### ISSUE TITLE
RTX 3090 Unsupported gpu architecture

### ISSUE THREAD

**Issue by hakkiyagiz** [NVIDIA/apex#1006]
nvcc fatal   : Unsupported gpu architecture 'compute_86'

`    nvcc fatal   : Unsupported gpu architecture 'compute_86'
    [11/11] c++ -MMD -MF /tmp/pip-req-build-ayif671c/build/temp.linux-x86_64-3.8/csrc/amp_C_frontend.o.d -pthread -B /home/dh/miniconda3/envs/fms2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include -I/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/TH -I/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/dh/miniconda3/envs/fms2/include/python3.8 -c -c /tmp/pip-req-build-ayif671c/csrc/amp_C_frontend.cpp -o /tmp/pip-req-build-ayif671c/build/temp.linux-x86_64-3.8/csrc/amp_C_frontend.o -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/ATen/Parallel.h:149,
                     from /home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:12,
                     from /home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                     from /tmp/pip-req-build-ayif671c/csrc/amp_C_frontend.cpp:1:
    /home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/include/ATen/ParallelOpenMP.h:84: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
       84 | #pragma omp parallel for if ((end - begin) >= grain_size)
          |
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1516, in _run_ninja_build
        subprocess.run(
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ayif671c/setup.py", line 405, in <module>
        setup(
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
        build_ext.build_extensions(self)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 473, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /home/dh/miniconda3/envs/fms2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ayif671c/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ayif671c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-4kcl1dne/install-record.txt --single-version-externally-managed --compile --install-headers /home/dh/miniconda3/envs/fms2/include/python3.8/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 838, in install
    success = install_legacy(
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 397, in run
    installed = install_given_reqs(
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 82, in install_given_reqs
    requirement.install(
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 856, in install
    six.reraise(*exc.parent)
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 273, in runner
    call_subprocess(
  File "/home/dh/miniconda3/envs/fms2/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/dh/miniconda3/envs/fms2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ayif671c/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ayif671c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-4kcl1dne/install-record.txt --single-version-externally-managed --compile --install-headers /home/dh/miniconda3/envs/fms2/include/python3.8/apex Check the logs for full command output.

**Comment by hakkiyagiz** [comment]
Worked like a charm [https://github.com/NVIDIA/apex/issues/988#issuecomment-726343453](url)

thanks

**Comment by Qi-Chuan** [comment]
Hello! Can you tell me how you solve the problem. I am confused with the solution of #988
