### ISSUE TITLE
Installation Error via cuda

### ISSUE THREAD

**Issue by chiehpower** [NVIDIA/apex#1034]
Hi, I can install successfully via command:
```
pip install -v --disable-pip-version-check --no-cache-dir ./
```
I wanna install Apex with CUDA and C++ extensions via
```
$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

However, it got error...

Here is my error message below:
```
/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py:234: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 20.3.3 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-xhr14d86
Created temporary directory: /tmp/pip-req-tracker-z3n3ekee
Initialized build tracking at /tmp/pip-req-tracker-z3n3ekee
Created build tracker: /tmp/pip-req-tracker-z3n3ekee
Entered build tracker: /tmp/pip-req-tracker-z3n3ekee
Created temporary directory: /tmp/pip-install-j_9b40v3
Processing /root/apex
  Created temporary directory: /tmp/pip-req-build-0gprabkz
  Added file:///root/apex to build tracker '/tmp/pip-req-tracker-z3n3ekee'
    Running setup.py (path:/tmp/pip-req-build-0gprabkz/setup.py) egg_info for package from file:///root/apex
    Created temporary directory: /tmp/pip-pip-egg-info-e0_p21a7
    Running command python setup.py egg_info


    torch.__version__  = 1.4.0


    running egg_info
    creating /tmp/pip-pip-egg-info-e0_p21a7/apex.egg-info
    writing /tmp/pip-pip-egg-info-e0_p21a7/apex.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-e0_p21a7/apex.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-e0_p21a7/apex.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-e0_p21a7/apex.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-e0_p21a7/apex.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-pip-egg-info-e0_p21a7/apex.egg-info/SOURCES.txt'
    /tmp/pip-req-build-0gprabkz/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
  Source in /tmp/pip-req-build-0gprabkz has version 0.1, which satisfies requirement apex==0.1 from file:///root/apex
  Removed apex==0.1 from file:///root/apex from build tracker '/tmp/pip-req-tracker-z3n3ekee'
Created temporary directory: /tmp/pip-unpack-4z3mv4tl
Skipping wheel build for apex, due to binaries being disabled for it.
Installing collected packages: apex
  Attempting uninstall: apex
    Found existing installation: apex 0.1
    Uninstalling apex-0.1:
      Created temporary directory: /usr/local/lib/python3.6/dist-packages/~pex-0.1.dist-info
      Removing file or directory /usr/local/lib/python3.6/dist-packages/apex-0.1.dist-info/
      Created temporary directory: /usr/local/lib/python3.6/dist-packages/~pex
      Removing file or directory /usr/local/lib/python3.6/dist-packages/apex/
      Successfully uninstalled apex-0.1
  Created temporary directory: /tmp/pip-record-nhrngrb0
    Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0gprabkz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0gprabkz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-nhrngrb0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/apex


    torch.__version__  = 1.4.0


    /tmp/pip-req-build-0gprabkz/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2019 NVIDIA Corporation
    Built on Wed_Oct_23_19:24:38_PDT_2019
    Cuda compilation tools, release 10.2, V10.2.89
    from /usr/local/cuda/bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-0gprabkz/setup.py", line 171, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-0gprabkz/setup.py", line 106, in check_cuda_torch_binary_vs_bare_metal
        "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.1.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
    Running setup.py install for apex ... error
  Rolling back uninstall of apex
  Moving to /usr/local/lib/python3.6/dist-packages/apex-0.1.dist-info/
   from /usr/local/lib/python3.6/dist-packages/~pex-0.1.dist-info
  Moving to /usr/local/lib/python3.6/dist-packages/apex/
   from /usr/local/lib/python3.6/dist-packages/~pex
  Replacing /usr/local/lib/python3.6/dist-packages/apex-0.1.dist-info/ from /usr/local/lib/python3.6/dist-packages/~pex-0.1.dist-info
  Replacing /usr/local/lib/python3.6/dist-packages/apex/ from /usr/local/lib/python3.6/dist-packages/~pex
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0gprabkz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0gprabkz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-nhrngrb0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 854, in install
    req_description=str(self.req),
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 403, in run
    pycompile=options.compile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 858, in install
    six.reraise(*exc.parent)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/install/legacy.py", line 76, in install
    cwd=unpacked_source_directory,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 275, in runner
    spinner=spinner,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0gprabkz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0gprabkz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-nhrngrb0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/apex Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-z3n3ekee'
```

I was installing in docker container with runtime nvidia.
The based image was from NGC TensorRT v20.03.01.

## Environment version
- pytorch 1.4 
- cuda version 10.2
- gcc v7.4.0
- OS ubuntu 18.04

Is there any idea about this?
Thank you!

**Comment by shrutishrestha** [comment]
same issue. Did you solve it?

**Comment by chiehpower** [comment]
> same issue. Did you solve it?

For this specific case, the answer is no.
However, I can run it based on this [Dockerfile](https://github.com/NVIDIA/apex/tree/master/examples/docker) that if you just wanna test NVIDIA APEX, then you can try this first.

**Comment by chiehpower** [comment]
> same issue. Did you solve it?

Hi @shrutishrestha , here is my [whole steps](https://github.com/chiehpower/Setup-deeplearning-tools/tree/master/NVIDIA-Apex). You can try this if you are interested in APEX performance.
