### ISSUE TITLE
Quick Start commands fail on latest docker image

### ISSUE THREAD

**Issue by BrainSlugs83** [NVIDIA/apex#1042]
The documentation in the `readme.md` on how to use this via docker seems to be really out of date (I wasn't able to get the instructions to work from Windows, or Ubuntu; so I figured I'd give the docker containers a try... 🤷🏻‍♂️)

Tried the NGC containers first -- but the URL that's listed is borked. -- if you go there, the page is just a broken template with no information and infinite loading of nothing... -- (in the Chrome console it looks like the page is trying to do insecure things like execute javascript files with bad mime types... so maybe it's being blocked in latest Chrome?)

So... let's go the other route...
```
$ docker pull "pytorch/pytorch:nightly-devel-cuda10.0-cudnn7"
nightly-devel-cuda10.0-cudnn7: Pulling from pytorch/pytorch
[...]

$ docker image ls -a
REPOSITORY        TAG                             IMAGE ID       CREATED         SIZE
pytorch/pytorch   nightly-devel-cuda10.0-cudnn7   a5b30513fbc1   19 months ago   6.4GB

$ docker run -it --rm --entrypoint bash "pytorch/pytorch:nightly-devel-cuda10.0-cudnn7"
```

On to the Quick Start instructions ...
```
$ git clone https://github.com/NVIDIA/apex
bash: git: command not found
```

So... it doesn't have git installed (the Quick Start seems to imply it should...) but whatever... we can fix that...

```
$ apt-get update && apt-get install git -yex
[...]
$ git clone https://github.com/NVIDIA/apex
[...]
$ cd apex
$ pip install -v --disable-pip-version-check --no-cache-dir ./
```

Here's the full output of that command:
(FYI: it's the same for the long and the short python only command)
```
$ pip install -v --disable-pip-version-check --no-cache-dir ./
Using pip 20.3.3 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-mpd8lx5y
Created temporary directory: /tmp/pip-req-tracker-v3xxu_td
Initialized build tracking at /tmp/pip-req-tracker-v3xxu_td
Created build tracker: /tmp/pip-req-tracker-v3xxu_td
Entered build tracker: /tmp/pip-req-tracker-v3xxu_td
Created temporary directory: /tmp/pip-install-kzvkti68
Processing /workspace/apex
  Created temporary directory: /tmp/pip-req-build-bzi2689z
  Added file:///workspace/apex to build tracker '/tmp/pip-req-tracker-v3xxu_td'
    Running setup.py (path:/tmp/pip-req-build-bzi2689z/setup.py) egg_info for package from file:///workspace/apex
    Created temporary directory: /tmp/pip-pip-egg-info-3q4n7u9f
    Running command python setup.py egg_info
    /opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370156314/work/c10/cuda/CUDAFunctions.cpp:100.)
      return torch._C._cuda_getDeviceCount() > 0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-bzi2689z/setup.py", line 35, in <module>
        _, bare_metal_major, _ = get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-bzi2689z/setup.py", line 14, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

    Warning: Torch did not find available GPUs on this system.
     If your intention is to cross-compile, this is not an error.
    By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
    Volta (compute capability 7.0), Turing (compute capability 7.5),
    and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
    If you wish to cross-compile for a single specific architecture,
    export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

**ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.**
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 169, in _merge_into_criterion
    name = self._p.identify(requirement)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 60, in identify
    return dependency.name
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 41, in name
    return self.candidate.name
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 188, in name
    return self.project_name
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 182, in project_name
    self._name = canonicalize_name(self.dist.project_name)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 319, in _prepare_distribution
    self._ireq, parallel_builds=True,
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 535, in _generate_metadata
    details=self.name or "from {}".format(self.link)
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 73, in generate_metadata
    command_desc='python setup.py egg_info',
  File "/opt/conda/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///workspace/apex from build tracker '/tmp/pip-req-tracker-v3xxu_td'
Removed build tracker: '/tmp/pip-req-tracker-v3xxu_td'
```

**Comment by kevinbro96** [comment]
I meet the same problem!
