### ISSUE TITLE
cannot import name 'container_abcs' from 'torch._six'

### ISSUE THREAD

**Issue by ShoufaChen** [NVIDIA/apex#1048]
```
>>> from apex import amp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/lustre/chenshoufa/anaconda3/envs/pytorch18/lib/python3.8/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/mnt/lustre/chenshoufa/anaconda3/envs/pytorch18/lib/python3.8/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/mnt/lustre/chenshoufa/anaconda3/envs/pytorch18/lib/python3.8/site-packages/apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "/mnt/lustre/chenshoufa/anaconda3/envs/pytorch18/lib/python3.8/site-packages/apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "/mnt/lustre/chenshoufa/anaconda3/envs/pytorch18/lib/python3.8/site-packages/apex/amp/wrap.py", line 3, in <module>
    from ._amp_state import _amp_state
  File "/mnt/lustre/chenshoufa/anaconda3/envs/pytorch18/lib/python3.8/site-packages/apex/amp/_amp_state.py", line 14, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (/mnt/lustre/chenshoufa/anaconda3/envs/pytorch18/lib/python3.8/site-packages/torch/_six.py)
```

**Comment by kawseribn** [comment]
```import collections.abc as container_abcs``` this might solve your problem

**Comment by parmarmanoj007** [comment]
downgrade PyTorch to 1.8

**Comment by anonymousleo** [comment]
i solved this error by following this [link](https://qiita.com/kid_med/items/4529708196098e2adddd)
