### ISSUE TITLE
apex install error. (Errno 13)

### ISSUE THREAD

**Issue by zerojooon** [NVIDIA/apex#1054]
I was trying to install apex with below commands

```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

But i got an error code like below

```

ERROR: Could not install packages due to an EnvironmentError.
Traceback (most recent call last):
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 169, in _merge_into_criterion
    name = self._p.identify(requirement)
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 60, in identify
    return dependency.name
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 41, in name
    return self.candidate.name
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 188, in name
    return self.project_name
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 182, in project_name
    self._name = canonicalize_name(self.dist.project_name)
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 319, in _prepare_distribution
    self._ireq, parallel_builds=True,
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 505, in _prepare_linked_requirement
    self.download_dir, hashes,
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 244, in unpack_url
    _copy_source_tree(link.file_path, location)
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 187, in _copy_source_tree
    shutil.copytree(source, target, **kwargs)
  File "/home/sdl/anaconda3/envs/deepspeed/lib/python3.6/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/home/sdl/DeepSpeedExamples/Megatron-LM/apex/.git/objects/pack/pack-241163e61d5f9eb45f0546772d079e96c56c4d05.idx', '/tmp/pip-req-build-ssz7ag06/.git/objects/pack/pack-241163e61d5f9eb45f0546772d079e96c56c4d05.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-ssz7ag06/.git/objects/pack/pack-241163e61d5f9eb45f0546772d079e96c56c4d05.idx'"), ('/home/sdl/DeepSpeedExamples/Megatron-LM/apex/.git/objects/pack/pack-241163e61d5f9eb45f0546772d079e96c56c4d05.pack', '/tmp/pip-req-build-ssz7ag06/.git/objects/pack/pack-241163e61d5f9eb45f0546772d079e96c56c4d05.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-ssz7ag06/.git/objects/pack/pack-241163e61d5f9eb45f0546772d079e96c56c4d05.pack'")]
Removed build tracker: '/tmp/pip-req-tracker-dafpw8m7'



```

How can i solve this error

=======
nvcc 10.1
python 3.6
gcc version 7.5.0
torch==1.7.1+cu101

**Comment by raytrun** [comment]
How can you solve it?

**Comment by zhaozhang** [comment]
I ran into the same issue. Any solution?

**Comment by 4-0-4-notfound** [comment]
same issue
