### ISSUE TITLE
UnencryptedCookieSessionFactoryConfig not available for newer versions of pyramid.sessions

### ISSUE THREAD

**Issue by rustil** [NVIDIA/apex#1063]
Installing apex through pip in an Anaconda python 3.8 environment yields:
```
>>> from apex import apm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path/lib/python3.8/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```
After having a look at the API documentation of pyramid it seems that indeed that name isn't available anymore in versions pyramid > 1.9. So I suppose replacing the `UnencryptedCookieSessionFactoryConfig` and/or specifying the maximally allowed pyramid version should do the trick.

The installed apex version is from pypy: `0.9.10.dev0`

**Comment by nikhilrayaprolu** [comment]
I too face the same issue!! Any response?

**Comment by rustil** [comment]
I downgraded my anaconda environment a bit so that I would find a workable dependency tree including `nvidia-apex` from `conda-forge` instead of this `pip` installed version.

The obtained and working package is:
`nvidia-apex               0.1              py37h3dc597d_3    conda-forge`

which doesn't seem to depend on pyramid.

**Comment by xloem** [comment]
The apex that depends on pyramid and cryptacular is an unrelated package to this one. This package does not depend on pyramid.

This issue arises when apex is installed from commandline package managers. Most python packages choose names that are unique on pypi, but there is another package with this name.
