### ISSUE TITLE
AttributeError: 'DistributedDataParallel' object has no attribute 'callback_queued'

### ISSUE THREAD

**Issue by LightToYang** [NVIDIA/apex#107]
My pytorch version is 1.0 stable.

```
Traceback (most recent call last):
  File "train_cosine_iterations_distributed.py", line 420, in <module>
    optimizer.backward(loss)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/fp16_utils/fp16_optimizer.py", line 482, in backward
    self.loss_scaler.backward(loss.float())
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/fp16_utils/loss_scaler.py", line 45, in backward
    scaled_loss.backward()
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 340, in allreduce_hook
    if not self.callback_queued:
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute 'callback_queued'
```

**Comment by LightToYang** [comment]
It seems that I write the incorrect code leading to the error.

**Comment by KamInNg** [comment]
Hi, @LightToYang 
I got the same Error. Could you tell me the detail of reason in your case?
Thank you!

**Comment by pldelisle** [comment]
Interested in your workaround too. I got the same error.

**Comment by xieydd** [comment]
@pldelisle @KamInNg  @LightToYang I meet this issue in custom loss when use `model.parameters()`

**Comment by xieydd** [comment]
All, I solve the problem; Linked the issue #457

**Comment by vibhavagarwal5** [comment]
Does `model = model.module` helps in solving the issue?

**Comment by ZhengshengGuo** [comment]
Hello! I have the same error. Can someone give me a hand to solving the issue? Thankuuuuu!!
