### ISSUE TITLE
Failed to install apex

### ISSUE THREAD

**Issue by notooth1** [NVIDIA/apex#1073]
I failed to install apex. Can anyone help?

```
$ pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" git+https://github.com/NVIDIA/apex.git@e2083df5eb96643c61613b9df48dd4eea6b07690

    building 'amp_C' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-oers0g5e/setup.py", line 456, in <module>
        setup(
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/notooth/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/notooth/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/notooth/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/notooth/anaconda3/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/notooth/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/notooth/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/notooth/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/notooth/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/notooth/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/notooth/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
        build_ext.build_extensions(self)
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/notooth/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/notooth/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/notooth/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 486, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 395, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags) +
      File "/home/notooth/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1438, in _get_cuda_arch_flags
        raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
    ValueError: Unknown CUDA arch (compute) or GPU not supported
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /home/notooth/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-oers0g5e/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-oers0g5e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-m60kw6xk/install-record.txt --single-version-externally-managed --compile --install-headers /home/notooth/anaconda3/include/python3.8/apex Check the logs for full command output.                                                                      
Exception information:
Traceback (most recent call last):
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 838, in install
    success = install_legacy(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 397, in run
    installed = install_given_reqs(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 82, in install_given_reqs
    requirement.install(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 856, in install
    six.reraise(*exc.parent)
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 273, in runner
    call_subprocess(
  File "/home/notooth/anaconda3/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/notooth/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-oers0g5e/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-oers0g5e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-m60kw6xk/install-record.txt --single-version-externally-managed --compile --install-headers /home/notooth/anaconda3/include/python3.8/apex Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-du50jqwm'
```

**Comment by ilyak93** [comment]
How you fixed it ?

**Comment by notooth1** [comment]
Somewhere in the installation process suggested me to ` export TORCH_CUDA_ARCH_LIST="compute capability" ` which caused the issue. Disabling the export fixed the issue.

**Comment by mahdiabavisani** [comment]
If you have run `export TORCH_CUDA_ARCH_LIST="compute capability"`, `unset TORCH_CUDA_ARCH_LIST` fixed the issue for me.

**Comment by Maydaytyh** [comment]
> If you have run `export TORCH_CUDA_ARCH_LIST="compute capability"`, `unset TORCH_CUDA_ARCH_LIST` fixed the issue for me.

thx! It works for me.
