### ISSUE TITLE
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by davjd98** [NVIDIA/apex#1106]
# Error message

    csrc/mlp_cuda.cu(194): error: identifier "cublasLtMatmulDescOpaque_t" is undefined

    csrc/mlp_cuda.cu(195): error: identifier "cublasLtMatrixLayoutOpaque_t" is undefined

    csrc/mlp_cuda.cu(196): error: identifier "cublasLtMatmulPreferenceOpaque_t" is undefined

    csrc/mlp_cuda.cu(205): error: identifier "CUBLAS_COMPUTE_32F" is undefined

    csrc/mlp_cuda.cu(205): error: identifier "cublasLtMatmulDescInit" is undefined

    csrc/mlp_cuda.cu(234): error: identifier "cublasLtMatrixLayoutInit" is undefined

    csrc/mlp_cuda.cu(248): error: identifier "cublasLtMatmulPreferenceInit" is undefined

    csrc/mlp_cuda.cu(336): error: identifier "cublasLtMatmulDescOpaque_t" is undefined

    csrc/mlp_cuda.cu(337): error: identifier "cublasLtMatrixLayoutOpaque_t" is undefined

    csrc/mlp_cuda.cu(338): error: identifier "cublasLtMatmulPreferenceOpaque_t" is undefined

    csrc/mlp_cuda.cu(347): error: identifier "CUBLAS_COMPUTE_32F" is undefined

    csrc/mlp_cuda.cu(347): error: identifier "cublasLtMatmulDescInit" is undefined

    csrc/mlp_cuda.cu(376): error: identifier "cublasLtMatrixLayoutInit" is undefined

    csrc/mlp_cuda.cu(390): error: identifier "cublasLtMatmulPreferenceInit" is undefined

    14 errors detected in the compilation of "/tmp/tmpxft_0000822e_00000000-6_mlp_cuda.cpp1.ii".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /home/jindawei/miniconda3/envs/trans/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-77p_7_23/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-77p_7_23/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-x447l0fz/install-record.txt --single-version-externally-managed --compile --install-headers /home/jindawei/miniconda3/envs/trans/include/python3.8/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 806, in install
    success = install_legacy(
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 81, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 393, in run
    installed = install_given_reqs(
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 77, in install_given_reqs
    requirement.install(
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 824, in install
    six.reraise(*exc.parent)
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 69, in install
    runner(
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 274, in runner
    call_subprocess(
  File "/home/jindawei/miniconda3/envs/trans/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/jindawei/miniconda3/envs/trans/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-77p_7_23/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-77p_7_23/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-x447l0fz/install-record.txt --single-version-externally-managed --compile --install-headers /home/jindawei/miniconda3/envs/trans/include/python3.8/apex Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-khuujrmh'

# Environment
## Ubuntu
$ cat /etc/issue
Ubuntu 16.04.6 LTS \n \l
## nvcc
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
## torch
>>> import torch
>>> print(torch.__version__)
1.8.1+cu102
## python
python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
## gcc
$ gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.

# Code for installation
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

**Comment by davjd98** [comment]
I have seen a similar post #797, but it does not solve my problem

**Comment by davjd98** [comment]
git reset --hard a651e2c24ecf97cbf367fd3f330df36760e1c597 seems solve my problem. Verifying now.

**Comment by davjd98** [comment]
git reset --hard a651e2c24ecf97cbf367fd3f330df36760e1c597 
The solution from #1091 works for me.
