### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Ardor-Wu** [NVIDIA/apex#1112]
I followed Quick Start but got the following error message:
(wolf) ardor@cori19:~/apex> pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/commands/install.py:232: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.1.1 from /global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-xbvi395s
Created temporary directory: /tmp/pip-req-tracker-gyye4pav
Initialized build tracking at /tmp/pip-req-tracker-gyye4pav
Created build tracker: /tmp/pip-req-tracker-gyye4pav
Entered build tracker: /tmp/pip-req-tracker-gyye4pav
Created temporary directory: /tmp/pip-install-lymajxn4
Processing /global/u1/a/ardor/apex
  Created temporary directory: /tmp/pip-req-build-3vlqbiqi
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Added file:///global/u1/a/ardor/apex to build tracker '/tmp/pip-req-tracker-gyye4pav'
    Running setup.py (path:/tmp/pip-req-build-3vlqbiqi/setup.py) egg_info for package from file:///global/u1/a/ardor/apex
    Created temporary directory: /tmp/pip-pip-egg-info-9miicexf
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-3vlqbiqi/setup.py", line 35, in <module>
        _, bare_metal_major, _ = get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-3vlqbiqi/setup.py", line 14, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

    Warning: Torch did not find available GPUs on this system.
     If your intention is to cross-compile, this is not an error.
    By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
    Volta (compute capability 7.0), Turing (compute capability 7.5),
    and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
    If you wish to cross-compile for a single specific architecture,
    export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

WARNING: Discarding file:///global/u1/a/ardor/apex. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    r = self.factory.make_requirement_from_install_req(
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 433, in make_requirement_from_install_req
    raise self._build_failures[ireq.link]
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    super().__init__(
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 36, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 544, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 519, in _generate_metadata
    return generate_metadata_legacy(
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 67, in generate_metadata
    call_subprocess(
  File "/global/homes/a/ardor/.conda/envs/wolf/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///global/u1/a/ardor/apex from build tracker '/tmp/pip-req-tracker-gyye4pav'
Removed build tracker: '/tmp/pip-req-tracker-gyye4pav'

I really appreciate any help you can provide.

**Comment by mindmapper15** [comment]
It will be easier to find solution if you post your hardware, environment, etc.
