### ISSUE TITLE
LegacyInstallFailure installation error

### ISSUE THREAD

**Issue by binerone** [NVIDIA/apex#1128]
Environment:
    Pytorch: 1.7.1
    Cuda: 11.0
    Cudnn: 11.0
    gcc: 7.5.0
    g++:7.5.0
    GPU Card: 3090

Major error log:
` g++ -pthread -shared -B /home/yanbin/anaconda3/envs/apex/compiler_compat -L/home/yanbin/anaconda3/envs/apex/lib -Wl,-rpath=/home/yanbin/anaconda3/envs/apex/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-req-build-5xltav2c/build/temp.linux-x86_64-3.8/csrc/flatten_unflatten.o -L/home/yanbin/anaconda3/envs/apex/lib/python3.8/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.8/apex_C.cpython-38-x86_64-linux-gnu.so
    g++: error: /tmp/pip-req-build-5xltav2c/build/temp.linux-x86_64-3.8/csrc/flatten_unflatten.o: 没有那个文件或目录
    error: command 'g++' failed with exit status 1
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /home/yanbin/anaconda3/envs/apex/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-5xltav2c/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-5xltav2c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-5pyuswje/install-record.txt --single-version-externally-managed --compile --install-headers /home/yanbin/anaconda3/envs/apex/include/python3.8/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/yanbin/anaconda3/envs/apex/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 812, in install
    success = install_legacy(
  File "/home/yanbin/anaconda3/envs/apex/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure
`

Thanks for help.

**Comment by ake020675** [comment]
me too

**Comment by JayRane1** [comment]
same problem any solution
