### ISSUE TITLE
An install problem.Cuda11.2 torch1.9.0

### ISSUE THREAD

**Issue by liuyuan000** [NVIDIA/apex#1133]
```

    torch.__version__  = 1.9.0+cu102


    /tmp/pip-req-build-xogkfxc5/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2021 NVIDIA Corporation
    Built on Sun_Feb_14_21:12:58_PST_2021
    Cuda compilation tools, release 11.2, V11.2.152
    Build cuda_11.2.r11.2/compiler.29618528_0
    from /usr/local/cuda/bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-xogkfxc5/setup.py", line 171, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-xogkfxc5/setup.py", line 102, in check_cuda_torch_binary_vs_bare_metal
        raise RuntimeError("Cuda extensions are being compiled with a version of Cuda that does " +
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.2.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /home/liuyuan/anaconda3/envs/yolox/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-xogkfxc5/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-xogkfxc5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-wm_6rdtx/install-record.txt --single-version-externally-managed --compile --install-headers /home/liuyuan/anaconda3/envs/yolox/include/python3.8/apex Check the logs for full command output.
```
can you tell me how to install it?

**Comment by ShoufaChen** [comment]
Your PyTorch is compiled with Cuda 10.2 instead of 11.2 from 
 `RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.2.
`

**Comment by mikel-brostrom** [comment]
Check your CUDA installation with:

```
nvidia-smi
```

you will see something like  CUDA Version: XX.X, top right. Go to https://pytorch.org/ and install the PyTorch version compiled with the CUDA version closest to your CUDA installation. In your case this would be

```
pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
```

Then, under `apex/setup.py` comment out lines (101-107):

https://github.com/NVIDIA/apex/blob/0c2c6eea6556b208d1a8711197efc94899e754e1/setup.py#L101

**Comment by evilc3** [comment]
No need to install anything. your can change the symilink of cuda to point to cuda10.1 as colab already has it installed.  you can check this post. https://vitalitylearning.medium.com/running-cuda-in-google-colab-525a92efcf75
