### ISSUE TITLE
install apex error, flatten_unflatten.obj cannot open

### ISSUE THREAD

**Issue by MrBook2019** [NVIDIA/apex#1141]
python 3.8.11
CUDA: V10.2.89
CUDNN: V8.2.1.32
pytorch: 1.9.0+cu102
GPU: GTX1650
Driver Version: 457.49

pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
D:\ProgramData\Anaconda3\envs\yolo\lib\site-packages\pip\_internal\commands\install.py:229: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.2.2 from D:\ProgramData\Anaconda3\envs\yolo\lib\site-packages\pip (python 3.8)
Looking in indexes: https://pypi.douban.com/simple
Processing d:\ailearn\python\book\yolox\apex
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    Running command python setup.py egg_info

    torch.__version__  = 1.9.0+cu102

    running egg_info
    creating C:\Users\Book\AppData\Local\Temp\pip-pip-egg-info-dwmghvsi\apex.egg-info
    writing C:\Users\Book\AppData\Local\Temp\pip-pip-egg-info-dwmghvsi\apex.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Book\AppData\Local\Temp\pip-pip-egg-info-dwmghvsi\apex.egg-info\dependency_links.txt
    writing top-level names to C:\Users\Book\AppData\Local\Temp\pip-pip-egg-info-dwmghvsi\apex.egg-info\top_level.txt
    writing manifest file 'C:\Users\Book\AppData\Local\Temp\pip-pip-egg-info-dwmghvsi\apex.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\Book\AppData\Local\Temp\pip-pip-egg-info-dwmghvsi\apex.egg-info\SOURCES.txt'
    writing manifest file 'C:\Users\Book\AppData\Local\Temp\pip-pip-egg-info-dwmghvsi\apex.egg-info\SOURCES.txt'
    C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "D:\ProgramData\Anaconda3\envs\yolo\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
Skipping wheel build for apex, due to binaries being disabled for it.
Installing collected packages: apex
    Running command 'D:\ProgramData\Anaconda3\envs\yolo\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Book\\AppData\\Local\\Temp\\pip-req-build-l1fi33a9\\setup.py'"'"'; __file__='"'"'C:\\Users\\Book\\AppData\\Local\\Temp\\pip-req-build-l1fi33a9\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record 'C:\Users\Book\AppData\Local\Temp\pip-record-zh_dgdl2\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ProgramData\Anaconda3\envs\yolo\Include\apex'

    torch.__version__  = 1.9.0+cu102

    C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2019 NVIDIA Corporation
    Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
    Cuda compilation tools, release 10.2, V10.2.89
    from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2/bin

    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\apex
    copying apex\__init__.py -> build\lib.win-amd64-3.8\apex
    creating build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\amp.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\compat.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\frontend.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\handle.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\opt.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\rnn_compat.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\scaler.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\utils.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\wrap.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\_amp_state.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\_initialize.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\_process_optimizer.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\__init__.py -> build\lib.win-amd64-3.8\apex\amp
    copying apex\amp\__version__.py -> build\lib.win-amd64-3.8\apex\amp
    creating build\lib.win-amd64-3.8\apex\contrib
    copying apex\contrib\__init__.py -> build\lib.win-amd64-3.8\apex\contrib
    creating build\lib.win-amd64-3.8\apex\fp16_utils
    copying apex\fp16_utils\fp16util.py -> build\lib.win-amd64-3.8\apex\fp16_utils
    copying apex\fp16_utils\fp16_optimizer.py -> build\lib.win-amd64-3.8\apex\fp16_utils
    copying apex\fp16_utils\loss_scaler.py -> build\lib.win-amd64-3.8\apex\fp16_utils
    copying apex\fp16_utils\__init__.py -> build\lib.win-amd64-3.8\apex\fp16_utils
    creating build\lib.win-amd64-3.8\apex\mlp
    copying apex\mlp\mlp.py -> build\lib.win-amd64-3.8\apex\mlp
    copying apex\mlp\__init__.py -> build\lib.win-amd64-3.8\apex\mlp
    creating build\lib.win-amd64-3.8\apex\multi_tensor_apply
    copying apex\multi_tensor_apply\multi_tensor_apply.py -> build\lib.win-amd64-3.8\apex\multi_tensor_apply
    copying apex\multi_tensor_apply\__init__.py -> build\lib.win-amd64-3.8\apex\multi_tensor_apply
    creating build\lib.win-amd64-3.8\apex\normalization
    copying apex\normalization\fused_layer_norm.py -> build\lib.win-amd64-3.8\apex\normalization
    copying apex\normalization\__init__.py -> build\lib.win-amd64-3.8\apex\normalization
    creating build\lib.win-amd64-3.8\apex\optimizers
    copying apex\optimizers\fused_adagrad.py -> build\lib.win-amd64-3.8\apex\optimizers
    copying apex\optimizers\fused_adam.py -> build\lib.win-amd64-3.8\apex\optimizers
    copying apex\optimizers\fused_lamb.py -> build\lib.win-amd64-3.8\apex\optimizers
    copying apex\optimizers\fused_novograd.py -> build\lib.win-amd64-3.8\apex\optimizers
    copying apex\optimizers\fused_sgd.py -> build\lib.win-amd64-3.8\apex\optimizers
    copying apex\optimizers\__init__.py -> build\lib.win-amd64-3.8\apex\optimizers
    creating build\lib.win-amd64-3.8\apex\parallel
    copying apex\parallel\distributed.py -> build\lib.win-amd64-3.8\apex\parallel
    copying apex\parallel\LARC.py -> build\lib.win-amd64-3.8\apex\parallel
    copying apex\parallel\multiproc.py -> build\lib.win-amd64-3.8\apex\parallel
    copying apex\parallel\optimized_sync_batchnorm.py -> build\lib.win-amd64-3.8\apex\parallel
    copying apex\parallel\optimized_sync_batchnorm_kernel.py -> build\lib.win-amd64-3.8\apex\parallel
    copying apex\parallel\sync_batchnorm.py -> build\lib.win-amd64-3.8\apex\parallel
    copying apex\parallel\sync_batchnorm_kernel.py -> build\lib.win-amd64-3.8\apex\parallel
    copying apex\parallel\__init__.py -> build\lib.win-amd64-3.8\apex\parallel
    creating build\lib.win-amd64-3.8\apex\pyprof
    copying apex\pyprof\__init__.py -> build\lib.win-amd64-3.8\apex\pyprof
    creating build\lib.win-amd64-3.8\apex\reparameterization
    copying apex\reparameterization\reparameterization.py -> build\lib.win-amd64-3.8\apex\reparameterization
    copying apex\reparameterization\weight_norm.py -> build\lib.win-amd64-3.8\apex\reparameterization
    copying apex\reparameterization\__init__.py -> build\lib.win-amd64-3.8\apex\reparameterization
    creating build\lib.win-amd64-3.8\apex\RNN
    copying apex\RNN\cells.py -> build\lib.win-amd64-3.8\apex\RNN
    copying apex\RNN\models.py -> build\lib.win-amd64-3.8\apex\RNN
    copying apex\RNN\RNNBackend.py -> build\lib.win-amd64-3.8\apex\RNN
    copying apex\RNN\__init__.py -> build\lib.win-amd64-3.8\apex\RNN
    creating build\lib.win-amd64-3.8\apex\amp\lists
    copying apex\amp\lists\functional_overrides.py -> build\lib.win-amd64-3.8\apex\amp\lists
    copying apex\amp\lists\tensor_overrides.py -> build\lib.win-amd64-3.8\apex\amp\lists
    copying apex\amp\lists\torch_overrides.py -> build\lib.win-amd64-3.8\apex\amp\lists
    copying apex\amp\lists\__init__.py -> build\lib.win-amd64-3.8\apex\amp\lists
    creating build\lib.win-amd64-3.8\apex\contrib\bottleneck
    copying apex\contrib\bottleneck\bottleneck.py -> build\lib.win-amd64-3.8\apex\contrib\bottleneck
    copying apex\contrib\bottleneck\test.py -> build\lib.win-amd64-3.8\apex\contrib\bottleneck
    copying apex\contrib\bottleneck\__init__.py -> build\lib.win-amd64-3.8\apex\contrib\bottleneck
    creating build\lib.win-amd64-3.8\apex\contrib\fmha
    copying apex\contrib\fmha\fmha.py -> build\lib.win-amd64-3.8\apex\contrib\fmha
    copying apex\contrib\fmha\__init__.py -> build\lib.win-amd64-3.8\apex\contrib\fmha
    creating build\lib.win-amd64-3.8\apex\contrib\groupbn
    copying apex\contrib\groupbn\batch_norm.py -> build\lib.win-amd64-3.8\apex\contrib\groupbn
    copying apex\contrib\groupbn\__init__.py -> build\lib.win-amd64-3.8\apex\contrib\groupbn
    creating build\lib.win-amd64-3.8\apex\contrib\layer_norm
    copying apex\contrib\layer_norm\layer_norm.py -> build\lib.win-amd64-3.8\apex\contrib\layer_norm
    copying apex\contrib\layer_norm\__init__.py -> build\lib.win-amd64-3.8\apex\contrib\layer_norm
    creating build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\encdec_multihead_attn.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\encdec_multihead_attn_func.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\fast_encdec_multihead_attn_func.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\fast_encdec_multihead_attn_norm_add_func.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\fast_self_multihead_attn_func.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\fast_self_multihead_attn_norm_add_func.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\mask_softmax_dropout_func.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\self_multihead_attn.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\self_multihead_attn_func.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    copying apex\contrib\multihead_attn\__init__.py -> build\lib.win-amd64-3.8\apex\contrib\multihead_attn
    creating build\lib.win-amd64-3.8\apex\contrib\optimizers
    copying apex\contrib\optimizers\distributed_fused_adam.py -> build\lib.win-amd64-3.8\apex\contrib\optimizers
    copying apex\contrib\optimizers\distributed_fused_adam_v2.py -> build\lib.win-amd64-3.8\apex\contrib\optimizers
    copying apex\contrib\optimizers\distributed_fused_adam_v3.py -> build\lib.win-amd64-3.8\apex\contrib\optimizers
    copying apex\contrib\optimizers\distributed_fused_lamb.py -> build\lib.win-amd64-3.8\apex\contrib\optimizers
    copying apex\contrib\optimizers\fp16_optimizer.py -> build\lib.win-amd64-3.8\apex\contrib\optimizers
    copying apex\contrib\optimizers\fused_adam.py -> build\lib.win-amd64-3.8\apex\contrib\optimizers
    copying apex\contrib\optimizers\fused_lamb.py -> build\lib.win-amd64-3.8\apex\contrib\optimizers
    copying apex\contrib\optimizers\fused_sgd.py -> build\lib.win-amd64-3.8\apex\contrib\optimizers
    copying apex\contrib\optimizers\__init__.py -> build\lib.win-amd64-3.8\apex\contrib\optimizers
    creating build\lib.win-amd64-3.8\apex\contrib\sparsity
    copying apex\contrib\sparsity\asp.py -> build\lib.win-amd64-3.8\apex\contrib\sparsity
    copying apex\contrib\sparsity\sparse_masklib.py -> build\lib.win-amd64-3.8\apex\contrib\sparsity
    copying apex\contrib\sparsity\__init__.py -> build\lib.win-amd64-3.8\apex\contrib\sparsity
    creating build\lib.win-amd64-3.8\apex\contrib\transducer
    copying apex\contrib\transducer\transducer.py -> build\lib.win-amd64-3.8\apex\contrib\transducer
    copying apex\contrib\transducer\__init__.py -> build\lib.win-amd64-3.8\apex\contrib\transducer
    creating build\lib.win-amd64-3.8\apex\contrib\xentropy
    copying apex\contrib\xentropy\softmax_xentropy.py -> build\lib.win-amd64-3.8\apex\contrib\xentropy
    copying apex\contrib\xentropy\__init__.py -> build\lib.win-amd64-3.8\apex\contrib\xentropy
    creating build\lib.win-amd64-3.8\apex\pyprof\nvtx
    copying apex\pyprof\nvtx\nvmarker.py -> build\lib.win-amd64-3.8\apex\pyprof\nvtx
    copying apex\pyprof\nvtx\__init__.py -> build\lib.win-amd64-3.8\apex\pyprof\nvtx
    creating build\lib.win-amd64-3.8\apex\pyprof\parse
    copying apex\pyprof\parse\db.py -> build\lib.win-amd64-3.8\apex\pyprof\parse
    copying apex\pyprof\parse\kernel.py -> build\lib.win-amd64-3.8\apex\pyprof\parse
    copying apex\pyprof\parse\nvvp.py -> build\lib.win-amd64-3.8\apex\pyprof\parse
    copying apex\pyprof\parse\parse.py -> build\lib.win-amd64-3.8\apex\pyprof\parse
    copying apex\pyprof\parse\__init__.py -> build\lib.win-amd64-3.8\apex\pyprof\parse
    copying apex\pyprof\parse\__main__.py -> build\lib.win-amd64-3.8\apex\pyprof\parse
    creating build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\activation.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\base.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\blas.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\conv.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\convert.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\data.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\dropout.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\embedding.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\index_slice_join_mutate.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\linear.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\loss.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\misc.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\normalization.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\optim.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\output.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\pointwise.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\pooling.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\prof.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\randomSample.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\recurrentCell.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\reduction.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\softmax.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\usage.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\utility.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\__init__.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    copying apex\pyprof\prof\__main__.py -> build\lib.win-amd64-3.8\apex\pyprof\prof
    running build_ext
    building 'apex_C' extension
    creating C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\build\temp.win-amd64-3.8
    creating C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\build\temp.win-amd64-3.8\Release
    creating C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\build\temp.win-amd64-3.8\Release\csrc
    Emitting ninja build file C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\build\temp.win-amd64-3.8\Release\build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    1.10.2.git.kitware.jobserver-1
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\ProgramData\Anaconda3\envs\yolo\lib\site-packages\torch\lib /LIBPATH:D:\ProgramData\Anaconda3\envs\yolo\libs /LIBPATH:D:\ProgramData\Anaconda3\envs\yolo\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit_apex_C C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\build\temp.win-amd64-3.8\Release\csrc/flatten_unflatten.obj /OUT:build\lib.win-amd64-3.8\apex_C.cp38-win_amd64.pyd /IMPLIB:C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\build\temp.win-amd64-3.8\Release\csrc\apex_C.cp38-win_amd64.lib
    **LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\build\temp.win-amd64-3.8\Release\csrc\flatten_unflatten.obj”**
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "D:\ProgramData\Anaconda3\envs\yolo\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: 'D:\ProgramData\Anaconda3\envs\yolo\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Book\\AppData\\Local\\Temp\\pip-req-build-l1fi33a9\\setup.py'"'"'; __file__='"'"'C:\\Users\\Book\\AppData\\Local\\Temp\\pip-req-build-l1fi33a9\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record 'C:\Users\Book\AppData\Local\Temp\pip-record-zh_dgdl2\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ProgramData\Anaconda3\envs\yolo\Include\apex' Check the logs for full command output.

**Comment by MrBook2019** [comment]
when i install apex , it failed :
**LINK : fatal error LNK1181: 无法打开输入文件“C:\Users\Book\AppData\Local\Temp\pip-req-build-l1fi33a9\build\temp.win-amd64-3.8\Release\csrc\flatten_unflatten.obj”**
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

anybody known how can i fix it?

**Comment by vaze1025** [comment]
Hi~Have you solved this problem? I met a same one:(

**Comment by hjp819** [comment]
I met a same one.

**Comment by GreenTeaHua** [comment]
vs2019+py37+ cuda11.1 was ok。
but，vs2019+py39+ cuda11.3 failed。

**Comment by Tsar06** [comment]
Same problem with CUDA 11.6, VS 2022 PY38
Seems a bug here - how can we fix this?

**Comment by AkKari808** [comment]
Same to me
