### ISSUE TITLE
Removed build tracker: '/tmp/pip-req-tracker-m9gpggek'

### ISSUE THREAD

**Issue by skye95git** [NVIDIA/apex#1169]
When I run `pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./`, there is an error:
```shell
/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/commands/install.py:232: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.1.3 from /home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip (python 3.6)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-ele8krc6
Created temporary directory: /tmp/pip-req-tracker-m9gpggek
Initialized build tracking at /tmp/pip-req-tracker-m9gpggek
Created build tracker: /tmp/pip-req-tracker-m9gpggek
Entered build tracker: /tmp/pip-req-tracker-m9gpggek
Created temporary directory: /tmp/pip-install-fyld8iws
Processing /home/linjiayi/apex
  Created temporary directory: /tmp/pip-req-build-ntg76bpi
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
ERROR: Could not install packages due to an OSError.
Traceback (most recent call last):
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
    req, requested_extras=()
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 434, in make_requirement_from_install_req
    version=None,
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 205, in _make_candidate_from_link
    version=version,
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 312, in __init__
    version=version,
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
    self._ireq, parallel_builds=True
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 552, in _prepare_linked_requirement
    self.download_dir, hashes
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 230, in unpack_url
    _copy_source_tree(link.file_path, location)
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 157, in _copy_source_tree
    copy_function=_copy2_ignoring_special_files,
  File "/home/linjiayi/anaconda3/envs/python36/lib/python3.6/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/home/linjiayi/apex/.git/objects/pack/pack-e03fd17c90bd1410366202603f249bd0aad60005.pack', '/tmp/pip-req-build-ntg76bpi/.git/objects/pack/pack-e03fd17c90bd1410366202603f249bd0aad60005.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-ntg76bpi/.git/objects/pack/pack-e03fd17c90bd1410366202603f249bd0aad60005.pack'"), ('/home/linjiayi/apex/.git/objects/pack/pack-e03fd17c90bd1410366202603f249bd0aad60005.idx', '/tmp/pip-req-build-ntg76bpi/.git/objects/pack/pack-e03fd17c90bd1410366202603f249bd0aad60005.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-ntg76bpi/.git/objects/pack/pack-e03fd17c90bd1410366202603f249bd0aad60005.idx'")]
Removed build tracker: '/tmp/pip-req-tracker-m9gpggek'
```

Then I run `python setup.py install`. It works:
```shell
Installed /home/linjiayi/anaconda3/envs/python36/lib/python3.6/site-packages/apex-0.1-py3.6.egg
Processing dependencies for apex==0.1
Finished processing dependencies for apex==0.1
```
<img width="634" alt="捕获" src="https://user-images.githubusercontent.com/41561936/133763783-2c80ff77-ed32-46d6-894f-7f9235896d8e.PNG">

But when I run my codes, there still is an error:
```shell
Traceback (most recent call last):
  File "tools/generate_samples_gpt.py", line 27, in <module>
    from megatron.checkpointing import load_checkpoint
  File "/home/linjiayi/Megatron-LM/megatron/checkpointing.py", line 25, in <module>
    from megatron import (get_args,
  File "/home/linjiayi/Megatron-LM/megatron/utils.py", line 24, in <module>
    import amp_C
ModuleNotFoundError: No module named 'amp_C'
```

What should I do?

**Comment by Kravrolens** [comment]
Put an eye in.

**Comment by ptrblck** [comment]
You are running into:
```python
[Errno 13] Permission denied
```
issues so make sure `pip` is able to write to the desired locations.
