### ISSUE TITLE
Can't install apex

### ISSUE THREAD

**Issue by Haddybaba123** [NVIDIA/apex#1170]
i tried pip install apex but it didn't worked and is showing the error below
`C:\Users\Haddy-PC>pip install apex
WARNING: Ignoring invalid distribution -ip (f:\apps\anaconda\lib\site-packages)
WARNING: Ignoring invalid distribution - (f:\apps\anaconda\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (f:\apps\anaconda\lib\site-packages)
WARNING: Ignoring invalid distribution - (f:\apps\anaconda\lib\site-packages)
Collecting apex
  Using cached apex-0.9.10.dev0-py3-none-any.whl
Collecting cryptacular
  Using cached cryptacular-1.6.2.tar.gz (75 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'f:\apps\anaconda\python.exe' 'f:\apps\anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Haddy-PC\AppData\Local\Temp\tmpu0qgh85p'
         cwd: C:\Users\Haddy-PC\AppData\Local\Temp\pip-install-_nfjsx88\cryptacular_151af672f68d44de8bf2f29431158c40
    Complete output (50 lines):
    scons: Reading SConscript files ...

    scons: warning: VC version 14.1 not installed.  C/C++ compilers are most likely not set correctly.
     Installed versions are: []
    File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-install-_nfjsx88\cryptacular_151af672f68d44de8bf2f29431158c40\SConstruct", line 27, in <module>

    scons: warning: VC version 14.1 not installed.  C/C++ compilers are most likely not set correctly.
     Installed versions are: []
    File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-install-_nfjsx88\cryptacular_151af672f68d44de8bf2f29431158c40\SConstruct", line 27, in <module>
    DistutilsPlatformError: Unable to find vcvarsall.bat:
      File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-install-_nfjsx88\cryptacular_151af672f68d44de8bf2f29431158c40\SConstruct", line 27:
        env = Environment(
      File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-build-env-jb0053aa\overlay\Lib\site-packages\SCons\Environment.py", line 1010:
        apply_tools(self, tools, toolpath)
      File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-build-env-jb0053aa\overlay\Lib\site-packages\SCons\Environment.py", line 116:
        _ = env.Tool(tool)
      File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-build-env-jb0053aa\overlay\Lib\site-packages\SCons\Environment.py", line 1879:
        tool(self)
      File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-build-env-jb0053aa\overlay\Lib\site-packages\enscons\cpyext.py", line 108:
        ext = get_build_ext()
      File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-build-env-jb0053aa\overlay\Lib\site-packages\enscons\cpyext.py", line 84:
        cmd.run()
      File "f:\apps\anaconda\lib\distutils\command\build_ext.py", line 340:
        self.build_extensions()
      File "f:\apps\anaconda\lib\distutils\command\build_ext.py", line 449:
        self._build_extensions_serial()
      File "f:\apps\anaconda\lib\distutils\command\build_ext.py", line 474:
        self.build_extension(ext)
      File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-build-env-jb0053aa\overlay\Lib\site-packages\enscons\cpyext.py", line 64:
        build_ext.build_extension(self, ext)
      File "f:\apps\anaconda\lib\distutils\command\build_ext.py", line 528:
        objects = self.compiler.compile(sources,
      File "f:\apps\anaconda\lib\distutils\_msvccompiler.py", line 327:
        self.initialize()
      File "f:\apps\anaconda\lib\distutils\_msvccompiler.py", line 224:
        vc_env = _get_vc_env(plat_spec)
      File "f:\apps\anaconda\lib\distutils\_msvccompiler.py", line 126:
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    Traceback (most recent call last):
      File "f:\apps\anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
        main()
      File "f:\apps\anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "f:\apps\anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-build-env-jb0053aa\overlay\Lib\site-packages\enscons\api.py", line 35, in prepare_metadata_for_build_wheel
        return _run("dist_info")
      File "C:\Users\Haddy-PC\AppData\Local\Temp\pip-build-env-jb0053aa\overlay\Lib\site-packages\enscons\api.py", line 29, in _run
        lookup = SCons.Node.arg2nodes_lookups[0](alias).sources[0]
    AttributeError: 'NoneType' object has no attribute 'sources'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/42/69/34d478310d6c4451e5ddeabe879b28cc304173e0301b3568eca88ec65112/cryptacular-1.6.2.tar.gz#sha256=7b529cb2b8a3c7e5be77921bf1ebc653d4d3a8f791375cc6f971b20db2404176 (from https://pypi.org/simple/cryptacular/). Command errored out with exit status 1: 'f:\apps\anaconda\python.exe' 'f:\apps\anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Haddy-PC\AppData\Local\Temp\tmpu0qgh85p' Check the logs for full command output.`

and when i write pip install apexpy

`C:\Users\Haddy-PC>pip install apexpy
WARNING: Ignoring invalid distribution -ip (f:\apps\anaconda\lib\site-packages)
WARNING: Ignoring invalid distribution - (f:\apps\anaconda\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (f:\apps\anaconda\lib\site-packages)
WARNING: Ignoring invalid distribution - (f:\apps\anaconda\lib\site-packages)
Collecting apexpy
  Using cached apexpy-1.1.0.tar.gz (5.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in f:\apps\anaconda\lib\site-packages (from apexpy) (1.18.1)
Building wheels for collected packages: apexpy
  Building wheel for apexpy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'f:\apps\anaconda\python.exe' 'f:\apps\anaconda\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\Haddy-PC\AppData\Local\Temp\tmpmk5a77il'
       cwd: C:\Users\Haddy-PC\AppData\Local\Temp\pip-install-ogahult3\apexpy_5a9d0824924f4e0abaf68d88a066533a
  Complete output (31 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "apexpy.fortranapex" sources
  f2py options: []
    adding 'build\src.win-amd64-3.8\build\src.win-amd64-3.8\src\fortranapex\fortranobject.c' to sources.
    adding 'build\src.win-amd64-3.8\build\src.win-amd64-3.8\src\fortranapex' to include_dirs.
    adding 'build\src.win-amd64-3.8\src\fortranapex\fortranapex-f2pywrappers.f' to sources.
    adding 'build\src.win-amd64-3.8\src\fortranapex\fortranapex-f2pywrappers2.f90' to sources.
  build_src: building npy-pkg config files
  running build_py
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\apexpy
  copying src\apexpy\apex.py -> build\lib.win-amd64-3.8\apexpy
  copying src\apexpy\helpers.py -> build\lib.win-amd64-3.8\apexpy
  copying src\apexpy\__init__.py -> build\lib.win-amd64-3.8\apexpy
  copying src\apexpy\__main__.py -> build\lib.win-amd64-3.8\apexpy
  copying src\apexpy\apexsh.dat -> build\lib.win-amd64-3.8\apexpy
  copying src\apexpy\igrf13coeffs.txt -> build\lib.win-amd64-3.8\apexpy
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  customize MSVCCompiler using build_ext
  CCompilerOpt.cc_test_flags[1013] : testing flags (/O2)
  CCompilerOpt.cache_flush[809] : write cache to path -> C:\Users\Haddy-PC\AppData\Local\Temp\pip-install-ogahult3\apexpy_5a9d0824924f4e0abaf68d88a066533a\build\temp.win-amd64-3.8\Release\ccompiler_opt_cache_ext.py
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for apexpy
Failed to build apexpy
ERROR: Could not build wheels for apexpy which use PEP 517 and cannot be installed directly`

**Comment by ptrblck** [comment]
Based on the output it seems you are trying to install [this package](https://pypi.org/project/apex/) using the same name, so you might want to contact the authors.
