### ISSUE TITLE
ModuleNotFoundError: No module named 'amp_C'

### ISSUE THREAD

**Issue by newyorkthink** [NVIDIA/apex#1208]
/usr/bin/python3.9 "/home/thinker/pythonProject/yolov3 train/yolov3-9.5.0/train.py"
Traceback (most recent call last):
  File "/home/thinker/pythonProject/yolov3 train/yolov3-9.5.0/train.py", line 44, in <module>
    from apex import amp
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/__init__.py", line 20, in <module>
    from . import transformer
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/transformer/__init__.py", line 3, in <module>
    from apex.transformer import pipeline_parallel
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/__init__.py", line 1, in <module>
    from apex.transformer.pipeline_parallel.schedules import get_forward_backward_func
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/schedules/__init__.py", line 4, in <module>
    from apex.transformer.pipeline_parallel.utils import get_num_microbatches
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/utils.py", line 26, in <module>
    import amp_C
ModuleNotFoundError: No module named 'amp_C'

apex cannot find it :(

**Comment by pradeep-vishnu** [comment]
Pinging for the same issue. @newyorkthink Is the line missing any import path?

**Comment by ptrblck** [comment]
This should be resolved via #1211. Feel free to reopen if that's not the case.
