### ISSUE TITLE
big bug :(

### ISSUE THREAD

**Issue by newyorkthink** [NVIDIA/apex#1209]
![image](https://user-images.githubusercontent.com/87791643/140928676-3312d378-8bcb-41a3-a551-2be0bed002a4.png)

I code:
try:
    from apex.parallel import DistributedDataParallel as DDP
    from apex.fp16_utils import *
    from apex import amp, optimizers
    from apex.multi_tensor_apply import multi_tensor_applier
except ImportError:
    raise ImportError("Please install apex from https://www.github.com/nvidia/apex to run this example.")

and many package cannot found
Traceback (most recent call last):
  File "/home/thinker/pythonProject/yolov3 train/nvdia apex.py", line 5, in <module>
    from apex.parallel import DistributedDataParallel as DDP
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/__init__.py", line 20, in <module>
    from . import transformer
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/transformer/__init__.py", line 3, in <module>
    from apex.transformer import pipeline_parallel
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/__init__.py", line 1, in <module>
    from apex.transformer.pipeline_parallel.schedules import get_forward_backward_func
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/schedules/__init__.py", line 4, in <module>
    from apex.transformer.pipeline_parallel.utils import get_num_microbatches
  File "/home/thinker/.local/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/utils.py", line 23, in <module>
    import amp_C
ModuleNotFoundError: No module named 'amp_C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thinker/pythonProject/yolov3 train/nvdia apex.py", line 10, in <module>
    raise ImportError("Please install apex from https://www.github.com/nvidia/apex to run this example.")
ImportError: Please install apex from https://www.github.com/nvidia/apex to run this example.

Process finished with exit code 1

**Comment by ptrblck** [comment]
Double post from https://github.com/NVIDIA/apex/issues/1208
