### ISSUE TITLE
cannot load FastLayerNorm from apex.contrib.layer_norm

### ISSUE THREAD

**Issue by dominicshanshan** [NVIDIA/apex#1256]
Environment: Pytorch 21.12 from NGC
build APEX from source pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

then in the script

from apex.contrib.layer_norm import FastLayerNorm

running report issue: 

Traceback (most recent call last):
  File "layernorm.py", line 14, in <module>
    from apex.contrib.layer_norm import FastLayerNorm
  File "/workspace/apex/apex/contrib/layer_norm/__init__.py", line 1, in <module>
    from .layer_norm import FastLayerNorm
  File "/workspace/apex/apex/contrib/layer_norm/layer_norm.py", line 5, in <module>
    import fast_layer_norm
ModuleNotFoundError: No module named 'fast_layer_norm'

**Comment by crcrpar** [comment]
You need to build apex with `--global-option="--fast_layer_norm"` if you want to use apex/contrib/layer_norm

`pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" --global-option="--fast_layer_norm" ./`

**Comment by dominicshanshan** [comment]
sorry, should read setup.py more carefully ..

**Comment by arjuntemura** [comment]
Hi 
I tried using the command with the --global-option="--fast_layer_norm"  flag but still facing the same issue. 

![Image](https://github.com/user-attachments/assets/97c7ce1e-ffef-48b2-89af-94bc5afd10fd)
