### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Tangolin** [NVIDIA/apex#1261]
I am getting the following error while attempting to use APEX for a project.
```
12/30/2021 06:50:47 - INFO - __main__ -     Total #steps = 175250
12/30/2021 06:50:47 - INFO - __main__ -     Validate every 1800 steps, in total 98 times
Traceback (most recent call last):
  File "src/tasks/run_video_retrieval.py", line 833, in <module>
    start_training(input_cfg)
  File "src/tasks/run_video_retrieval.py", line 385, in start_training
    optimizer.step()
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_process_optimizer.py", line 359, in new_step
    self._master_params_to_model_params()
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_process_optimizer.py", line 22, in _master_params_to_model_params
    1.0)
  File "/opt/conda/lib/python3.6/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 30, in __call__
    *args)
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

After looking around it seems like this is an error that pops up when the compatibility score is too low for the GPU, however I am currently using a Titan X which shouldn't have this problem.

Here are some information about my environment specs, any help would be greatly appreciated.

```
>> print('A', sys.version)
A 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0]

>> print('B', torch.__version__)
B 1.5.1+cu101

>> print('C', torch.cuda.is_available())
C True

>> print('D', torch.backends.cudnn.enabled)
D True

>> device = torch.device('cuda')
>> print('E', torch.cuda.get_device_properties(device))
E _CudaDeviceProperties(name='GeForce GTX TITAN X', major=5, minor=2, total_memory=12212MB, multi_processor_count=24)

>> input(torch.tensor([1.0, 2.0]).cuda())
tensor([1., 2.], device='cuda:0')

>> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

>> nvidia-smi
Sun Jan  2 03:12:05 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:05:00.0 Off |                  N/A |
| 26%   65C    P8    16W / 250W |    295MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:06:00.0 Off |                  N/A |
| 70%   86C    P2   123W / 250W |   6806MiB / 12212MiB |     79%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 00000000:09:00.0 Off |                  N/A |
| 22%   61C    P8    18W / 250W |      6MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 00000000:0A:00.0 Off |                  N/A |
| 22%   52C    P8    17W / 250W |      6MiB / 12212MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by Po0ria** [comment]
How did you fix this?

**Comment by Po0ria** [comment]
Just in case someone is wondering this is a duplication of #605
