### ISSUE TITLE
`fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.

### ISSUE THREAD

**Issue by adore1979** [NVIDIA/apex#1314]
help!

**Comment by yunxiaomr** [comment]
Did you work it out？

**Comment by yunxiaomr** [comment]
hello,Did you work it out?

**Comment by crcrpar** [comment]
This message is expected when either you install APEX without CUDA extensions or  your CUDA version is <11.
Also I think even you see this message, most features work.

**Comment by ShivanshuPurohit** [comment]
I have torch 1.8.1 and cuda 11.1 and I'm still getting this error even after installing the CUDA/C++ extensions

**Comment by GregorySenay** [comment]
Same here with torch LTS (torch-1.8.2+cu111) and CUDA 11.1 on a fresh installation and Nvidia Driver Version: 510.47.03
More precisely when importing `fused_weight_gradient_mlp_cuda` and without triggering the exception message:
```bash
>>> import torch
>>> import apex
`fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
>>> import fused_weight_gradient_mlp_cuda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /opt/spark/python/lib/python3.9/site-packages/fused_weight_gradient_mlp_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda4blas19_cublasGetErrorEnumE14cublasStatus_t
```

**Comment by wangzishuo2002** [comment]
same problem help!!

**Comment by wangzishuo2002** [comment]
torch 1.10.2+cu102, cuda11.4, modified the torch version to 114 by hand, same problem detected

**Comment by Nishant3815** [comment]
struggling with same issue..it would be great if someone can help

**Comment by crcrpar** [comment]
> Same here with torch LTS (torch-1.8.2+cu111) and CUDA 11.1 on a fresh installation and Nvidia Driver Version: 510.47.03 More precisely when importing `fused_weight_gradient_mlp_cuda` and without triggering the exception message:
> 
> ```shell
> >>> import torch
> >>> import apex
> `fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
> >>> import fused_weight_gradient_mlp_cuda
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: /opt/spark/python/lib/python3.9/site-packages/fused_weight_gradient_mlp_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda4blas19_cublasGetErrorEnumE14cublasStatus_t
> ```

For this, I think https://github.com/pytorch/pytorch/pull/67161 is needed.

**Comment by Furqan7007** [comment]
Any update on this error? I'm using torch1.10.2+cu113, on cuda 11.3. Still getting the same error.

**Comment by GregorySenay** [comment]
Problem solved for me. Thanks @crcrpar!

You need to use and compile apex with a recent nightly version of Pytorch.

In my case I installed: `1.12.0.dev20220304+cu113`
`pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html`

**Comment by GregorySenay** [comment]
> > Same here with torch LTS (torch-1.8.2+cu111) and CUDA 11.1 on a fresh installation and Nvidia Driver Version: 510.47.03 More precisely when importing `fused_weight_gradient_mlp_cuda` and without triggering the exception message:
> > ```shell
> > >>> import torch
> > >>> import apex
> > `fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
> > >>> import fused_weight_gradient_mlp_cuda
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> > ImportError: /opt/spark/python/lib/python3.9/site-packages/fused_weight_gradient_mlp_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda4blas19_cublasGetErrorEnumE14cublasStatus_t
> > ```
> 
> For this, I think [pytorch/pytorch#67161](https://github.com/pytorch/pytorch/pull/67161) is needed.

Problem solved for me. Thanks @crcrpar!

You need to use and compile apex with a recent nightly version of Pytorch.

In my case I installed: `1.12.0.dev20220304+cu113`
`pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html`

**Comment by Furqan7007** [comment]
> > > Same here with torch LTS (torch-1.8.2+cu111) and CUDA 11.1 on a fresh installation and Nvidia Driver Version: 510.47.03 More precisely when importing `fused_weight_gradient_mlp_cuda` and without triggering the exception message:
> > > ```shell
> > > >>> import torch
> > > >>> import apex
> > > `fused_weight_gradient_mlp_cuda` module not found. gradient accumulation fusion with weight gradient computation disabled.
> > > >>> import fused_weight_gradient_mlp_cuda
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: /opt/spark/python/lib/python3.9/site-packages/fused_weight_gradient_mlp_cuda.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at4cuda4blas19_cublasGetErrorEnumE14cublasStatus_t
> > > ```
> > 
> > 
> > For this, I think [pytorch/pytorch#67161](https://github.com/pytorch/pytorch/pull/67161) is needed.
> 
> Problem solved for me. Thanks @crcrpar!
> 
> You need to use and compile apex with a recent nightly version of Pytorch.
> 
> In my case I installed: `1.12.0.dev20220304+cu113` `pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html`

Thank you @GregorySenay ! That actually solves the problem!

**Comment by Zxl19990529** [comment]
Hi guys. I meet the same problem for me. But I found the following modification in ```setup.py``` works for me.
Original :
```py
def get_cuda_bare_metal_version(cuda_dir):
    raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
    output = raw_output.split()
    release_idx = output.index("release") + 1
    release = output[release_idx].split(".")
    bare_metal_major = release[0]
    bare_metal_minor = release[1][0]

    return raw_output, bare_metal_major, bare_metal_minor
```

MY modification:
```py
def get_cuda_bare_metal_version(cuda_dir):
    raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
    output = raw_output.split()
    release_idx = output.index("release") + 1
    release = output[release_idx].split(".")
    bare_metal_major = release[0]
    #bare_metal_minor = release[1][0]
    bare_metal_minor = '3' # Modify the minor version to match your cudatoolkit installed  by conda here.
    return raw_output, bare_metal_major, bare_metal_minor
```

My computer is 3060 12G, with cuda=11.4 install in ```/usr/local/cuda-11.4```
When installing pytorch1.10.2, the official conda command will install cudatoolkit=11.3.1. So when installing apex, there is a conflict in minor version check here. 

Attention, the major version between your local cuda and cudatoolkit installed by conda should be kept the same.

**Comment by Limingxing00** [comment]
I got the same problem with torch 1.7.1 and cuda 10.2. I just installed mmdetection before apex.

**Comment by crcrpar** [comment]
cuda 10.2 cannot compile `fused_weight_gradient_mlp_cuda`.
so I expect (a) apex to be `import`-able and (b) the message to be displayed.
Without any description of environment and steps to reproduce, there isn't much that I can do.

**Comment by mmbejani** [comment]
The problem has been solved by installing `pytorch 1.11.0` for me!

**Comment by yizhangliu** [comment]
> The problem has been solved by installing `pytorch 1.11.0` for me! (CUDA 11.3, GPU 2 x RTX Titan)

The detected CUDA version (11.0) mismatches the version that was used to compile
  PyTorch (11.3). Please make sure to use the same CUDA versions.

Where can I get CUDA 11.3?

**Comment by mmbejani** [comment]
https://developer.nvidia.com/cuda-11.3.0-download-archive

**Comment by yizhangliu** [comment]
> https://developer.nvidia.com/cuda-11.3.0-download-archive

Thanks.

**Comment by namho-96** [comment]
That actually solves the problem. Thank you @mmbejani !

**Comment by medlen** [comment]
we can ignore this problem if CUDA  < 11  or install CUDA >= 11.

If we ignore this problem , our code maybe run slightly slow. just as it said "gradient accumulation fusion with weight gradient computation disabled" 

or we can install CUDA >= 11. make sure "nvcc -V" and "torch.version.cuda" have same version.

In my case:

'''
(swin) :~ $ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105       
(swin) :~ $ python 
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.version.cuda
'10.1'
'''

"fused_weight_gradient_mlp_cuda" module is install in setup.py, and it will check CUDA version.

https://github.com/NVIDIA/apex/blob/47c269b63f7e50c9a3397bf1587b4b992ae3a13e/setup.py#L300

'''
 # Check, if CUDA11 is installed for compute capability 8.0       <-------------  here 
    _, bare_metal_major, bare_metal_minor = get_cuda_bare_metal_version(CUDA_HOME)
    if int(bare_metal_major) >= 11:
        cc_flag = []
        cc_flag.append("-gencode")
        cc_flag.append("arch=compute_80,code=sm_80")
        if int(bare_metal_minor) > 0:
            cc_flag.append("-gencode")
            cc_flag.append("arch=compute_86,code=sm_86")
        ext_modules.append(
            CUDAExtension(
                name="fused_weight_gradient_mlp_cuda",    # <------------- and  here
                include_dirs=[os.path.join(this_dir, "csrc")],
                sources=[
                    "csrc/megatron/fused_weight_gradient_dense.cpp",
                    "csrc/megatron/fused_weight_gradient_dense_cuda.cu",
                    "csrc/megatron/fused_weight_gradient_dense_16bit_prec_cuda.cu",
                ],
                extra_compile_args={
                    "cxx": ["-O3"] + version_dependent_macros,
                    "nvcc": append_nvcc_threads(
                        [
                            "-O3",
                            "-gencode",
                            "arch=compute_70,code=sm_70",
                            "-U__CUDA_NO_HALF_OPERATORS__",
                            "-U__CUDA_NO_HALF_CONVERSIONS__",
                            "--expt-relaxed-constexpr",
                            "--expt-extended-lambda",
                            "--use_fast_math",
                        ]
                        + version_dependent_macros
                        + cc_flag
                    ),
                },
            )
        )

'''

**Comment by RunpeiDong** [comment]
> we can ignore this warning if CUDA < 11 or install CUDA >= 11 just as above said.
> 
> If we ignore this problem , our code maybe run slightly slower. just as warning "gradient accumulation fusion with weight gradient computation disabled"
> 
> or we can install CUDA >= 11. make sure "nvcc -V" and "torch.version.cuda" have same version.
> 
> In my case (my CUDA is 10.1 , and I choose to ignore this warning):
> 
> ```
> 
> (swin) :~ $ nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2019 NVIDIA Corporation
> Built on Fri_Feb__8_19:08:17_PST_2019
> Cuda compilation tools, release 10.1, V10.1.105       
> (swin) :~ $ python 
> Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> torch.version.cuda
> '10.1'
> ```
> 
> "fused_weight_gradient_mlp_cuda" module is install in [setup.py](https://github.com/NVIDIA/apex/blob/47c269b63f7e50c9a3397bf1587b4b992ae3a13e/setup.py#L300), and it will check CUDA version.
> 
> ```
> # Check, if CUDA11 is installed for compute capability 8.0       <-------------  here 
>     _, bare_metal_major, bare_metal_minor = get_cuda_bare_metal_version(CUDA_HOME)
>     if int(bare_metal_major) >= 11:
>         cc_flag = []
>         cc_flag.append("-gencode")
>         cc_flag.append("arch=compute_80,code=sm_80")
>         if int(bare_metal_minor) > 0:
>             cc_flag.append("-gencode")
>             cc_flag.append("arch=compute_86,code=sm_86")
>         ext_modules.append(
>             CUDAExtension(
>                 name="fused_weight_gradient_mlp_cuda",    # <------------- and  here
>                 include_dirs=[os.path.join(this_dir, "csrc")],
>                 sources=[
>                     "csrc/megatron/fused_weight_gradient_dense.cpp",
>                     "csrc/megatron/fused_weight_gradient_dense_cuda.cu",
>                     "csrc/megatron/fused_weight_gradient_dense_16bit_prec_cuda.cu",
>                 ],
>                 extra_compile_args={
>                     "cxx": ["-O3"] + version_dependent_macros,
>                     "nvcc": append_nvcc_threads(
>                         [
>                             "-O3",
>                             "-gencode",
>                             "arch=compute_70,code=sm_70",
>                             "-U__CUDA_NO_HALF_OPERATORS__",
>                             "-U__CUDA_NO_HALF_CONVERSIONS__",
>                             "--expt-relaxed-constexpr",
>                             "--expt-extended-lambda",
>                             "--use_fast_math",
>                         ]
>                         + version_dependent_macros
>                         + cc_flag
>                     ),
>                 },
>             )
>         )
> ```

Hi, CUDA >= 11.0 may not be enough.
In my case, I have CUDA=11.1, torch=1.9.0, and python=3.8.8, the warning still occurs.

**Comment by Somoku** [comment]
I recloned the project and rebuild again then everything looked good. Maybe the module will be not found when you rebuild it after the build failed.
In my case, I attempted to install relevant requirements on my own container but met this error. But when I used NVIDIA NGC's PyTorch container, I met it again when I rebuild after failure. So I solved the problem by recloning and rebuilding.
(pytorch1.8.0 + CUDA11.1)

**Comment by lxy51** [comment]
> 嗨，大家好。我遇到了同样的问题。但我发现以下修改`setup.py`对我有用。 原来的 ：
> 
> ```python
> def get_cuda_bare_metal_version(cuda_dir):
>     raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
>     output = raw_output.split()
>     release_idx = output.index("release") + 1
>     release = output[release_idx].split(".")
>     bare_metal_major = release[0]
>     bare_metal_minor = release[1][0]
> 
>     return raw_output, bare_metal_major, bare_metal_minor
> ```
> 
> 我的修改：
> 
> ```python
> def get_cuda_bare_metal_version(cuda_dir):
>     raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
>     output = raw_output.split()
>     release_idx = output.index("release") + 1
>     release = output[release_idx].split(".")
>     bare_metal_major = release[0]
>     #bare_metal_minor = release[1][0]
>     bare_metal_minor = '3' # Modify the minor version to match your cudatoolkit installed  by conda here.
>     return raw_output, bare_metal_major, bare_metal_minor
> ```
> 
> 修改完后，安装apex `python setup.py install`，然后导入。这对我有用。
> 
> 我的电脑是3060 12G，安装了cuda=11.4，在`/usr/local/cuda-11.4` 安装pytorch1.10.2时，官方的conda命令会安装cudatoolkit=11.3.1。所以安装apex的时候，这里小版本检查有冲突。
> 
> 注意，你本地的cuda和conda安装的cudatoolkit的主版本要保持一致。

I have the same problem. I found that the download was not successful with "conda install pytorch torchvision torchaudio cudatoolkit=11.4 -c pytorch- lts-c nvidia". May I ask whether cudatoolkit=11.3 or cudatoolkit=11.4 was used at the end?
