### ISSUE TITLE
when build apex occur the errors:41 errors detected in the compilation of "/tmp/tmpxft_00206a36_00000000-6_multi_tensor_lamb_stage_2.cpp1.ii".

### ISSUE THREAD

**Issue by cpperrpr** [NVIDIA/apex#1331]
when i run the command "python setup.py install --cuda_ext -cpp_ext" to build the apex,  report some errors like below

_**41 errors detected in the compilation of "/tmp/tmpxft_00206a36_00000000-6_multi_tensor_lamb_stage_2.cpp1.ii".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/wqh/anaconda3/envs/sg_benchmark/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "/home/wqh/anaconda3/envs/sg_benchmark/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:**_

I found these errors when run the demo of maskrcnn_benckmark, which takes me some days to find the mistake,  Now it may be the errors from  apex,but i don't konw how to solve it ,I have tried so many methods, and remake the pytorch environment  again and again, I am very appreciate for you give me the useful method to solve these,thanks

Pytorch 1.7.1
nvcc 10.1.243
Cuda 10.1.243
torchversion 0.8.2
cudatoolkits 10.1.243
gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) 
Linux version 5.8.0-50-generic (buildd@lgw01-amd64-030) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021

**Comment by cpperrpr** [comment]
`            instantiation of "std::reference_wrapper<_Tp>::reference_wrapper(_Tp &) [with _Tp=const std::string]" 
/home/wqh/anaconda3/envs/sg_benchmark/lib/python3.7/site-packages/torch/include/ATen/core/ivalue_inl.h(1082): here

/usr/include/c++/8/bits/move.h(48): error: identifier "__builtin_addressof" is undefined
          detected during:
            instantiation of "_Tp *std::__addressof(_Tp &) [with _Tp=std::reference_wrapper<const std::string>]" 
(139): here
            instantiation of "_Tp *std::addressof(_Tp &) [with _Tp=std::reference_wrapper<const std::string>]" 
/home/wqh/anaconda3/envs/sg_benchmark/lib/python3.7/site-packages/torch/include/c10/util/Optional.h(271): here
            instantiation of "std::remove_const<T>::type *c10::optional<T>::dataptr() [with T=std::reference_wrapper<const std::string>]" 
/home/wqh/anaconda3/envs/sg_benchmark/lib/python3.7/site-packages/torch/include/c10/util/Optional.h(327): here
            instantiation of "c10::optional<T>::optional(c10::optional<T> &&) [with T=std::reference_wrapper<const std::string>]" 

/usr/include/c++/8/bits/move.h(48): error: identifier "__builtin_addressof" is undefined
          detected during:
            instantiation of "_Tp *std::__addressof(_Tp &) [with _Tp=std::vector<double, std::allocator<double>>]" 
(139): here
            instantiation of "_Tp *std::addressof(_Tp &) [with _Tp=std::vector<double, std::allocator<double>>]" 
/home/wqh/anaconda3/envs/sg_benchmark/lib/python3.7/site-packages/torch/include/c10/util/Optional.h(271): here
            instantiation of "std::remove_const<T>::type *c10::optional<T>::dataptr() [with T=std::vector<double, std::allocator<double>>]" 
/home/wqh/anaconda3/envs/sg_benchmark/lib/python3.7/site-packages/torch/include/c10/util/Optional.h(327): here
            instantiation of "c10::optional<T>::optional(c10::optional<T> &&) [with T=std::vector<double, std::allocator<double>>]" 
/home/wqh/anaconda3/envs/sg_benchmark/lib/python3.7/site-packages/torch/include/ATen/core/ivalue.h(58): here

41 errors detected in the compilation of "/tmp/tmpxft_002880d2_00000000-6_multi_tensor_lamb_stage_1.cpp1.ii".
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/wqh/anaconda3/envs/sg_benchmark/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
    env=env)`

**Comment by cpperrpr** [comment]
It took ten days to succeed，today it succeed when i use cuda 9.0,
