### ISSUE TITLE
HI! install error!!

### ISSUE THREAD

**Issue by scj0709** [NVIDIA/apex#1357]
I want to install apex, but I get the following error.

    /usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
    /usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
    /usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
    [8/10] /usr/local/cuda-10.1/bin/nvcc  -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/TH -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/scj/anaconda3/envs/u2pl/include/python3.9 -c -c /tmp/pip-req-build-zz3_80h_/csrc/multi_tensor_axpby_kernel.cu -o /tmp/pip-req-build-zz3_80h_/build/temp.linux-x86_64-3.9/csrc/multi_tensor_axpby_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -lineinfo -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
    FAILED: /tmp/pip-req-build-zz3_80h_/build/temp.linux-x86_64-3.9/csrc/multi_tensor_axpby_kernel.o
    /usr/local/cuda-10.1/bin/nvcc  -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/TH -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/scj/anaconda3/envs/u2pl/include/python3.9 -c -c /tmp/pip-req-build-zz3_80h_/csrc/multi_tensor_axpby_kernel.cu -o /tmp/pip-req-build-zz3_80h_/build/temp.linux-x86_64-3.9/csrc/multi_tensor_axpby_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -lineinfo -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
    /usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
    /usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
    /usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
    /usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
    /usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
    /usr/include/c++/7/bits/basic_string.h:6688:95:   required from here
    /usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
           __p->_M_set_sharable();
           ~~~~~~~~~^~
    /usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
    /usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
    /usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
    /usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
    /usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
    /usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
    /usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
    [9/10] /usr/local/cuda-10.1/bin/nvcc  -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/TH -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/scj/anaconda3/envs/u2pl/include/python3.9 -c -c /tmp/pip-req-build-zz3_80h_/csrc/multi_tensor_l2norm_kernel.cu -o /tmp/pip-req-build-zz3_80h_/build/temp.linux-x86_64-3.9/csrc/multi_tensor_l2norm_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -lineinfo -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
    FAILED: /tmp/pip-req-build-zz3_80h_/build/temp.linux-x86_64-3.9/csrc/multi_tensor_l2norm_kernel.o
    /usr/local/cuda-10.1/bin/nvcc  -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/TH -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/scj/anaconda3/envs/u2pl/include/python3.9 -c -c /tmp/pip-req-build-zz3_80h_/csrc/multi_tensor_l2norm_kernel.cu -o /tmp/pip-req-build-zz3_80h_/build/temp.linux-x86_64-3.9/csrc/multi_tensor_l2norm_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -lineinfo -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++14
    /usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
    /usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
    /usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
    /usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
    /usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
    /usr/include/c++/7/bits/basic_string.h:6688:95:   required from here
    /usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
           __p->_M_set_sharable();
           ~~~~~~~~~^~
    /usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
    /usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
    /usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
    /usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
    /usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
    /usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
    /usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
    [10/10] c++ -MMD -MF /tmp/pip-req-build-zz3_80h_/build/temp.linux-x86_64-3.9/csrc/amp_C_frontend.o.d -pthread -B /home/scj/anaconda3/envs/u2pl/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/scj/anaconda3/envs/u2pl/include -fPIC -O2 -isystem /home/scj/anaconda3/envs/u2pl/include -fPIC -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/TH -I/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/scj/anaconda3/envs/u2pl/include/python3.9 -c -c /tmp/pip-req-build-zz3_80h_/csrc/amp_C_frontend.cpp -o /tmp/pip-req-build-zz3_80h_/build/temp.linux-x86_64-3.9/csrc/amp_C_frontend.o -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    In file included from /home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/ATen/Parallel.h:140:0,
                     from /home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                     from /home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                     from /home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                     from /home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:13,
                     from /home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                     from /tmp/pip-req-build-zz3_80h_/csrc/amp_C_frontend.cpp:1:
    /home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/include/ATen/ParallelOpenMP.h:83:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     #pragma omp parallel for if ((end - begin) >= grain_size)

    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
        subprocess.run(
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/subprocess.py", line 524, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zz3_80h_/setup.py", line 285, in <module>
        setup(
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 664, in run
        self.run_command('build')
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
        build_ext.build_extensions(self)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/scj/anaconda3/envs/u2pl/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /home/scj/anaconda3/envs/u2pl/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zz3_80h_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zz3_80h_/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-rjf2sqbs/install-record.txt --single-version-externally-managed --compile --install-headers /home/scj/anaconda3/envs/u2pl/include/python3.9/apex Check the logs for full command output.

CUDA version is 10.1 and pytorch 3.8.1 !!
plz help me

**Comment by AlexG1105** [comment]
I thinking I'm getting the same issue. I've tried GCC 7,8, am on Ubuntu 20.04 (gcp vm), PyTorch 1.6, cuda 10.1, cudnn 7.6

**Comment by sol173angs** [comment]
This is affecting #rollingthunder NV

**Comment by sol173angs** [comment]
![Convection-snapshot](https://user-images.githubusercontent.com/108617547/177042796-026ea55d-624f-4903-a1a6-505b0aee7f2f.png)

**Comment by ptrblck** [comment]
Based on the (truncated) error log I guess your compiler might be too old. We recommend to use e.g. the Ubuntu 20.04 base container/installation with the shipped toolchain.
In case you are running into build issues, please use the pre-built [NGC containers](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch). Closing
