### ISSUE TITLE
FusedLayerNorm not working properly (apex O1)

### ISSUE THREAD

**Issue by mindest** [NVIDIA/apex#1379]
**Describe the Bug**
Modules/functions are overridden in [`apex.amp.amp.init()`](https://github.com/NVIDIA/apex/blob/c3018b132c3dc180e5fda64e8ef432a1a22c7734/apex/amp/amp.py#L68) but apex normalization functions like `fused_layer_norm_affine` are not included. In the following example, the `input` of `fused_layer_norm_affine` is of type `half` while `weight` and `bias` are both of type `float`.
https://github.com/NVIDIA/apex/blob/c3018b132c3dc180e5fda64e8ef432a1a22c7734/apex/normalization/fused_layer_norm.py#L168-L171
I tried manually overriding it or casting `weight` and `bias` to `input.dtype`, both will work. Is this a known issue or can it be improved later? Thanks!
Call stack:
```
Traceback (most recent call last):
  File "/home/linmin/layernorm_issue.py", line 18, in <module>
    y = model(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/linmin/layernorm_issue.py", line 12, in forward
    return self.norm(self.ln(x))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/apex/normalization/fused_layer_norm.py", line 292, in forward
    return fused_layer_norm_affine(input, self.weight, self.bias, self.normalized_shape, self.eps)
  File "/opt/conda/lib/python3.8/site-packages/apex/normalization/fused_layer_norm.py", line 171, in fused_layer_norm_affine
    return FusedLayerNormAffineFunction.apply(*args)
  File "/opt/conda/lib/python3.8/site-packages/apex/normalization/fused_layer_norm.py", line 43, in forward
    output, mean, invvar = fused_layer_norm_cuda.forward_affine(
RuntimeError: expected scalar type Half but found Float
```
**Minimal Steps/Code to Reproduce the Bug**
```python
import torch
from apex import amp
from apex.normalization.fused_layer_norm import FusedLayerNorm

class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.norm = FusedLayerNorm(16)
        self.ln = torch.nn.Linear(16, 16)
    def forward(self, x):
        return self.norm(self.ln(x))

model = Net().cuda()
model = amp.initialize(model, opt_level="O1")

x = torch.randn(16, 16, device='cuda')
y = model(x)
```

**Expected Behavior**
The simple model should work fine.

**Environment**
<details>
<summary>info collected via `python -m torch.utils.collect_env`</summary>

```
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1063-azure-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.82.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.11.0
[pip3] torchelastic==0.2.2
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] mypy                      0.950                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.2           py38h20f2e39_0  
[conda] numpy-base                1.21.2           py38h79a1101_0  
[conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtext                 0.12.0                     py38    pytorch
[conda] torchvision               0.12.0               py38_cu113    pytorch
```
</details>

**Comment by mindest** [comment]
#760 looks similar but I cannot reproduce it on my side.

**Comment by quanpn90** [comment]
This happens because O1 needs functions to be declared to be whitelisted, so that inputs are converted to half.

https://github.com/NVIDIA/apex/blob/master/apex/amp/README.md

The solution is to add @amp.half_function on top of the fused_layer_norm function. 
Anyways the fused layer norm is either updated or even slower than the official PyTorch function, as well as O1 is inferior than PyTorch amp so there should be any reason to use anymore.

**Comment by mindest** [comment]
Thanks @quanpn90 for the clarification. I have a few questions:
- "updated": how is the fused layer norm updated?
- "even slower than the official PyTorch function": is it compared against torch function `torch.nn.LayerNorm`?
