### ISSUE TITLE
RuntimeError: cublas runtime error : unknown error at /tmp/pip-req-build-l1dtn3mo/aten/src/THC/THCBlas.cu:390

### ISSUE THREAD

**Issue by Jhaprince** [NVIDIA/apex#1389]
Hi @ptrblck

I am getting the following error using torch.matmul, will you please help me out with this

hidden states torch.Size([32, 69, 768])
attention head size 64
all head size 768
num attention heads 12
tensor shapes :
query shape torch.Size([32, 12, 69, 64])
key shape torch.Size([32, 12, 69, 64])
Traceback (most recent call last):
  File "train_meme_itm.py", line 802, in <module>
    run_main_train(args)
  File "train_meme_itm.py", line 705, in run_main_train
    main(args)
  File "train_meme_itm.py", line 470, in main
    loss = model(batch, compute_loss=True)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_initialize.py", line 177, in new_fwd
    **applier(kwargs, input_caster))
  File "/src/model_villa/vqa.py", line 43, in forward
    output_all_encoded_layers=False)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/src/model_villa/model.py", line 385, in forward
    output_all_encoded_layers=output_all_encoded_layers)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/src/model_villa/model.py", line 295, in forward
    hidden_states = layer_module(hidden_states, attention_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/src/model_villa/layer.py", line 177, in forward
    attention_output = self.attention(hidden_states, attention_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/src/model_villa/layer.py", line 135, in forward
    self_output = self.self(input_tensor, attention_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/src/model_villa/layer.py", line 95, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: cublas runtime error : unknown error at /tmp/pip-req-build-l1dtn3mo/aten/src/THC/THCBlas.cu:390

**Comment by ptrblck** [comment]
This doesn't seem to be apex-related, so feel free to post this issue e.g. in the PyTorch discussion board including a minimal, executable code snippet.
Closing.

**Comment by Jhaprince** [comment]
I raised this issue here because , while running the code . I received the following warning. I am also running this code inside the docker container 


error message:
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.
WARNING: Detected NVIDIA A100-PCIE-40GB GPU, which is not yet supported in this version of the container
