### ISSUE TITLE
AttributeError: module 'torchvision.ops.misc' has no attribute 'Conv2d'

### ISSUE THREAD

**Issue by billysx** [NVIDIA/apex#1424]
The error reported is as follows when I wanted to implement NM sparsity with timm models.

[ASP] torchvision is imported, can work with the MaskRCNN/KeypointRCNN from torchvision.
Traceback (most recent call last):
  File "train.py", line 879, in <module>
    main()
  File "train.py", line 472, in main
    ASP.prune_trained_model(model, optimizer)
  File "/home/shixingy/anaconda3/envs/ysx/lib/python3.7/site-packages/apex/contrib/sparsity/asp.py", line 295, in prune_trained_model
    cls.init_model_for_pruning(model, mask_calculator="m4n2_1d", verbosity=2, whitelist=[torch.nn.Linear, torch.nn.Conv2d], allow_recompute_mask=False)
  File "/home/shixingy/anaconda3/envs/ysx/lib/python3.7/site-packages/apex/contrib/sparsity/asp.py", line 98, in init_model_for_pruning
    sparse_parameter_list = {torch.nn.Linear: ['weight'], torch.nn.Conv1d: ['weight'], torch.nn.Conv2d: ['weight'], torch.nn.Conv3d: ['weight'], torchvision.ops.misc.Conv2d: ['weight']}
AttributeError: module 'torchvision.ops.misc' has no attribute 'Conv2d'

I thought it was the problem of the model initially as I used DeiT-Tiny, then I tried ResNet50, ResNext101 also, fails for the same error.
Then I check the source code of asp (apex.contrib.sparsity), where 
`sparse_parameter_list = {torch.nn.Linear: ['weight'], torch.nn.Conv1d: ['weight'], torch.nn.Conv2d: ['weight'], torch.nn.Conv3d: ['weight'], torchvision.ops.misc.Conv2d: ['weight']}` does exists but when I checked the source code or torchvison.ops.misc.Conv2d, there is turly no Conv2d attribute

**Comment by ChongyuNVIDIA** [comment]
This is due to TorchVision latest version (0.13.0) remove APIs that were deprecated before 0.8. https://github.com/pytorch/vision/commit/0c2373d0bba3499e95776e7936e207d8a1676e65
You can first comment out the torchvision.ops.misc.Conv2d: ['weight'] to have a try.

**Comment by billysx** [comment]
Thank you! That solves my problem
