### ISSUE TITLE
Autocasting does not cast to the right dtypes for FastMultiheadAttention 

### ISSUE THREAD

**Issue by smfsamir** [NVIDIA/apex#1431]
**Describe the Bug**
I'm trying to train a model that incorporates the `SelfMultiheadAttn` module from apex. Because the module only supports half precison, I'm using the `amp` package to attempt to cast the inputs and model components to the right type. This approach, however, gives me a type-mismatch RuntimeError:

```
Traceback (most recent call last):
  File "autocast_trial.py", line 15, in <module>
    outputs = net(inputs, inputs, inputs, is_training=True)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fsamir/.local/lib/python3.8/site-packages/apex/contrib/multihead_attn/self_multihead_attn.py", line 239, in forward
    outputs = self.attn_func(
  File "/home/fsamir/.local/lib/python3.8/site-packages/apex/contrib/multihead_attn/self_multihead_attn_func.py", line 118, in forward
    matmul2_results = torch.bmm(dropout_results, values.transpose(0, 1), out=matmul2_results)
RuntimeError: Expected out tensor to have dtype c10::Half, but got float instead
```

**Minimal Steps/Code to Reproduce the Bug**
 
```
import torch
import torch.nn as nn

from torch.cuda.amp.autocast_mode import autocast
from apex.contrib.multihead_attn import SelfMultiheadAttn

heads = 16
hidden_dim = 1024
seq_length = 10
num_seqs = 2
inputs = torch.randn(seq_length, num_seqs, hidden_dim, device='cuda')
net = SelfMultiheadAttn(hidden_dim, heads, impl='default').cuda() # using impl='fast' gives a similar type mismatch error.

with torch.cuda.amp.autocast_mode.autocast():
    outputs = net(inputs, inputs, inputs, is_training=True)
```

**Expected Behavior**
I expect the snippet above to work as if I had manually called `.half()` on the model `net` and the `inputs`. This is the approach taken in the `perf_test_multihead_attn.py`, but it's unclear to me how that approach would extend to a model that contains many other components (e.g., a sequence-to-sequence Transformer model). 

**Environment**

```
Collecting environment information...
PyTorch version: 1.12.0a0+8a1a93a
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-55-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 450.119.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] numpydoc==1.4.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.12.0
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchtext==0.13.0a0
[pip3] torchvision==0.13.0a0
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.3           py38h99721a1_2    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.12.0a0+8a1a93a          pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchtext                 0.13.0a0                 pypi_0    pypi
[conda] torchvision               0.13.0a0                 pypi_0    pypi
```

**Comment by smfsamir** [comment]
I found a Transformer model [here](https://github.com/benywon/LALM/blob/master/models/Transformer.py) that uses the FMHA components. For [training](https://github.com/benywon/LALM/blob/master/train/train.py), it appears they use `apex.amp.initialize` to achieve mixed precision: `model, optim = amp.initialize(model, optim, opt_level="O2", verbosity=0)`. According to [this thread](https://discuss.pytorch.org/t/torch-cuda-amp-equivalent-of-apex-amp-initialize/132598) however, it appears that `torch.cuda.amp.autocast` is now the recommended method, so I'm hesitant to use `apex.amp.initialize`.

**Comment by smfsamir** [comment]
According to [these docs](https://pytorch.org/docs/stable/notes/amp_examples.html#amp-custom-examples), it may suffice to add the @custom_fwd(cast_inputs=torch.float16) and @custom_bwd decorators to the `forward` and `backward` definitions in `self_multihead_attn_func.py`.

**Comment by smfsamir** [comment]
I added the decorators mentioned in the previous comment; after doing so, the `amp` package works seamlessly
