### ISSUE TITLE
KeyError when using DDP

### ISSUE THREAD

**Issue by neonrights** [NVIDIA/apex#149]
Using ```DistributedDataParallel``` results a KeyError with the following trace

```bash
Traceback (most recent call last):
  File "training_script.py", line 328, in iteration
    loss.backward()
  File "/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/anaconda3/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/parallel/distributed.py", line 362, in allreduce_hook
    self.comm_ready_buckets(param)
  File "/anaconda3/lib/python3.7/site-packages/apex-0.1-py3.7-linux-x86_64.egg/apex/parallel/distributed.py", line 422, in comm_ready_buckets
    bucket_idx, bucket_loc = self.param_id_to_bucket[id(param)]
KeyError: 139779067778824
```

pytorch: 1.0.0
apex compiled without --cpp_ext

**Comment by mcarilli** [comment]
This is a strange error.  Apex DDP parses the params that require grad during each forward pass, so it should set up bucket slots for all of them.  What options are you supplying to the DDP constructor?

In the meantime, you can try running with delay_allreduce=True, and that may unblock you.

**Comment by Lausannen** [comment]
@mcarilli Hi, actually I find apex from https://github.com/pytorch/pytorch/issues/13273. It is really useful for my model to bacward normally with apex. However, I have met the same problem with @neonrights . My code is a little special. I have two stage training. The first one is fixing encoder, just train model.module.decoder. The second one is training both encoder and decoder. When I use apex, they can be nomorally trained seperately, but if I join them together, key error will happen. Since I make the stage 1 and stage 2 auto-switch, I guess maybe I should reset something in torch.distributed or apex parameters ? If you can give me some suggestions, I will be very appreciated!

**Comment by mcarilli** [comment]
Do you wrap both the top level module and the submodule in DDP separately?  If so, taht might result in some params having more than one allreduce hook registered...and i'm not sure what will happen.

Apex DDP should support partial freezing or unfreezing of your model between iterations.  I THINK if you wrap only the top level module in DDP, then manually freeze (unfreeze) the parts of the model that you don't want to train, by setting requires_grad=False (True) on the frozen (unfrozen) parts before beginning forward passes, then Apex DDP will detect that the set of non-frozen (requires_grad=True) params has changed, and recreate the bucket structure properly.

Another thing you can try is the delay_allreduce=True option, which waits until the end of backward and collects whatever gradients the model happened to create.

**Comment by Lausannen** [comment]
Thank you for your quick reply ! I will take a try and let you know the result. By the way, when I use apex to wrap my model,  how much extra time might it consume compared with origin torch.distributed? (since I could not test using torch.distributed)

**Comment by mcarilli** [comment]
torch.nn.parallel.DistributedDataParallel and apex.parallel.DistributedDataParallel should have comparable performance for most models.  I maintain the apex version to support our internal use cases, which sometimes require quick addition of custom functionality.

**Comment by Lausannen** [comment]
Thank you ! More info will let you know when I get them. If others meet similar problems , I will suggest them to use apex.

**Comment by mcarilli** [comment]
`torch.nn.parallel.DistributedDataParallel` is usually pretty good.  Like I said, for most models there's no real advantage in using apex.  I (and upstream) would also be interested to hear what challenges you were having with the torch version.

**Comment by neonrights** [comment]
Wow, did not expect so many responses already!

I have a similar model like @Lausannen in that some parameters are not used during a forward pass.  I am trying to jointly train a model on several language tasks by having a model for a specific task share some parameters with others.  This leads to some parameters being unused during a forward pass.

@mcarilli I have already tried setting ```delay_allreduce=True```, however this results in each process completing 2-3 training iterations before hanging in the terminal.  I will try freezing unused parameters, however my current training setup consists of randomly selecting data from a task for each batch, then accumulating several batches before an optimization step.  Thus each process would need to communicate which parameters have been used anyways in order to prevent a freezing a parameter that a different process might have used.

**Comment by mcarilli** [comment]
Ok, i'm afraid you've run into an issue that has been a thorn in the side of DistributedDataParallel for a long time.  Nccl allreduces require that all processes publish the same set of gradients to an allreduce, or else they will hang.
Apex DDP with delay_allreduce=True can handle if the processes create different sets of gradients each iteration, **as long as the set of gradients created is the same across processes**.

One workaround is to not to manually freeze the params, but instead, ensure that every param has a zeroed gradient before each backward pass.  In this case, DDP will see a gradient for all the parameters, even though some of them are zero, and allreduce everything symmetrically.  If the params that actually receive grads for each task are only a small fraction of the total number of params in your network, this might be inefficient, though.   Another thing to watch out for is that an optimizer step with zeroed gradients is not numerically quite the same as an optimizer step with None gradients:  With None gradients, the optimizer skips the step for that param completely, while if the gradients are zero, it still does the update math, which might actually change the param a bit if there is some lingering momentum (for example).

**Comment by neonrights** [comment]
I see, that is unfortunate.  Thanks for the help anyways, I will try your workaround.

**Comment by chenhuiji** [comment]
> Ok, i'm afraid you've run into an issue that has been a thorn in the side of DistributedDataParallel (both apex and torch) for a long time. Nccl allreduces require that all processes publish the same set of gradients to an allreduce, or else they will hang. I think this is also the root cause of the original error you saw with delay_allreduce=False, where some params apparently didn't have a overlapped-allreduce bucket slot ready for them. The bucket structure is synced based on rank 0, so if rank 1 ever receives a gradient that rank 0 never received, rank 1's bucket structure (which mirrors rank 0) will not have a bucket slot available for that gradient.
> 
> Apex DDP with delay_allreduce=True can handle if the processes create different sets of gradients each iteration, **as long as the set of gradients created is the same across processes**.
> 
> One workaround is to not to manually freeze the params, but instead, ensure that every param has a zeroed gradient before each backward pass. In this case, DDP will see a gradient for all the parameters, even though some of them are zero, and allreduce everything symmetrically. If the params that actually receive grads for each task are only a small fraction of the total number of params in your network, this might be inefficient, though. Another thing to watch out for is that an optimizer step with zeroed gradients is not numerically quite the same as an optimizer step with None gradients: With None gradients, the optimizer skips the step for that param completely, while if the gradients are zero, it still does the update math, which might actually change the param a bit if there is some lingering momentum (for example).

@mcarilli Hi，in my situation, I adoptted adaptive-softmax implemented in PyTorch, and this algorithm would create data dependant gradients. For example, with the same model loaded into two GPUs, process in GPU 0 has gradients: g_0=[10,5], g_1[10,100], process in GPU 1 has gradients: g_0=[10,5], g_1=None. I have tried to assign the g_1 in GPU 1 with zero gradient of the shape [10,100] to avoid this error. However, PyTorch does not support gradient size modification operation with the API register_backward_hook. So I don't know how to resovle this problem now? Would this zero gradient assignment method to None gradient tensors work if applied in the DDP wrapper?

**Comment by FDecaYed** [comment]
@mcarilli I've also been asked this.
From my rough understanding, modifying grad for those are None with in the callback here would work in delayed case? Of course assuming the parameter you actually register_hook on won't have None grad, otherwise NOTHING works(This might be a bug on its own. even in every worker produce None on same tensor case)
https://github.com/NVIDIA/apex/blob/master/apex/parallel/distributed.py#L404

also I know very little about `queue_callback`. It seems from test you can only do that in a hook? If there is a way @chenhuiji can insert grad modification in that queue manually, it will solve the problem.
