### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by bjutlss** [NVIDIA/apex#1507]
I am using cuda11.1 pytorch1.8.0 ubuntu20.04 to install apex using the following command:
git clone https://github.com/NVIDIA/apex
cd apex
Export TORCH_CUDA_ARCH_LIST = "6.0; 6.1; 6.2; 7.0; 7.5" # set the target architecture manually, suggested in issue https://github.com/NVIDIA/apex/issues/605#issuecomment-554453001
pip3 install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
cd ..
But I got the following error:
The torch. __version__ = 1.8.0 comes with
Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11. 1. TC455_06. 29190527 _0
The from/usr/local/cuda - 11.1 / bin

Traceback (most recent call last):
File "<string>", line 1, in <module></module></string>
File "/tmp/pip-req-build-u1q04ptr/setup.py", line 177, in <module></module>
check_cuda_torch_binary_vs_bare_metal(CUDA_HOME)
File "/tmp/pip-req-build-u1q04ptr/setup.py", line 40, in check_cuda_torch_binary_vs_bare_metal
+ "In some cases, a minor-version mismatch will not cause later errors:  "
RuntimeError:  Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch  Pytorch binaries were compiled with Cuda 11.1.
In some cases, a minor-version mismatch will not cause later errors:   https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own  risk).
Running setup.py install for apex ...  error

As shown above, I built pytorch with cuda11.1 and installed cuda11.1. Why did I throw this error?

**Comment by BaiMeiyingxue** [comment]
i have the same error
