### ISSUE TITLE
TypeError: LoadLibrary() argument 1 must be str, not None

### ISSUE THREAD

**Issue by Synicix** [NVIDIA/apex#151]
I received this error when import apex with the current version of the APEX lib. This was not an issue before in a previous version of apex just a few weeks ago. Did something change with the dependencies of apex on windows?

from apex import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\synic\AppData\Local\Programs\Python\Python37\lib\site-packages\apex-0.1-py3.7.egg\apex\__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\synic\AppData\Local\Programs\Python\Python37\lib\site-packages\apex-0.1-py3.7.egg\apex\optimizers\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\synic\AppData\Local\Programs\Python\Python37\lib\site-packages\apex-0.1-py3.7.egg\apex\optimizers\fp16_optimizer.py", line 5, in <module>
  File "C:\Users\synic\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\synic\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

**Comment by mcarilli** [comment]
The offending line is https://github.com/NVIDIA/apex/blob/master/apex/optimizers/fp16_optimizer.py#L5, which enables the weird call below (https://github.com/NVIDIA/apex/blob/master/apex/optimizers/fp16_optimizer.py#L9) that is intended to perform a norm on fp16 data and spit out an fp32 output.  At least, I think that's what it's doing (@ngimel can confirm).  This particular piece of code came from mlperf, to support FusedAdam.  I don't think `lib = ctypes.cdll.LoadLibrary(None)` is allowed on Windows.  If you don't need FusedAdam, this code is irrelevant, and you can work around it by not doing a `from apex import *`, but selectively importing only the components you need, or commenting out https://github.com/NVIDIA/apex/blob/master/apex/__init__.py#L12.

@gcp this may also be behind https://github.com/NVIDIA/apex/issues/97#issuecomment-460377585.

Pytorch 1.01 supports specifying an output datatype for norm, so post 1.01, we will no longer need this hack.  In the meantime I wrapped the LoadLibrary call in some logic that will hopefully suppress the error unless you actually attempt to use `fused_norm`.

**Comment by mcarilli** [comment]
https://github.com/NVIDIA/apex/commit/69907b807886846b6cf7320b5b1e104b2d18c1ae might unblock you, unless you actually need FusedAdam.

**Comment by mcarilli** [comment]
Can I close this?

**Comment by Synicix** [comment]
Yep, it has been resolved. Thank you!
