### ISSUE TITLE
Installation errors 

### ISSUE THREAD

**Issue by ti3x** [NVIDIA/apex#1545]
**Describe the Bug**
Getting following errors when installing apex on g5.xlarge with latest Nvidia drivers on Ubuntu 20.04.
```
Processing /home/ubuntu/nemo-examples/apex
  Running command python setup.py egg_info
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

  Warning: Torch did not find available GPUs on this system.
   If your intention is to cross-compile, this is not an error.
  By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
  Volta (compute capability 7.0), Turing (compute capability 7.5),
  and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
  If you wish to cross-compile for a single specific architecture,
  export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.
```
**Minimal Steps/Code to Reproduce the Bug**
This is running in a Nemo workspace from conda steps mentioned in Nemo repo, the only difference is that the conda workspace is with python3.9. 
```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

the Python instruction did work, `pip install -v --disable-pip-version-check --no-cache-dir ./` but it will keep warning about not finding apex.optimizers.FusedAdam if I continue with basic Nemo models

**Expected Behavior**
Able to install from source

**Environment**
OS version ubuntu 20.04
PyTorch version: '1.13.0'
Python version: python 3.8.0

```
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1022-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.7.6
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.10.2
[pip3] torchvision==0.14.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] cudatoolkit               11.7.0              hd8887f6_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.4           py39h3d75532_1    conda-forge
[conda] pytorch                   1.13.0              py3.9_cpu_0    pytorch
[conda] pytorch-lightning         1.7.6                    pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.13.0                 py39_cpu    pytorch
[conda] torchmetrics              0.10.2                   pypi_0    pypi
[conda] torchvision               0.14.0                 py39_cpu    pytorch
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1022-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.7.6
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.10.2
[pip3] torchvision==0.14.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] cudatoolkit               11.7.0              hd8887f6_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.4           py39h3d75532_1    conda-forge
[conda] pytorch                   1.13.0              py3.9_cpu_0    pytorch
[conda] pytorch-lightning         1.7.6                    pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.13.0                 py39_cpu    pytorch
[conda] torchmetrics              0.10.2                   pypi_0    pypi
[conda] torchvision               0.14.0                 py39_cpu    pytorchCollecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1022-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.7.6
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.10.2
[pip3] torchvision==0.14.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] cudatoolkit               11.7.0              hd8887f6_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.4           py39h3d75532_1    conda-forge
[conda] pytorch                   1.13.0              py3.9_cpu_0    pytorch
[conda] pytorch-lightning         1.7.6                    pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.13.0                 py39_cpu    pytorch
[conda] torchmetrics              0.10.2                   pypi_0    pypi
[conda] torchvision               0.14.0                 py39_cpu    pytorch
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1022-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.7.6
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.10.2
[pip3] torchvision==0.14.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] cudatoolkit               11.7.0              hd8887f6_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.4           py39h3d75532_1    conda-forge
[conda] pytorch                   1.13.0              py3.9_cpu_0    pytorch
[conda] pytorch-lightning         1.7.6                    pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.13.0                 py39_cpu    pytorch
[conda] torchmetrics              0.10.2                   pypi_0    pypi
[conda] torchvision               0.14.0                 py39_cpu    pytorchCollecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1022-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.7.6
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchmetrics==0.10.2
[pip3] torchvision==0.14.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] cudatoolkit               11.7.0              hd8887f6_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.4           py39h3d75532_1    conda-forge
[conda] pytorch                   1.13.0              py3.9_cpu_0    pytorch
[conda] pytorch-lightning         1.7.6                    pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.13.0                 py39_cpu    pytorch
[conda] torchmetrics              0.10.2                   pypi_0    pypi
[conda] torchvision               0.14.0                 py39_cpu    pytorch
```

**Comment by crcrpar** [comment]
Did you set the environment variable of `TORCH_CUDA_ARCH_LIST` which includes Ampere for example `TORCH_CUDA_ARCH_LIST="8.0+PTX"?

**Comment by ti3x** [comment]
The Nvidia info from nvidia-smi is Driver Version: 515.65.01    CUDA Version: 11.7
 I tried both `TORCH_CUDA_ARCH_LIST="8.0+PTX" and `TORCH_CUDA_ARCH_LIST="8.0", how do you knonw what to put in for TORCH_CUDA_ARCH_LIST?

 More error information:
 ```
 Using pip 22.3.1 from /opt/conda/envs/nemo/lib/python3.9/site-packages/pip (python 3.9)
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Processing /home/ubuntu/nemo-examples/apex
  Running command python setup.py egg_info
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

  Warning: Torch did not find available GPUs on this system.
   If your intention is to cross-compile, this is not an error.
  By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
  Volta (compute capability 7.0), Turing (compute capability 7.5),
  and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
  If you wish to cross-compile for a single specific architecture,
  export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.



  torch.__version__  = 1.13.0


  running egg_info
  creating /tmp/pip-pip-egg-info-_lk4spta/apex.egg-info
  writing /tmp/pip-pip-egg-info-_lk4spta/apex.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-_lk4spta/apex.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-pip-egg-info-_lk4spta/apex.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-_lk4spta/apex.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-_lk4spta/apex.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-_lk4spta/apex.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
WARNING: Error parsing requirements for pybind11: [Errno 2] No such file or directory: '/opt/conda/envs/nemo/lib/python3.9/site-packages/pybind11-2.10.1.dist-info/METADATA'
Installing collected packages: apex
  Attempting uninstall: apex
    Found existing installation: apex 0.1
    Uninstalling apex-0.1:
      Removing file or directory /opt/conda/envs/nemo/lib/python3.9/site-packages/apex-0.1.dist-info/
      Removing file or directory /opt/conda/envs/nemo/lib/python3.9/site-packages/apex/
      Successfully uninstalled apex-0.1
  DEPRECATION: apex is being installed using the legacy 'setup.py install' method, because the '--no-binary' option was enabled for it and this currently disables local wheel building for projects that don't have a 'pyproject.toml' file. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/11451
  Running command Running setup.py install for apex
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

  Warning: Torch did not find available GPUs on this system.
   If your intention is to cross-compile, this is not an error.
  By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
  Volta (compute capability 7.0), Turing (compute capability 7.5),
  and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
  If you wish to cross-compile for a single specific architecture,
  export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.



  torch.__version__  = 1.13.0


  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/ubuntu/nemo-examples/apex/setup.py", line 175, in <module>
      check_cuda_torch_binary_vs_bare_metal(CUDA_HOME)
    File "/home/ubuntu/nemo-examples/apex/setup.py", line 27, in check_cuda_torch_binary_vs_bare_metal
      torch_binary_major = torch.version.cuda.split(".")[0]
  AttributeError: 'NoneType' object has no attribute 'split'
  error: subprocess-exited-with-error

  × Running setup.py install for apex did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/conda/envs/nemo/bin/python3.9 -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/home/ubuntu/nemo-examples/apex/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' --cpp_ext --cuda_ext install --record /tmp/pip-record-16y6f40g/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/envs/nemo/include/python3.9/apex
  cwd: /home/ubuntu/nemo-examples/apex/
  Running setup.py install for apex ... error
  Rolling back uninstall of apex
  Moving to /opt/conda/envs/nemo/lib/python3.9/site-packages/apex-0.1.dist-info/
   from /opt/conda/envs/nemo/lib/python3.9/site-packages/~pex-0.1.dist-info
  Moving to /opt/conda/envs/nemo/lib/python3.9/site-packages/apex/
   from /opt/conda/envs/nemo/lib/python3.9/site-packages/~pex
error: legacy-install-failure
```

**Comment by crcrpar** [comment]
> Traceback (most recent call last):
>    File "<string>", line 2, in <module>
>    File "<pip-setuptools-caller>", line 34, in <module>
>    File "/home/ubuntu/nemo-examples/apex/setup.py", line 175, in <module>
>      check_cuda_torch_binary_vs_bare_metal(CUDA_HOME)
>    File "/home/ubuntu/nemo-examples/apex/setup.py", line 27, in check_cuda_torch_binary_vs_bare_metal
>      torch_binary_major = torch.version.cuda.split(".")[0]
>  AttributeError: 'NoneType' object has no attribute 'split'
>  error: subprocess-exited-with-error

This part could indicate the installed pytorch does not work in your environment. Usually `torch.version.cuda` e.g. 
```
print(torch.version.cuda)
11.7
```

Could you confirm if you can use cuda with pytorch (without apex or nemo)?

**Comment by ti3x** [comment]
I used a different workspace with 
```
print(torch.version.cuda)
11.6
```
and it works. Seems like some conda workspace setup issue.
But since nvidia-smi says coda is at CUDA Version: 11.7, shouldn't this be v.11.7 here?

After successfully installing apex, it still says "Could not import distributed_fused_adam optimizer from Apex", is that expected?

**Comment by crcrpar** [comment]
see https://github.com/nvidia/apex#custom-ccuda-extensions-and-install-options for install options.
I don't know what NeMo could use
