### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by jbs250** [NVIDIA/apex#1546]
/home/polo/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/polo/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
User install by explicit request
Created temporary directory: /tmp/pip-ephem-wheel-cache-ysb2pged
Created temporary directory: /tmp/pip-req-tracker-u35ua8yj
Initialized build tracking at /tmp/pip-req-tracker-u35ua8yj
Created build tracker: /tmp/pip-req-tracker-u35ua8yj
Entered build tracker: /tmp/pip-req-tracker-u35ua8yj
Created temporary directory: /tmp/pip-install-7z1s3vif
Processing /home/polo/apex
  Created temporary directory: /tmp/pip-req-build-m0i5rtgd
  Added file:///home/polo/apex to build tracker '/tmp/pip-req-tracker-u35ua8yj'
    Running setup.py (path:/tmp/pip-req-build-m0i5rtgd/setup.py) egg_info for package from file:///home/polo/apex
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-m0i5rtgd/setup.py", line 137, in <module>
        _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
      File "/tmp/pip-req-build-m0i5rtgd/setup.py", line 17, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
      File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.8/subprocess.py", line 493, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: ':/usr/local/cuda/bin/nvcc'

    torch.__version__  = 1.10.1+cu113

Cleaning up...
  Removing source in /tmp/pip-req-build-m0i5rtgd
Removed file:///home/polo/apex from build tracker '/tmp/pip-req-tracker-u35ua8yj'
Removed build tracker: '/tmp/pip-req-tracker-u35ua8yj'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 515, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python3/dist-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 564, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 538, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/build/metadata_legacy.py", line 115, in generate_metadata
    call_subprocess(
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ptrblck** [comment]
Based on the error message:
```
FileNotFoundError: [Errno 2] No such file or directory: ':/usr/local/cuda/bin/nvcc'
```
you don't have a working CUDA compiler installed.
Make sure to install a CUDA toolkit and verify that you are able to compile CUDA code with `nvcc`.

**Comment by ccl-1** [comment]
from this error message:
` FileNotFoundError: [Errno 2] No such file or directory: ':/usr/local/cuda/bin/nvcc'`
i guess ":" is the reason that lead to this error. So in setup.py,  i add `cuda_dir = cuda_dir.split(":")[-1]`
befor 
`    raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)`

it works for me.
