### ISSUE TITLE
why

### ISSUE THREAD

**Issue by noadore** [NVIDIA/apex#1549]
(SER-end) E:\test\Anaconda3\envs\SER-end\apex-master>python setup.py install

torch.__version__  = 1.13.0

Traceback (most recent call last):
  File "setup.py", line 137, in <module>
    _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
  File "setup.py", line 17, in get_cuda_bare_metal_version
    raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
  File "E:\test\Anaconda3\envs\SER-end\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\test\Anaconda3\envs\SER-end\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\test\Anaconda3\envs\SER-end\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\test\Anaconda3\envs\SER-end\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by ptrblck** [comment]
Based on the error message it seems your system has trouble finding the `nvcc` executable.
Make sure your `nvcc` binary can be found and you are able to compile CUDA code with it.
