### ISSUE TITLE
AttributeError: 'xxxxx' object has no attribute 'module'，asp.py line 218，error

### ISSUE THREAD

**Issue by Dagoli** [NVIDIA/apex#1590]
**Describe the Bug**
**When i use the ‘ASP.prune_trained_model(model, optimizer)’ API on my bert model,it's error like this:** 

**************************************************************************************************
Traceback (most recent call last):
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/apex/contrib/sparsity/asp.py", line 218, in compute_sparse_m
    offline_permutation_fx_graph, success_in_build_offline_permutation_graph = Permutation.build_offline_permutation_graph(clh, save_dumped_fx_graph=os.path.join(cls.__permutation_output_dir, 'model_offline_permutation_graph.json'))
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1208, in __getattr__
    type(self).__name__, name))
AttributeError: 'Model' object has no attribute 'module'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 37, in <module>
    train(config, model, train_iter, dev_iter, test_iter)
  File "/root/workspace/model_zoo/Bert-Chinese-Text-Classification-Pytorch/train_eval.py", line 44, in train
    ASP.prune_trained_model(model, optimizer)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/apex/contrib/sparsity/asp.py", line 297, in prune_trained_mo
    cls.compute_sparse_masks()
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/apex/contrib/sparsity/asp.py", line 221, in compute_sparse_m
    offline_permutation_fx_graph, success_in_build_offline_permutation_graph = Permutation.build_offline_permutation_graph(cl_dumped_fx_graph=os.path.join(cls.__permutation_output_dir, 'model_offline_permutation_graph.json'))
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/apex/contrib/sparsity/permutation_lib.py", line 241, in buil
    fx_graph, success_in_build_fx_graph = cls.build_fx_graph(model, dump_fx_graph=dump_fx_graph, save_dumped_fx_graph=save_du
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/apex/contrib/sparsity/permutation_lib.py", line 834, in buil
    graph_module = cls.print_raw_fx_graph(model, print_tabular=True)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/apex/contrib/sparsity/permutation_lib.py", line 894, in prin
    symbolic_traced : torch.fx.GraphModule = symbolic_trace(model)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 878, in symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 587, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/root/workspace/model_zoo/Bert-Chinese-Text-Classification-Pytorch/models/bert.py", line 44, in forward
    _, pooled = self.bert(context, attention_mask=mask, output_all_encoded_layers=False)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 577, in module_call_wrapp
    return self.call_module(mod, forward, args, kwargs)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 372, in call_module
    return forward(*args, **kwargs)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 573, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace/model_zoo/Bert-Chinese-Text-Classification-Pytorch/pytorch_pretrained/modeling.py", line 730, in
    embedding_output = self.embeddings(input_ids, token_type_ids)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 577, in module_call_wrapp
    return self.call_module(mod, forward, args, kwargs)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 372, in call_module
    return forward(*args, **kwargs)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 573, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/root/miniconda3/envs/py37_3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace/model_zoo/Bert-Chinese-Text-Classification-Pytorch/pytorch_pretrained/modeling.py", line 262, in
    position_ids = torch.arange(seq_length, dtype=torch.long, device=input_ids.device)
TypeError: arange() received an invalid combination of arguments - got (Proxy, device=Attribute, dtype=torch.dtype), but expe
 * (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_gr
 * (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool p
********************************************************************************************************
**I have also encountered this error when running other models**

**Comment by ptrblck** [comment]
CC @jpool-nv

**Comment by jpool-nv** [comment]
Hi @Dagoli , can you share any specific model that sees this issue so I can reproduce it?

**Comment by Dagoli** [comment]
@jpool-nv First of all thank you very much for your response. I'm adding ASP.prune_trained_model(model, optimizer) on line 44 of train_eval.py
The github repository: https://github.com/649453932/Bert-Chinese-Text-Classification-Pytorch.

**Comment by Dagoli** [comment]
@jpool-nv Or bert resp:/bert/transformers/examples/legacy/question-answerin/run_squad.py

**Comment by Dagoli** [comment]
@jpool-nv I have another question about that resnet50 is pruned most conv layers,but yolov5 pruned for only a few conv layers when using the ASP.prune_trained_model()?  How can yolov5 achieve resnet50 performance?Thanks a lot.

**Comment by jpool-nv** [comment]
Hi @Dagoli  - I've submitted PR 1595 that will address the error in your first report.

Regarding yolov5, there are certain constraints a convolution must satisfy in order to be accelerated by Sparse Tensor Cores, and so ASP will not prune layers that do not satisfy these constraints.  You can see them on lines 142/145 of asp.py, but the main point is that the layer must have input/output channel counts that are even multiples of 16/8.  You should see some prints in the ASP logs confirming which layers were pruned and which were skipped (for which reasons).

If you have questions about a particular version and variant of yolov5, please point me to it, share the logs from ASP (particularly the prints from lines 143, 146, and 150), and I can take a look.

**Comment by Dagoli** [comment]
> Hi @Dagoli - I've submitted PR 1595 that will address the error in your first report.
> 
> Regarding yolov5, there are certain constraints a convolution must satisfy in order to be accelerated by Sparse Tensor Cores, and so ASP will not prune layers that do not satisfy these constraints. You can see them on lines 142/145 of asp.py, but the main point is that the layer must have input/output channel counts that are even multiples of 16/8. You should see some prints in the ASP logs confirming which layers were pruned and which were skipped (for which reasons).
> 
> If you have questions about a particular version and variant of yolov5, please point me to it, share the logs from ASP (particularly the prints from lines 143, 146, and 150), and I can take a look.

Thank you for your detailed reply. In the future, I will continue to study yolo5, and I will do some simple experiments to verify the degree of sparsity's performance improvement.

**Comment by Dagoli** [comment]
Hi @jpool-nv -This is the log and onnx model when i pruned it: https://github.com/Dagoli/yolo5_sparsity_debug_log.git
The previous part of the model,like backbone.dark ,meets the multiple of 8/16 but there are still a lot of conv layer can not be pruned, I looked at the source code on lines of permutation_lib.py but did not understand
