### ISSUE TITLE
Issue Installing Apex in WSL Environment

### ISSUE THREAD

**Issue by l8g** [NVIDIA/apex#1676]
**🐛 Bug**

I'm having a problem installing Apex in a WSL environment. It seems the installation script for Apex is trying to find the CUDA installation directory and run the `nvcc -V` command. In a WSL environment, despite CUDA being supported through the NVIDIA WSL driver, there may not exist a proper CUDA installation directory, and `nvcc` may not be added to the `PATH` environment variable.

**To Reproduce**
I attempted to install Apex in WSL using the following commands:

```bash
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir ./
```
I then received the following error:

```
File "/home/ldd/nlp/apex/setup.py", line 130, in <module>
  _, bare_metal_version = get_cuda_bare_metal_version(CUDA_HOME)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ldd/nlp/apex/setup.py", line 17, in get_cuda_bare_metal_version
  raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
                                        ~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Expected behavior
I would expect Apex to be installable in a WSL environment without needing a full CUDA installation directory or nvcc.

Environment

OS: Ubuntu 20.04 on WSL 2
Python version: 3.11
PyTorch version: 2.0.1
CUDA version: NVIDIA CUDA 11.3 driver for Windows
GPU models: [e.g. NVIDIA RTX 2080]
Apex version: master branch as of 2023-06-06
GCC version: [e.g. 7.5]
Any other relevant information:
Additional context
I'm trying to run a deep learning project that depends on Apex. I'm unable to run this project as Apex cannot be installed in my WSL environment.

**Comment by l8g** [comment]
I appreciate your prompt response. I would like to clarify a few things about my setup:

1. I am working within a WSL2 (Windows Subsystem for Linux) environment, not a traditional Linux one.
2. In my Windows system, the CUDA installation directory does not contain all the files and directories that WSL2 would expect from a full CUDA install. In particular, `nvcc` is missing because WSL2, by design, does not have access to a full CUDA installation that is present in the Windows system.
3. I have tried setting the `CUDA_HOME` environment variable in WSL2, but it did not solve the issue, as the directory that this variable points to does not contain `nvcc`.

Given these constraints, I am currently unable to install Apex in my WSL2 environment. I was wondering if you have any recommendations for installing Apex under WSL2, or if there are plans to support WSL2 in the future?

Thank you for your time and consideration.

Best regards,

**Comment by crcrpar** [comment]
thank you for your clarification. I misunderstood some bits. could you try commenting out https://github.com/NVIDIA/apex/blob/05091d498d21058a0fe736b828c43431d4f0dda2/setup.py#L130
?
since your install command doesn't depend on any custom extensions, I don't think the cuda ver check is needed

**Comment by l8g** [comment]
Thank you very much for your guidance. I have successfully installed Apex and it seems to be functioning correctly. I ran a script that tests Apex's Automatic Mixed Precision (AMP) feature and everything worked as expected.

However, during the test, I received a warning that the multi_tensor_applier fused unscale kernel is unavailable, and Apex was using a Python fallback. The message suggested this might be because Apex was installed without --cuda_ext --cpp_ext.

This isn't causing me any problems at the moment, but I am wondering if it may impact performance, and if so, what I should do about it. My understanding is that compiling the CUDA extensions in WSL2 might be nontrivial due to the unique setup.

Any further advice you could provide on this topic would be greatly appreciated.

**Comment by ingura** [comment]
I am having the same. How did you solve it?

After commenting line 130 as mentioned above I run into RuntimeError: nvcc was not found: 

`$ pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--global-option=--cpp_ext" --config-settings "--global-option=--cuda_ext" ./
Using pip 23.2.1 from /home/ozgard/.local/lib/python3.10/site-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Processing /home/ozgard/Installs/apex-master
  Running command Preparing metadata (pyproject.toml)


  torch.__version__  = 2.0.1+cu117


  running dist_info
  creating /tmp/pip-modern-metadata-bohz_c9m/apex.egg-info
  writing /tmp/pip-modern-metadata-bohz_c9m/apex.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-bohz_c9m/apex.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-bohz_c9m/apex.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-bohz_c9m/apex.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-bohz_c9m/apex.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-bohz_c9m/apex.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-bohz_c9m/apex.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-bohz_c9m/apex.dist-info'
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: packaging>20.6 in /home/ozgard/.local/lib/python3.10/site-packages (from apex==0.1) (23.1)
Building wheels for collected packages: apex
  Running command Building wheel for apex (pyproject.toml)


  torch.__version__  = 2.0.1+cu117


  Traceback (most recent call last):
    File "/home/ozgard/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/ozgard/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ozgard/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 177, in <module>
      raise_if_cuda_home_none("--cuda_ext")
    File "setup.py", line 53, in raise_if_cuda_home_none
      raise RuntimeError(
  RuntimeError: --cuda_ext was requested, but nvcc was not found.  Are you sure your environment has nvcc available?  If you're installing within a container from https://hub.docker.com/r/pytorch/pytorch, only images whose names contain 'devel' will provide nvcc.
  error: subprocess-exited-with-error

  × Building wheel for apex (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /home/ozgard/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpy9mqud0_
  cwd: /home/ozgard/Installs/apex-master
  Building wheel for apex (pyproject.toml) ... error
  ERROR: Failed building wheel for apex
Failed to build apex
ERROR: Could not build wheels for apex, which is required to install pyproject.toml-based projects`

**Comment by ingura** [comment]
For others that run into this problem besides the version check comment I had to add "packaging" and "torch" to pyproject.toml
