### ISSUE TITLE
torch

### ISSUE THREAD

**Issue by yuhuai4554** [NVIDIA/apex#1729]
Traceback (most recent call last):
    File "/root/anaconda3/envs/distbert/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/root/anaconda3/envs/distbert/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/root/anaconda3/envs/distbert/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/root/anaconda3/envs/distbert/lib/python3.8/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/root/anaconda3/envs/distbert/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 136, in <module>
    File "<string>", line 23, in get_cuda_bare_metal_version
  TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
  error: subprocess-exited-with-error

**Comment by kwin1412** [comment]
how to fix it or which commit can avoid this bug

**Comment by AJohnsonV** [comment]
Don't know if you have already seen this issue:
https://github.com/NVIDIA/apex/issues/990
