### ISSUE TITLE
When doing pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./, shows ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by lainmn** [NVIDIA/apex#1737]
**Describe the Bug**

When doing pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./, shows ModuleNotFoundError: No module named 'packaging', but I have packaging installed

The detailed error looks like this: 
  Traceback (most recent call last):
    File "C:\Users\luo00318\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\luo00318\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\luo00318\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\luo00318\AppData\Local\Temp\pip-build-env-wchsm8v0\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\luo00318\AppData\Local\Temp\pip-build-env-wchsm8v0\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "C:\Users\luo00318\AppData\Local\Temp\pip-build-env-wchsm8v0\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 5, in <module>
  ModuleNotFoundError: No module named 'packaging'
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\luo00318\AppData\Local\anaconda3\envs\torch_gpu\python.exe' 'C:\Users\luo00318\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\luo00318\AppData\Local\Temp\tmptlqivujq'
  cwd: C:\Users\luo00318\Research\ICL\myplan\week4\apex
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Minimal Steps/Code to Reproduce the Bug**
 

**Expected Behavior**

should have been installed correctly?

**Environment**

**Comment by orrzohar** [comment]
I got the same error.

**Comment by sym330** [comment]
I got the same error.

**Comment by lengendhao** [comment]
Hey! I also got this error, and I've solved it. You can see #1653, which said:
1. clone or download [apex 22.04-dev branch](https://github.com/NVIDIA/apex/tree/22.04-dev) instead of [master brach](https://github.com/nvidia/apex)
2. use the command：pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./ to install 'apex'.
You may get another error: **No such file or directory: ':/usr/local/cuda-11.0/bin/nvcc'**
You can `vi ~/.bashrc`
then change 'export CUDA_HOME=$CUDA_HOME:/usr/local/cuda' into 'export CUDA_HOME=/usr/local/cuda'
Finally, `source ~/.bashrc`
Use the command again, and you will use apex succesfully!

**Comment by rocke2020** [comment]
> Hey! I also got this error, and I've solved it. You can see #1653, which said:
> 
> 1. clone or download [apex 22.04-dev branch](https://github.com/NVIDIA/apex/tree/22.04-dev) instead of [master brach](https://github.com/nvidia/apex)
> 2. use the command：`pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./` to install 'apex'.
>    You may get another error: **No such file or directory: ':/usr/local/cuda-11.0/bin/nvcc'**
>    You can `vi ~/.bashrc`
>    then change 'export CUDA_HOME=$CUDA_HOME:/usr/local/cuda' into 'export CUDA_HOME=/usr/local/cuda'
>    Finally, `source ~/.bashrc`
>    Use the command again, and you will use apex succesfully!

could you share your package details? thanks in advance!
1, torch version
2, python version
3, cuda version
My envs: torch 2.1, py 3.10, cuda 11.8, I has the same apex install error. the 22.04-dev branch also failed to install.

**Comment by lengendhao** [comment]
> > Hey! I also got this error, and I've solved it. You can see #1653, which said:
> > 
> > 1. clone or download [apex 22.04-dev branch](https://github.com/NVIDIA/apex/tree/22.04-dev) instead of [master brach](https://github.com/nvidia/apex)
> > 2. use the command：`pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./` to install 'apex'.
> >    You may get another error: **No such file or directory: ':/usr/local/cuda-11.0/bin/nvcc'**
> >    You can `vi ~/.bashrc`
> >    then change 'export CUDA_HOME=$CUDA_HOME:/usr/local/cuda' into 'export CUDA_HOME=/usr/local/cuda'
> >    Finally, `source ~/.bashrc`
> >    Use the command again, and you will use apex succesfully!
> 
> could you share your package details? thanks in advance! 1, torch version 2, python version 3, cuda version My envs: torch 2.1, py 3.10, cuda 11.8, I has the same apex install error. the 22.04-dev branch also failed to install.

My envs:
PyTorch  1.8.1
Python  3.8(ubuntu18.04)
Cuda  11.1
Maybe this issue can help you: [https://github.com/NVIDIA/apex/issues/1735](https://github.com/NVIDIA/apex/issues/1735)

**Comment by MuTsuMiJohn** [comment]
python  3.7.3
pytorch 1.5.1
cuda     12.0
`conda install packaging
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./`
apex 22.04-dev branch doesn't work for me... but i've found that [#1748](https://github.com/NVIDIA/apex/issues/1748#issuecomment-1928910265) solved my problem. Good luck!

**Comment by LukeLIN-web** [comment]
I also met this problem.
