### ISSUE TITLE
Whether to support Cuda 12.1

### ISSUE THREAD

**Issue by yangzhipeng1108** [NVIDIA/apex#1748]
torch.__version__  = 2.1.0+cu121

Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Sep__8_19:17:24_PDT_2023
Cuda compilation tools, release 12.3, V12.3.52
Build cuda_12.3.r12.3/compiler.33281558_0
from /usr/local/cuda/bin

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "setup.py", line 178, in <module>
    check_cuda_torch_binary_vs_bare_metal(CUDA_HOME)
  File "setup.py", line 40, in check_cuda_torch_binary_vs_bare_metal
    raise RuntimeError(
RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 12.1.
In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).

**Comment by tiandiao123** [comment]
do you have some ways to fix this? I have a similar problem over here.

**Comment by CTW20191008** [comment]
```
conda install packaging
pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
These work for me. Good luck.

**Comment by MuTsuMiJohn** [comment]
Thanks very much! This works for me.

**Comment by Edenzzzz** [comment]
> ```
> conda install packaging
> pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./
> ```
> 
> These work for me. Good luck.

Worked

**Comment by jiayoujiayoujiayoua** [comment]
> ```
> conda install packaging
> pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./
> ```
> 
> These work for me. Good luck.

Thanks, this works for me, too

**Comment by kkk935208447** [comment]
Thanks, this works for me

**Comment by v1o6ynne** [comment]
> ```
> conda install packaging
> pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./
> ```
> 
> These work for me. Good luck.

Works for me, Thx. Why packaging can solve this?

**Comment by sirlddf** [comment]
Thanks, it works for me as well.

**Comment by AlongWY** [comment]
try this one 试试这个？[apex wheels](https://github.com/AlongWY/apex_wheels/releases/tag/v24.4.1)

**Comment by LRuiRui517** [comment]
> ```
> conda install packaging
> pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --global-option="--cpp_ext" --global-option="--cuda_ext" ./
> ```
> 
> These work for me. Good luck.

it dosen't work for me. my error:Using pip 24.2 from /home/adminl/anaconda3/envs/bevdet/lib/python3.8/site-packages/pip (python 3.8)
DEPRECATION: --build-option and --global-option are deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option.
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Processing /home/adminl/lrp2/CompletionFormer-main/src/model/deformconv
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-9el8elzp/DCN.egg-info
  writing /tmp/pip-pip-egg-info-9el8elzp/DCN.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-9el8elzp/DCN.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-pip-egg-info-9el8elzp/DCN.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-9el8elzp/DCN.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-9el8elzp/DCN.egg-info/SOURCES.txt'
  writing manifest file '/tmp/pip-pip-egg-info-9el8elzp/DCN.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: DCN
  Running command python setup.py bdist_wheel
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: option --cpp_ext not recognized
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/adminl/anaconda3/envs/bevdet/bin/python -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/home/adminl/lrp2/CompletionFormer-main/src/model/deformconv/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' --cpp_ext --cuda_ext bdist_wheel -d /tmp/pip-wheel-ww2_h5yr
  cwd: /home/adminl/lrp2/CompletionFormer-main/src/model/deformconv/
  Building wheel for DCN (setup.py) ... error
  ERROR: Failed building wheel for DCN
  Running setup.py clean for DCN
  Running command python setup.py clean
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: option --cpp_ext not recognized
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/adminl/anaconda3/envs/bevdet/bin/python -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/home/adminl/lrp2/CompletionFormer-main/src/model/deformconv/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' --cpp_ext --cuda_ext clean --all
  cwd: /home/adminl/lrp2/CompletionFormer-main/src/model/deformconv
  ERROR: Failed cleaning build dir for DCN
Failed to build DCN
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (DCN)
