### ISSUE TITLE
Apex installation fails

### ISSUE THREAD

**Issue by yang606** [NVIDIA/apex#1762]
**Describe the Bug**
Apex installation fails.
(rei) ecust@ecust:~ EVA/EVA-CLIP/apex$ pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation--config-settings"--build-option=--cpp ext"--config-settings" --build-option=--cuda_ext" ./
Using pip 23.3.2 from /home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/site-packages/pip (python 3.8)rocessing /home/ecust/EVA/EVA-CLIP/apexRunning command Preparing metadata (pyproject.toml)
torch.__version_= 2.1.2+Cu118
Traceback (most recent call last):File "home/ecust/1TSS/anaconda3/envs/rei/lib/python3.8/site-packages/pip/.vendor/pyproject hooks/ in process/ in processpy", line 353, in module3main)File "/home/ecust/1TSD/anaconda3/envs/rei/ib/python38/site-packages/pip/.vendor/pyprojet hooks/-in process in process,py", line 335, in mainrule t['etur1-ya)amhoka/hook tnputl hwargs" /site-packaes/pip/ vendor/oworotect hooks/ in process/ in process v’, ine 14, n renare metadata for burid whereturn hook(metadata_directory, config_settings.File "/homeecust/1TSD/anaconda3envs/re/lib/python3.8/site-packages/setuptols/build meta.py", ine 39, in prepare metadata for build wheelself.run setup(File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/site-packages/setuptools/build meta.py", line 341, in run_setup
exec(code， locals())File "<string>", line 137, in <module>lineFile "<string:24, in get cuda bare metal versiorFile "/home/ecust/1TSsD/anaconda3/envs/rei/lib/python3.8/subprocess.py", line 415, in check outputfeturn run(*popenargs, stdout=PIPE,timeout=timeout, check=True .File "/home/ecust/1TSSD/anaconda3/ernvs/rei/lib/python3.8/subprocess.py", line 493, in runwith Popen(*popenargs，**kwargs) as DrocessFile "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/subprocess.py", ine 858, in __initself. execute child(args, executable, preexec fn, close fds.File "/home/ecust/1TSsD/anaconda3/envs/rei/lib/python3.8/subprocess.py", line 1720, in _execute_childraise child_exception_type(errno_num,err_msg, err_filename)FileNotFoundError: [Errno 2] No such file or directory:'/usr/local/cuda:/usr/local/cudaexport/bin/nvcc 
error: subprocess-exited-with-error
x Preparing metadata (pyproject.toml) did not run successfully.
exit code: 1> See above for output.note: This error originates from a subprocess. and is likely not a problem with pipFull comad: /hone/ecust/TSD/anaconda3/enws/rei/bin/python3.a hone/ecust/S/anacand3/enws/rei/libpython./site-padkaes pip/.vendor pyproect toks n proxessj-im proces.y metadata for build wheel /tmp/tmpi7imsvgpreparecwd: /home/ecust/EVA/EVA-CLIP/apexerPcepartngdnetadata (pyprofect.tonl) ... error
xEncountered error while generating package metadata_> See above for output .
note: This is an issue with the package mentioned above, not pip.
hint: see above for details.
**Minimal Steps/Code to Reproduce the Bug**
 

**Expected Behavior**

**Environment**

OS: Ubuntu 20.04.6 LTS (x86_64)
PyTorch version: 2.1.2
GPU:RTX3090
torch   2.1.2+cu118
torchaudio  2.1.2+cu118
torchvision  0.16.2+cu118
pip  23.3.2

**Comment by yaoyuan10475** [comment]
(rei) ecust@ecust:~/EVA/EVA-CLIP/apex$ pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./
Using pip 23.3.2 from /home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/site-packages/pip (python 3.8)
Processing /home/ecust/EVA/EVA-CLIP/apex
  Running command Preparing metadata (pyproject.toml)


  torch.__version__  = 2.1.2+cu118


  Traceback (most recent call last):
    File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 137, in <module>
    File "<string>", line 24, in get_cuda_bare_metal_version
    File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/subprocess.py", line 415, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/subprocess.py", line 493, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/subprocess.py", line 1720, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda:/usr/local/cudaexport/bin/nvcc'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/ecust/1TSSD/anaconda3/envs/rei/bin/python3.8 /home/ecust/1TSSD/anaconda3/envs/rei/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpkasgw45l
  cwd: /home/ecust/EVA/EVA-CLIP/apex
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
