### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by lxy51** [NVIDIA/apex#1815]
(umamba2) root@a84983fdd20f:/apex# pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
Using pip 24.0 from /root/data1/lxy/envs/umamba2/lib/python3.10/site-packages/pip (python 3.10)
DEPRECATION: --build-option and --global-option are deprecated. pip 24.2 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option. 
Processing /apex
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Using cached setuptools-70.1.1-py3-none-any.whl
  Collecting wheel
    Using cached wheel-0.43.0-py3-none-any.whl
  Installing collected packages: wheel, setuptools
  Successfully installed setuptools-70.1.1 wheel-0.43.0
  WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "/root/data1/lxy/envs/umamba2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/root/data1/lxy/envs/umamba2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/root/data1/lxy/envs/umamba2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-das4_3h3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
    File "/tmp/pip-build-env-das4_3h3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-das4_3h3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 5, in <module>
  ModuleNotFoundError: No module named 'packaging'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /root/data1/lxy/envs/umamba2/bin/python /root/data1/lxy/envs/umamba2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpuf0bfcpx
  cwd: /apex
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mzhang2FW** [comment]
I have the same issue. Thanks for posting and could you let me know if you got a solution yet?

**Comment by vishweshhampali** [comment]
Same issue here. Could anyone provide a solution.

**Comment by aitrics-chris** [comment]
guy... install packaging

**Comment by AlongWY** [comment]
try this one 试试这个？[apex wheels](https://github.com/AlongWY/apex_wheels/releases/tag/v24.4.1)
