### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='/home/shengjieyi/cuda1108' .

### ISSUE THREAD

**Issue by vvsherryvv** [NVIDIA/apex#1828]
I run `export  CUDA_HOME=~/cuda1108` in terminal , and write `export PATH="/home/shengjieyi/cuda1108/bin:$PATH"
      export LD_LIBRARY_PATH="/home/shengjieyi/cuda1108/lib64:/home/shengjieyi/cuda1108/mylib/lib64:$LD_LIBRARY_PATH"`
in bashrc,
i run `which nvcc`and get `~/cuda1108/bin/nvcc`

i try to solve this problem 5days..., what can i do?

`(gauhuman) [shengjieyi@dx-ai-node1 GauHuman-main]$ pip install submodules/diff-gaussian-rasterization
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/, https://pypi.tuna.tsinghua.edu.cn/simple/, https://pypi.mirrors.ustc.edu.cn/simple/, https://pypi.douban.com/simple/
Processing ./submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff_gaussian_rasterization
  Building wheel for diff_gaussian_rasterization (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/home/shengjieyi/cuda1108'
      running bdist_wheel
      /home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      running build_ext
      /home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gaussian_rasterization._C' extension
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/cuda_rasterizer
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/shengjieyi/GauHuman-main/submodules/diff-gaussian-rasterization/setup.py", line 17, in <module>
          setup(
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 581, in unix_wrap_single_compile
          cflags = unix_cuda_flags(cflags)
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 548, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/shengjieyi/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1773, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  Running setup.py clean for diff_gaussian_rasterization
Failed to build diff_gaussian_rasterization
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (diff_gaussian_rasterization)`

**Comment by AlongWY** [comment]
try this one 试试这个？[apex wheels](https://github.com/AlongWY/apex_wheels/releases/tag/v24.4.1)
