### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by Cverlpeng** [NVIDIA/apex#236]

**Comment by Cverlpeng** [comment]
use pip install apex, get this error! thanks

**Comment by okanlv** [comment]
Did you just use `pip install apex` without downloading this repo? Could you write the steps to replicate the problem?

**Comment by Cverlpeng** [comment]
> 您是否只是在`pip install apex`没有下载此回购的情况下使用？你能写出复制问题的步骤吗？

fellow readme
git clone apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"
i get this error  in 3 step

**Comment by zsp1993** [comment]
according to readme
git clone apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"
i ａｌｓｏ　get this error in 3 step


csrc/welford.cu(131): error: identifier "__shfl_down_sync" is undefined
              detected during:
                instantiation of "void welford_reduce_mean_m2n(T *, int *, T &, T &, int &, int, int) [with T=at::acc_type<double, true>]"
    (287): here
                instantiation of "void welford_kernel<scalar_t,accscalar_t,outscalar_t>(const scalar_t *, outscalar_t *, outscalar_t *, int, int, int) [with scalar_t=double, accscalar_t=at::acc_type<double, true>, outscalar_t=at::acc_type<double, true>]"
    (849): here

    csrc/welford.cu(134): error: no instance of function template "welford_merge_element" matches the argument list
                argument types are: (int, at::acc_type<double, true>, at::acc_type<double, true>, <error-type>, <error-type>, <error-type>)
              detected during:
                instantiation of "void warp_reduce_mean_m2n(T &, T &, int &) [with T=at::acc_type<double, true>]"
    (152): here
                instantiation of "void welford_reduce_mean_m2n(T *, int *, T &, T &, int &, int, int) [with T=at::acc_type<double, true>]"
    (287): here
                instantiation of "void welford_kernel<scalar_t,accscalar_t,outscalar_t>(const scalar_t *, outscalar_t *, outscalar_t *, int, int, int) [with scalar_t=double, accscalar_t=at::acc_type<double, true>, outscalar_t=at::acc_type<double, true>]"
    (849): here

    csrc/welford.cu(134): error: no instance of function template "welford_merge_element" matches the argument list
                argument types are: (int, at::acc_type<float, true>, at::acc_type<float, true>, <error-type>, <error-type>, <error-type>)
              detected during:
                instantiation of "void warp_reduce_mean_m2n(T &, T &, int &) [with T=at::acc_type<float, true>]"
    (152): here
                instantiation of "void welford_reduce_mean_m2n(T *, int *, T &, T &, int &, int, int) [with T=at::acc_type<float, true>]"
    (287): here
                instantiation of "void welford_kernel<scalar_t,accscalar_t,outscalar_t>(const scalar_t *, outscalar_t *, outscalar_t *, int, int, int) [with scalar_t=float, accscalar_t=at::acc_type<float, true>, outscalar_t=at::acc_type<float, true>]"
    (849): here

    csrc/welford.cu(49): error: identifier "__shfl_down_sync" is undefined
              detected during:
                instantiation of "T warp_reduce_sum(T) [with T=at::acc_type<double, true>]"
    (60): here
                instantiation of "T reduce_block(T *, T) [with T=at::acc_type<double, true>]"
    (368): here
                instantiation of "void reduce_bn_kernel(const scalar_t *, const scalar_t *, const accscalar_t *, const accscalar_t *, accscalar_t *, accscalar_t *, layerscalar_t *, layerscalar_t *, int, int, int) [with scalar_t=double, accscalar_t=at::acc_type<double, true>, layerscalar_t=at::acc_type<double, true>]"
    (959): here

    csrc/welford.cu(49): error: identifier "__shfl_down_sync" is undefined
              detected during:
                instantiation of "T warp_reduce_sum(T) [with T=at::acc_type<float, true>]"
    (60): here
                instantiation of "T reduce_block(T *, T) [with T=at::acc_type<float, true>]"
    (368): here
                instantiation of "void reduce_bn_kernel(const scalar_t *, const scalar_t *, const accscalar_t *, const accscalar_t *, accscalar_t *, accscalar_t *, layerscalar_t *, layerscalar_t *, int, int, int) [with scalar_t=float, accscalar_t=at::acc_type<float, true>, layerscalar_t=at::acc_type<float, true>]"
    (959): here

    5 errors detected in the compilation of "/tmp/tmpxft_00003e29_00000000-7_welford.cpp1.ii".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
error
Cleaning up...
  Removing source in /tmp/pip-req-build-37982b4m
Command "/home/peng/anaconda2/envs/python35/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-37982b4m/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-fx89u4zb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-37982b4m/
Exception information:
Traceback (most recent call last):
  File "/home/peng/anaconda2/envs/python35/lib/python3.5/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/peng/anaconda2/envs/python35/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/home/peng/anaconda2/envs/python35/lib/python3.5/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/peng/anaconda2/envs/python35/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/home/peng/anaconda2/envs/python35/lib/python3.5/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/peng/anaconda2/envs/python35/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-37982b4m/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-fx89u4zb/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-37982b4m/

**Comment by avostryakov** [comment]
Can I ask another question: is it possible to install compiled version of apex with pip directly from github? I know that I can run: pip install git+https://github.com/NVIDIA/apex but I'm not sure that it isn't pure python version or with all cpp and cuda compiled code?
