### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by frankang** [NVIDIA/apex#249]
It gives error when I tried to build from this code for the latest commit:
`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
`
The error details:
```
    gcc -pthread -B /home/sakura/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-10.0/include -I/home/sakura/miniconda3/include/python3.7m -c csrc/layer_norm_cuda.cpp -o build/temp.linux-x86_64-3.7/csrc/layer_norm_cuda.o -O3 -DVERSION_GE_1_1 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=fused_layer_norm_cuda -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    csrc/layer_norm_cuda.cpp:9:9: error: ‘at::IntArrayRef’ has not been declared
         at::IntArrayRef normalized_shape,
             ^
    csrc/layer_norm_cuda.cpp: In function ‘void {anonymous}::compute_n1_n2(at::Tensor, int, int&, int&)’:
    csrc/layer_norm_cuda.cpp:16:55: error: request for member ‘size’ in ‘normalized_shape’, which is of non-class type ‘int’
         int idiff = input.ndimension() - normalized_shape.size();
                                                           ^
    csrc/layer_norm_cuda.cpp:18:48: error: request for member ‘size’ in ‘normalized_shape’, which is of non-class type ‘int’
         for (int i = 0;  i < (int)normalized_shape.size();  ++i) {
                                                    ^
    csrc/layer_norm_cuda.cpp:20:30: error: invalid types ‘int[int]’ for array subscript
          n2 *= normalized_shape[i];
                                  ^
    csrc/layer_norm_cuda.cpp: At global scope:
    csrc/layer_norm_cuda.cpp:30:9: error: variable or field ‘check_args’ declared void
         at::IntArrayRef normalized_shape,
             ^
    csrc/layer_norm_cuda.cpp:30:5: error: ‘IntArrayRef’ is not a member of ‘at’
         at::IntArrayRef normalized_shape,
         ^
    csrc/layer_norm_cuda.cpp:34:16: error: expected primary-expression before ‘gamma’
         at::Tensor gamma,
                    ^
    csrc/layer_norm_cuda.cpp:35:16: error: expected primary-expression before ‘beta’
         at::Tensor beta
                    ^
    csrc/layer_norm_cuda.cpp:239:1: error: expected ‘}’ at end of input
     }
     ^
    csrc/layer_norm_cuda.cpp:6:6: warning: ‘void {anonymous}::compute_n1_n2(at::Tensor, int, int&, int&)’ defined but not used [-Wunused-function]
     void compute_n1_n2(
          ^
    error: command 'gcc' failed with exit status 1
error
```
Looks like it's related to the modified variable name so I reverted back to this commit and it was compiled successfully.
https://github.com/NVIDIA/apex/commit/42180bd929639c137706be99c93626da93a36f2e#diff-f8e0b9bb4b0f8d041d1e8807d265d799

**Comment by mcarilli** [comment]
The relevant change is actually https://github.com/NVIDIA/apex/pull/169, I think.  For versions of Pytorch earlier than https://github.com/pytorch/pytorch/commit/4404762d7dd955383acee92e6f06b48144a0742e#diff-4939bfc2c45f18348424b70304e777a7, IntList is appropriate, and for versions of Pytorch later than https://github.com/pytorch/pytorch/commit/4404762d7dd955383acee92e6f06b48144a0742e#diff-4939bfc2c45f18348424b70304e777a7, IntArrayRef is appropriate.  The current Apex setup.py tries to figure out (based on the Pytorch version string) which one should be used, and then [sets up macros](https://github.com/NVIDIA/apex/blob/master/setup.py#L67-L68) so that the C++ compilation [uses either IntList or IntArrayRef](https://github.com/NVIDIA/apex/blob/master/csrc/layer_norm_cuda_kernel.cu#L678-L682).  This logic should work for _almost_ every Pytorch master commit since 1.0, unless the Apex setup.py is not able to figure out the version string properly and therefore sets up macros to use the wrong thing.

What version of Pytorch are you using?  Also, can you post the full build output?  It contains some additional information (torch version, cuda version) that may be useful.

**Comment by frankang** [comment]
Thanks for the info, and below is the log&info,
pytorch version from conda (installed from binary)
> pytorch                   1.0.0           py3.7_cuda10.0.130_cudnn7.4.1_1 

log:
```
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
/home/sakura/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py:207: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Created temporary directory: /tmp/pip-ephem-wheel-cache-g8ihma9c
Created temporary directory: /tmp/pip-req-tracker-6uvwgoto
Created requirements tracker '/tmp/pip-req-tracker-6uvwgoto'
Created temporary directory: /tmp/pip-install-snti7ggn
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /data/sakura/apex
  Created temporary directory: /tmp/pip-req-build-khp1jjck
  Added file:///data/sakura/apex to build tracker '/tmp/pip-req-tracker-6uvwgoto'
    Running setup.py (path:/tmp/pip-req-build-khp1jjck/setup.py) egg_info for package from file:///data/sakura/apex
    Running command python setup.py egg_info
    torch.__version__  =  1.1.0a0+1063795
    running egg_info
    creating pip-egg-info/apex.egg-info
    writing pip-egg-info/apex.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/apex.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/apex.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-khp1jjck has version 0.1, which satisfies requirement apex==0.1 from file:///data/sakura/apex
  Removed apex==0.1 from file:///data/sakura/apex from build tracker '/tmp/pip-req-tracker-6uvwgoto'
Installing collected packages: apex
  Found existing installation: apex 0.1
    Uninstalling apex-0.1:
      Created temporary directory: /home/sakura/miniconda3/lib/python3.7/site-packages/~pex-0.1-py3.7.egg-info
      Removing file or directory /home/sakura/miniconda3/lib/python3.7/site-packages/apex-0.1-py3.7.egg-info
      Created temporary directory: /home/sakura/miniconda3/lib/python3.7/site-packages/~pex
      Removing file or directory /home/sakura/miniconda3/lib/python3.7/site-packages/apex/
      Successfully uninstalled apex-0.1
  Created temporary directory: /tmp/pip-record-qruwyvvs
  Running setup.py install for apex ...     Running command /home/sakura/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-khp1jjck/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-qruwyvvs/install-record.txt --single-version-externally-managed --compile
    torch.__version__  =  1.1.0a0+1063795

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2018 NVIDIA Corporation
    Built on Sat_Aug_25_21:08:01_CDT_2018
    Cuda compilation tools, release 10.0, V10.0.130
    from /usr/local/cuda-10.0/bin

    Pytorch binaries were compiled with Cuda 10.0.130

    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/apex
    copying apex/__init__.py -> build/lib.linux-x86_64-3.7/apex
    creating build/lib.linux-x86_64-3.7/apex/fp16_utils
    copying apex/fp16_utils/fp16util.py -> build/lib.linux-x86_64-3.7/apex/fp16_utils
    copying apex/fp16_utils/fp16_optimizer.py -> build/lib.linux-x86_64-3.7/apex/fp16_utils
    copying apex/fp16_utils/loss_scaler.py -> build/lib.linux-x86_64-3.7/apex/fp16_utils
    copying apex/fp16_utils/__init__.py -> build/lib.linux-x86_64-3.7/apex/fp16_utils
    creating build/lib.linux-x86_64-3.7/apex/normalization
    copying apex/normalization/fused_layer_norm.py -> build/lib.linux-x86_64-3.7/apex/normalization
    copying apex/normalization/__init__.py -> build/lib.linux-x86_64-3.7/apex/normalization
    creating build/lib.linux-x86_64-3.7/apex/optimizers
    copying apex/optimizers/fp16_optimizer.py -> build/lib.linux-x86_64-3.7/apex/optimizers
    copying apex/optimizers/fused_adam.py -> build/lib.linux-x86_64-3.7/apex/optimizers
    copying apex/optimizers/__init__.py -> build/lib.linux-x86_64-3.7/apex/optimizers
    creating build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/handle.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/scaler.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/wrap.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/_process_optimizer.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/opt.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/utils.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/frontend.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/_amp_state.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/rnn_compat.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/compat.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/amp.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/__init__.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/__version__.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/_initialize.py -> build/lib.linux-x86_64-3.7/apex/amp
    creating build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/sync_batchnorm.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/sync_batchnorm_kernel.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/LARC.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/optimized_sync_batchnorm.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/optimized_sync_batchnorm_kernel.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/multiproc.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/__init__.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/distributed.py -> build/lib.linux-x86_64-3.7/apex/parallel
    creating build/lib.linux-x86_64-3.7/apex/RNN
    copying apex/RNN/RNNBackend.py -> build/lib.linux-x86_64-3.7/apex/RNN
    copying apex/RNN/models.py -> build/lib.linux-x86_64-3.7/apex/RNN
    copying apex/RNN/cells.py -> build/lib.linux-x86_64-3.7/apex/RNN
    copying apex/RNN/__init__.py -> build/lib.linux-x86_64-3.7/apex/RNN
    creating build/lib.linux-x86_64-3.7/apex/reparameterization
    copying apex/reparameterization/weight_norm.py -> build/lib.linux-x86_64-3.7/apex/reparameterization
    copying apex/reparameterization/__init__.py -> build/lib.linux-x86_64-3.7/apex/reparameterization
    copying apex/reparameterization/reparameterization.py -> build/lib.linux-x86_64-3.7/apex/reparameterization
    creating build/lib.linux-x86_64-3.7/apex/multi_tensor_apply
    copying apex/multi_tensor_apply/multi_tensor_apply.py -> build/lib.linux-x86_64-3.7/apex/multi_tensor_apply
    copying apex/multi_tensor_apply/__init__.py -> build/lib.linux-x86_64-3.7/apex/multi_tensor_apply
    creating build/lib.linux-x86_64-3.7/apex/amp/lists
    copying apex/amp/lists/tensor_overrides.py -> build/lib.linux-x86_64-3.7/apex/amp/lists
    copying apex/amp/lists/torch_overrides.py -> build/lib.linux-x86_64-3.7/apex/amp/lists
    copying apex/amp/lists/functional_overrides.py -> build/lib.linux-x86_64-3.7/apex/amp/lists
    copying apex/amp/lists/__init__.py -> build/lib.linux-x86_64-3.7/apex/amp/lists
    running build_ext
    building 'apex_C' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/csrc
    gcc -pthread -B /home/sakura/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/home/sakura/miniconda3/include/python3.7m -c csrc/flatten_unflatten.cpp -o build/temp.linux-x86_64-3.7/csrc/flatten_unflatten.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=apex_C -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    g++ -pthread -shared -B /home/sakura/miniconda3/compiler_compat -L/home/sakura/miniconda3/lib -Wl,-rpath=/home/sakura/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/csrc/flatten_unflatten.o -o build/lib.linux-x86_64-3.7/apex_C.cpython-37m-x86_64-linux-gnu.so
    building 'amp_C' extension
    gcc -pthread -B /home/sakura/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-10.0/include -I/home/sakura/miniconda3/include/python3.7m -c csrc/amp_C_frontend.cpp -o build/temp.linux-x86_64-3.7/csrc/amp_C_frontend.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=amp_C -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /usr/local/cuda-10.0/bin/nvcc -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-10.0/include -I/home/sakura/miniconda3/include/python3.7m -c csrc/multi_tensor_scale_kernel.cu -o build/temp.linux-x86_64-3.7/csrc/multi_tensor_scale_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -lineinfo -O3 --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=amp_C -std=c++11
    /usr/local/cuda-10.0/bin/nvcc -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-10.0/include -I/home/sakura/miniconda3/include/python3.7m -c csrc/multi_tensor_axpby_kernel.cu -o build/temp.linux-x86_64-3.7/csrc/multi_tensor_axpby_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -lineinfo -O3 --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=amp_C -std=c++11
    g++ -pthread -shared -B /home/sakura/miniconda3/compiler_compat -L/home/sakura/miniconda3/lib -Wl,-rpath=/home/sakura/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/csrc/amp_C_frontend.o build/temp.linux-x86_64-3.7/csrc/multi_tensor_scale_kernel.o build/temp.linux-x86_64-3.7/csrc/multi_tensor_axpby_kernel.o -L/usr/local/cuda-10.0/lib64 -lcudart -o build/lib.linux-x86_64-3.7/amp_C.cpython-37m-x86_64-linux-gnu.so
    building 'fused_adam_cuda' extension
    gcc -pthread -B /home/sakura/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-10.0/include -I/home/sakura/miniconda3/include/python3.7m -c csrc/fused_adam_cuda.cpp -o build/temp.linux-x86_64-3.7/csrc/fused_adam_cuda.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=fused_adam_cuda -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /usr/local/cuda-10.0/bin/nvcc -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-10.0/include -I/home/sakura/miniconda3/include/python3.7m -c csrc/fused_adam_cuda_kernel.cu -o build/temp.linux-x86_64-3.7/csrc/fused_adam_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -O3 --use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=fused_adam_cuda -std=c++11
    g++ -pthread -shared -B /home/sakura/miniconda3/compiler_compat -L/home/sakura/miniconda3/lib -Wl,-rpath=/home/sakura/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/csrc/fused_adam_cuda.o build/temp.linux-x86_64-3.7/csrc/fused_adam_cuda_kernel.o -L/usr/local/cuda-10.0/lib64 -lcudart -o build/lib.linux-x86_64-3.7/fused_adam_cuda.cpython-37m-x86_64-linux-gnu.so
    building 'syncbn' extension
    gcc -pthread -B /home/sakura/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-10.0/include -I/home/sakura/miniconda3/include/python3.7m -c csrc/syncbn.cpp -o build/temp.linux-x86_64-3.7/csrc/syncbn.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=syncbn -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /usr/local/cuda-10.0/bin/nvcc -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-10.0/include -I/home/sakura/miniconda3/include/python3.7m -c csrc/welford.cu -o build/temp.linux-x86_64-3.7/csrc/welford.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=syncbn -std=c++11
    g++ -pthread -shared -B /home/sakura/miniconda3/compiler_compat -L/home/sakura/miniconda3/lib -Wl,-rpath=/home/sakura/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/csrc/syncbn.o build/temp.linux-x86_64-3.7/csrc/welford.o -L/usr/local/cuda-10.0/lib64 -lcudart -o build/lib.linux-x86_64-3.7/syncbn.cpython-37m-x86_64-linux-gnu.so
    building 'fused_layer_norm_cuda' extension
    gcc -pthread -B /home/sakura/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/TH -I/home/sakura/miniconda3/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda-10.0/include -I/home/sakura/miniconda3/include/python3.7m -c csrc/layer_norm_cuda.cpp -o build/temp.linux-x86_64-3.7/csrc/layer_norm_cuda.o -O3 -DVERSION_GE_1_1 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=fused_layer_norm_cuda -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    csrc/layer_norm_cuda.cpp:9:9: error: ‘at::IntArrayRef’ has not been declared
         at::IntArrayRef normalized_shape,
             ^
    csrc/layer_norm_cuda.cpp: In function ‘void {anonymous}::compute_n1_n2(at::Tensor, int, int&, int&)’:
    csrc/layer_norm_cuda.cpp:16:55: error: request for member ‘size’ in ‘normalized_shape’, which is of non-class type ‘int’
         int idiff = input.ndimension() - normalized_shape.size();
                                                           ^
    csrc/layer_norm_cuda.cpp:18:48: error: request for member ‘size’ in ‘normalized_shape’, which is of non-class type ‘int’
         for (int i = 0;  i < (int)normalized_shape.size();  ++i) {
                                                    ^
    csrc/layer_norm_cuda.cpp:20:30: error: invalid types ‘int[int]’ for array subscript
          n2 *= normalized_shape[i];
                                  ^
    csrc/layer_norm_cuda.cpp: At global scope:
    csrc/layer_norm_cuda.cpp:30:9: error: variable or field ‘check_args’ declared void
         at::IntArrayRef normalized_shape,
             ^
    csrc/layer_norm_cuda.cpp:30:5: error: ‘IntArrayRef’ is not a member of ‘at’
         at::IntArrayRef normalized_shape,
         ^
    csrc/layer_norm_cuda.cpp:34:16: error: expected primary-expression before ‘gamma’
         at::Tensor gamma,
                    ^
    csrc/layer_norm_cuda.cpp:35:16: error: expected primary-expression before ‘beta’
         at::Tensor beta
                    ^
    csrc/layer_norm_cuda.cpp:239:1: error: expected ‘}’ at end of input
     }
     ^
    csrc/layer_norm_cuda.cpp:6:6: warning: ‘void {anonymous}::compute_n1_n2(at::Tensor, int, int&, int&)’ defined but not used [-Wunused-function]
     void compute_n1_n2(
          ^
    error: command 'gcc' failed with exit status 1
error
  Rolling back uninstall of apex
  Moving to /home/sakura/miniconda3/lib/python3.7/site-packages/apex-0.1-py3.7.egg-info
   from /home/sakura/miniconda3/lib/python3.7/site-packages/~pex-0.1-py3.7.egg-info
  Moving to /home/sakura/miniconda3/lib/python3.7/site-packages/apex/
   from /home/sakura/miniconda3/lib/python3.7/site-packages/~pex
  Replacing /home/sakura/miniconda3/lib/python3.7/site-packages/apex-0.1-py3.7.egg-info from /home/sakura/miniconda3/lib/python3.7/site-packages/~pex-0.1-py3.7.egg-info
  Replacing /home/sakura/miniconda3/lib/python3.7/site-packages/apex/ from /home/sakura/miniconda3/lib/python3.7/site-packages/~pex
Cleaning up...
  Removing source in /tmp/pip-req-build-khp1jjck
Removed build tracker '/tmp/pip-req-tracker-6uvwgoto'
Command "/home/sakura/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-khp1jjck/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-qruwyvvs/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-khp1jjck/
Exception information:
Traceback (most recent call last):
  File "/home/sakura/miniconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/sakura/miniconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/home/sakura/miniconda3/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/home/sakura/miniconda3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 945, in install
    spinner=spinner,
  File "/home/sakura/miniconda3/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/sakura/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-khp1jjck/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-qruwyvvs/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-khp1jjck/
```

**Comment by mcarilli** [comment]
The IntArrayRef syntax is new-ish and is replacing old IntList syntax.  As I said, our compatibility hack should work for almost every version of Pytorch since 1.0.  Maybe you got unlucky with a version of Pytorch that doesn't fit.  I recommend trying two things:
1.  Use the latest Apex with a newer version of Pytorch (the more recent the better)
2.  If 1. is inconvenient, use the latest Apex, but comment out https://github.com/NVIDIA/apex/blob/master/setup.py#L67-L68 in setup.py before running `pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .`

**Comment by frankang** [comment]
thanks! I will close this issue temporarily. Will let you know if your suggested method works in the future.
