### ISSUE TITLE
UserWarning: Error checking compiler version for c++

### ISSUE THREAD

**Issue by yaodonggggggg** [NVIDIA/apex#253]
i use 
git clone https://github.com/NVIDIA/apex.git; cd apex; python setup.py install --cuda_ext --cpp_ext
to install apex,but when i run a python code,error appears

E:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for c++: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
��Ϣ: ���ṩ��ģʽ�޷��ҵ��ļ���
Traceback (most recent call last):
  File "E:\PyCharm Community Edition 2018.2.5\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "E:\PyCharm Community Edition 2018.2.5\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "E:\PyCharm Community Edition 2018.2.5\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\PyCharm Community Edition 2018.2.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/python_workspace/code/TorchSeg/model/dfn/voc.dfn.R101_v1c/learn.py", line 21, in <module>
    from seg_opr.sync_bn import DataParallelModel, Reduce, BatchNorm2d
  File "E:\python_workspace\code\TorchSeg\furnace\seg_opr\sync_bn\__init__.py", line 8, in <module>
    from .syncbn import *
  File "E:\python_workspace\code\TorchSeg\furnace\seg_opr\sync_bn\syncbn.py", line 17, in <module>
    from .functions import *
  File "E:\python_workspace\code\TorchSeg\furnace\seg_opr\sync_bn\functions.py", line 13, in <module>
    from .src import *
  File "E:\python_workspace\code\TorchSeg\furnace\seg_opr\sync_bn\src\__init__.py", line 12, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "E:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 645, in load
    is_python_module)
  File "E:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "E:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 859, in _write_ninja_file_and_build
    with_cuda=with_cuda)
  File "E:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1064, in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "E:\anaconda3\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "E:\anaconda3\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

when i want to unintall apex to reinstall it
C:\Users\Faustino>pip uninstall apex
Skipping apex as it is not installed.
but i can import apex in cmd.when i import apex in pycharm,it says no module named apex

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:26_Pacific_Standard_Time_2019
Cuda compilation tools, release 10.1, V10.1.105

the pytorch version is 1.0.1

how can i deal with these problem?please help me

**Comment by mcarilli** [comment]
The recommended command to install apex is
```
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```
Also, it should be installed in the same environment that it's going to be run.  I've never used Pycharm before so I'm not sure what the best practice is for installing things in Pycharm.

**Comment by yaodonggggggg** [comment]
> I think this is a Pytorch extension building issue, not an Apex-specific issue. I've never used Pycharm before so I'm not sure what's necessary to make extensions work with Pycharm on Windows.
> 
> The recommended command to install apex is
> 
> ```
> pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
> ```
> Also, it should be installed in the same environment that it's going to be run. If those don't work, you can try the upstream cpp extension tests:
> 
> ```
> git clone https://github.com/pytorch/pytorch.git
> cd pytorch
> cd test
> cd cpp_extensions
> python setup.py install
> cd ..
> python test_cpp_extensions.py
> ```
> If that also fails, it's an issue with extension building in general in your environment, and you should file an issue with Pytorch about the errors you see.
> 
> As a last resort, you can try a Python-only install of Apex:
> 
> ```
> pip install -v --no-cache-dir .
> ```
> This will limit some features and be a bit slower, but Amp will still work.

thanks！！！

**Comment by Anandsrivastava90** [comment]
Hi
I am intalling Detectron2 in Windows10 , when I run python setup.py install I am getting this error .Please help me out

Microsoft Visual Studio 2019
pytorch 1.5
cuda 10.1

Traceback (most recent call last):
File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
check=True)
File "D:\anaconda\envs\detectron_project\lib\subprocess.py", line 438, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "setup.py", line 115, in
cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools_init_.py", line 165, in setup
return distutils.core.setup(**attrs)
File "D:\anaconda\envs\detectron_project\lib\distutils\core.py", line 148, in setup
dist.run_commands()
File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 955, in run_commands
self.run_command(cmd)
File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 974, in run_command
cmd_obj.run()
File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\install.py", line 67, in run
self.do_egg_install()
File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
self.run_command('bdist_egg')
File "D:\anaconda\envs\detectron_project\lib\distutils\cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 974, in run_command
cmd_obj.run()
File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run
cmd = self.call_command('install_lib', warn_dir=0)
File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
self.run_command(cmdname)
File "D:\anaconda\envs\detectron_project\lib\distutils\cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 974, in run_command
cmd_obj.run()
File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
self.build()
File "D:\anaconda\envs\detectron_project\lib\distutils\command\install_lib.py", line 107, in build
self.run_command('build_ext')
File "D:\anaconda\envs\detectron_project\lib\distutils\cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 974, in run_command
cmd_obj.run()
File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
_build_ext.run(self)
File "D:\anaconda\envs\detectron_project\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
_build_ext.build_ext.run(self)
File "D:\anaconda\envs\detectron_project\lib\distutils\command\build_ext.py", line 339, in run
self.build_extensions()
File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
build_ext.build_extensions(self)
File "D:\anaconda\envs\detectron_project\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
_build_ext.build_ext.build_extensions(self)
File "D:\anaconda\envs\detectron_project\lib\distutils\command\build_ext.py", line 448, in build_extensions
self._build_extensions_serial()
File "D:\anaconda\envs\detectron_project\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
self.build_extension(ext)
File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
_build_ext.build_extension(self, ext)
File "D:\anaconda\envs\detectron_project\lib\distutils\command\build_ext.py", line 533, in build_extension
depends=ext.depends)
File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
with_cuda=with_cuda)
File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
error_prefix='Error compiling objects for extension')
File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
