### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'log_softmax' when run inception_v3

### ISSUE THREAD

**Issue by binbinmeng** [NVIDIA/apex#27]
>>python main.py -a inception_v3 --epoch 5 -b 64  /workspace/imagenet/ --fp16
=> creating model 'inception_v3'
Traceback (most recent call last):
  File "main.py", line 466, in <module>
    main()
  File "main.py", line 212, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 293, in train
    loss = criterion(output, target_var)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 779, in forward
    self.ignore_index, self.reduce)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/functional.py", line 1454, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, size_average, ignore_index, reduce)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/functional.py", line 946, in log_softmax
    return input.log_softmax(dim)
AttributeError: 'tuple' object has no attribute 'log_softmax'

node:
    In [2]: print(torch.__version__)
       **0.5.0a0**

**Comment by mcarilli** [comment]
Thanks for letting me know, I'll see if I can reproduce this tomorrow.

**Comment by csarofeen** [comment]
This is known for inception_v3, please see https://github.com/pytorch/vision/issues/302
