### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by lemonhu** [NVIDIA/apex#276]
I use the following commands to install `apex`, but failed.

> $ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .

The error message is as follows：
```
...
    running install_egg_info
    running egg_info
    creating apex.egg-info
    writing apex.egg-info/PKG-INFO
    writing dependency_links to apex.egg-info/dependency_links.txt
    writing top-level names to apex.egg-info/top_level.txt
    writing manifest file 'apex.egg-info/SOURCES.txt'
    reading manifest file 'apex.egg-info/SOURCES.txt'
    writing manifest file 'apex.egg-info/SOURCES.txt'
    Copying apex.egg-info to /root/anaconda3/envs/hzq_env/lib/python3.7/site-packages/apex-0.1-py3.7.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-record-p5wp04si/install-record.txt'
  Running setup.py install for apex ... done
  Removing source in /tmp/pip-req-build-8g5_cw9w
Successfully installed apex-0.1
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-k7_y7y7y'
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 11064
Analyzing links from page https://pypi.org/simple/pip/
  Found link https://files.pythonhosted.org/packages/3d/9d/1e313763bdfb6a48977b65829c6ce2a43eaae29ea2f907c8bbef024a7219/pip-0.2.tar.gz#sha256=88bb8d029e1bf4acd0e04d300104b7440086f94cc1ce1c5c3c31e3293aee1f81 (from https://pypi.org/simple/pip/), version: 0.2
  Found link https://files.pythonhosted.org/packages/18/ad/c0fe6cdfe1643a19ef027c7168572dac6283b80a384ddf21b75b921877da/pip-0.2.1.tar.gz#sha256=83522005c1266cc2de97e65072ff7554ac0f30ad369c3b02ff3a764b962048da (from https://pypi.org/simple/pip/), version: 0.2.1
  Found link https://files.pythonhosted.org/packages/17/05/f66144ef69b436d07f8eeeb28b7f77137f80de4bf60349ec6f0f9509e801/pip-0.3.tar.gz#sha256=183c72455cb7f8860ac1376f8c4f14d7f545aeab8ee7c22cd4caf79f35a2ed47 (from https://pypi.org/simple/pip/), version: 0.3
  Found link https://files.pythonhosted.org/packages/0a/bb/d087c9a1415f8726e683791c0b2943c53f2b76e69f527f2e2b2e9f9e7b5c/pip-0.3.1.tar.gz#sha256=34ce534f17065c78f980702928e988a6b6b2d8a9851aae5f1571a1feb9bb58d8 (from https://pypi.org/simple/pip/), version: 0.3.1
  Found link https://files.pythonhosted.org/packages/cf/c3/153571aaac6cf999f4bb09c019b1ff379b7b599ea833813a41c784eec995/pip-0.4.tar.gz#sha256=28fc67558874f71fddda7168f73595f1650523dce3bc5bf189713ecdfc1e456e (from https://pypi.org/simple/pip/), version: 0.4
  Found link https://files.pythonhosted.org/packages/8d/c7/f05c87812fa5d9562ecbc5f4f1fc1570444f53c81c834a7f662af406e3c1/pip-0.5.tar.gz#sha256=328d8412782f22568508a0d0c78a49c9920a82e44c8dfca49954fe525c152b2a (from https://pypi.org/simple/pip/), version: 0.5
  Found link https://files.pythonhosted.org/packages/9a/aa/f536b6d14fe03343367da2ff44eee28f340ae650cd017ca088b6be13084a/pip-0.5.1.tar.gz#sha256=e27650538c41fe1007a41abd4cfd0f905b822622cbe1f8e7e09d1215af207694 (from https://pypi.org/simple/pip/), version: 0.5.1
  Found link https://files.pythonhosted.org/packages/db/e6/fdf7be8a17b032c533d3f91e91e2c63dd81d3627cbe4113248a00c2d39d8/pip-0.6.tar.gz#sha256=4cf47db6815b2f435d1f44e1f35ff04823043f6161f7df9aec71a123b0c47f0d (from https://pypi.org/simple/pip/), version: 0.6
...
```
I refer to the [reply](https://github.com/NVIDIA/apex/issues/247#issuecomment-480904902) of the issue #247, but still failed. Thanks for your reply.

**Comment by seongwook-ham** [comment]
Successfully installed apex-0.1? 
which message does mean fail?

**Comment by lemonhu** [comment]
I tried again, the bug information is as follows:
```
    nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    csrc/type_shim.h(118): error: identifier "__shfl_down_sync" is undefined
              detected during instantiation of "T reduce_block_into_lanes(T *, T, int, __nv_bool) [with T=float]"
    csrc/multi_tensor_l2norm_kernel.cu(67): here

    1 error detected in the compilation of "/tmp/tmpxft_00013d7a_00000000-7_multi_tensor_l2norm_kernel.cpp1.ii".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
error
Cleaning up...
  Removing source in /tmp/pip-req-build-uep8kkq9
Removed build tracker '/tmp/pip-req-tracker-9mxrbnss'
Command "/root/anaconda2/envs/hzq_env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-uep8kkq9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-mczx8wwx/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-uep8kkq9/
Exception information:
Traceback (most recent call last):
  File "/root/anaconda2/envs/hzq_env/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/root/anaconda2/envs/hzq_env/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/root/anaconda2/envs/hzq_env/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/root/anaconda2/envs/hzq_env/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 945, in install
    spinner=spinner,
  File "/root/anaconda2/envs/hzq_env/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/root/anaconda2/envs/hzq_env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-uep8kkq9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-mczx8wwx/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-uep8kkq9/
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 11064
Analyzing links from page https://pypi.org/simple/pip/
```

**Comment by ptrblck** [comment]
@lemonhu Are you using CUDA8? Your issue might be related to [this one](https://github.com/NVIDIA/apex/issues/95).
Would you be able to update your CUDA version, if that's the case?

**Comment by lemonhu** [comment]
My server contains two versions of cuda8 and cuda10. The problem may be because I used the version of cuda8.
Thanks for your answer.
