### ISSUE TITLE
Error using fused adam: p_copy.type().is_cuda() ASSERT FAILED

### ISSUE THREAD

**Issue by mpagli** [NVIDIA/apex#279]
I have this error when using fused Adam:

```
Traceback (most recent call last):                                                                                                                                                                   | 5/1100342 [00:19<1320:18:48,  4.32s/it]
  File "main.py", line 294, in <module>
    main(params)
  File "main.py", line 167, in main
    optimizer.step()
  File "/home/me/.local/lib/python3.6/site-packages/apex/optimizers/fp16_optimizer.py", line 151, in step
    grad_norms=norm_groups)
  File "/home/me/.local/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 146, in step
    group['weight_decay'])
RuntimeError: p_copy.type().is_cuda() ASSERT FAILED at csrc/fused_adam_cuda.cpp:13, please report a bug to PyTorch. p_copy must be a CUDA tensor (adam at csrc/fused_adam_cuda.cpp:13)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f42308ab441 in /home/me/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f42308aad7a in /home/me/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: adam(at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, at::Tensor&, float, float, float, float, float, int, int, int, float) + 0xb7f (0x7f42265745af in /home/me/.local/lib/python3.6/site-packages/fused_adam_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x145d8 (0x7f422657f5d8 in /home/me/.local/lib/python3.6/site-packages/fused_adam_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x1466e (0x7f422657f66e in /home/me/.local/lib/python3.6/site-packages/fused_adam_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x1160c (0x7f422657c60c in /home/me/.local/lib/python3.6/site-packages/fused_adam_cuda.cpython-36m-x86_64-linux-gnu.so)
```

I didn't have this error previously (with an older version of Apex). Any idea where this could come from? 

Thanks for the great lib!!

**Comment by ptrblck** [comment]
Hi @mpagli,

I assume you are using the latest master build for apex?
Could you post a small reproducible code snippet so that we could take a look into this issue?

**Comment by mcarilli** [comment]
Also, can you give us the commit hash that you're using when you see this error?  If possible, can you also give us the commit hash from the earlier version that worked?

**Comment by mpagli** [comment]
That's my mistake, I was sending the model to the GPU after building the optimizer. Sorry for the trouble.
