### ISSUE TITLE
Grad overflow on iteration occurs frequently?

### ISSUE THREAD

**Issue by lemonhu** [NVIDIA/apex#289]
Hi, Grad overflow on iteration occurs frequently in my experiments, and the result is always zero, what's going on? Tanks for your reply.
```
Epoch 1/20
  0% 0/184 [00:00<?, ?it/s]
Grad overflow on iteration 0
Using dynamic loss scale of 65536
  1% 1/184 [00:00<01:34,  1.93it/s, loss=4.215]
Grad overflow on iteration 1
Using dynamic loss scale of 32768.0
  1% 2/184 [00:00<01:24,  2.15it/s, loss=4.174]
Grad overflow on iteration 2
Using dynamic loss scale of 16384.0
  4% 8/184 [00:03<01:14,  2.35it/s, loss=4.251]
Grad overflow on iteration 8
Using dynamic loss scale of 8192.0
  8% 14/184 [00:05<01:02,  2.72it/s, loss=3.725]
Grad overflow on iteration 14
Using dynamic loss scale of 4096.0
  8% 15/184 [00:05<00:58,  2.87it/s, loss=3.562]
Grad overflow on iteration 15
Using dynamic loss scale of 2048.0
  9% 16/184 [00:06<01:10,  2.38it/s, loss=3.418]
Grad overflow on iteration 16
Using dynamic loss scale of 1024.0
  9% 17/184 [00:06<01:09,  2.41it/s, loss=3.292]
Grad overflow on iteration 17
Using dynamic loss scale of 512.0
 10% 18/184 [00:07<01:06,  2.50it/s, loss=3.187]
Grad overflow on iteration 18
Using dynamic loss scale of 256.0
 10% 19/184 [00:07<01:08,  2.40it/s, loss=3.098]
Grad overflow on iteration 19
Using dynamic loss scale of 128.0
 11% 20/184 [00:08<01:07,  2.44it/s, loss=3.017]
Grad overflow on iteration 20
Using dynamic loss scale of 64.0
 12% 22/184 [00:08<01:06,  2.45it/s, loss=2.866]
Grad overflow on iteration 22
Using dynamic loss scale of 32.0
 12% 23/184 [00:09<01:11,  2.26it/s, loss=2.791]
Grad overflow on iteration 23
Using dynamic loss scale of 16.0
 13% 24/184 [00:09<01:07,  2.37it/s, loss=2.718]
Grad overflow on iteration 24
Using dynamic loss scale of 8.0
 17% 32/184 [00:13<00:59,  2.55it/s, loss=2.405]
Grad overflow on iteration 32
Using dynamic loss scale of 4.0
 20% 37/184 [00:15<01:12,  2.02it/s, loss=2.350]
Grad overflow on iteration 37
Using dynamic loss scale of 2.0
 21% 38/184 [00:16<01:24,  1.72it/s, loss=2.312]
Grad overflow on iteration 38
Using dynamic loss scale of 1.0
 22% 40/184 [00:17<01:10,  2.05it/s, loss=2.245]
Grad overflow on iteration 40
Using dynamic loss scale of 1
 22% 41/184 [00:17<01:13,  1.96it/s, loss=2.211]
Grad overflow on iteration 41
Using dynamic loss scale of 1
 23% 42/184 [00:18<01:08,  2.06it/s, loss=2.175]
Grad overflow on iteration 42
Using dynamic loss scale of 1
 25% 46/184 [00:19<00:57,  2.41it/s, loss=2.082]
Grad overflow on iteration 46
Using dynamic loss scale of 1
 26% 48/184 [00:20<00:56,  2.41it/s, loss=2.040]
Grad overflow on iteration 48
Using dynamic loss scale of 1
 27% 49/184 [00:21<00:58,  2.30it/s, loss=2.022]
Grad overflow on iteration 49
Using dynamic loss scale of 1
 27% 50/184 [00:21<00:58,  2.29it/s, loss=2.002]
Grad overflow on iteration 50
Using dynamic loss scale of 1
```

**Comment by ptrblck** [comment]
Could you post the code you are using to initialize `amp`?
Are you using `DynamicLossScaler` manually?

**Comment by lemonhu** [comment]
The above problem is gone, but there is a new problem.
```
Removed build tracker '/tmp/pip-req-tracker-qvdna99u'
ERROR: Command "/home/hzq/.conda/envs/pytorch1.0/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-23738ryl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-u5w30me9/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-23738ryl/
Exception information:
Traceback (most recent call last):
  File "/home/hzq/.conda/envs/pytorch1.0/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/hzq/.conda/envs/pytorch1.0/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/hzq/.conda/envs/pytorch1.0/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/hzq/.conda/envs/pytorch1.0/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 953, in install
    spinner=spinner,
  File "/home/hzq/.conda/envs/pytorch1.0/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
```

**Comment by lemonhu** [comment]
Yeah, I used DynamicLossScaler manually, like this:
```
optimizer = FP16_Optimizer(optimizer, dynamic_loss_scale=True)
```
This should be a problem with my program. After several epochs, it recovered stability.

**Comment by ptrblck** [comment]
Thanks for the information!
`FP16_Optimizer` is deprecated and I would recommend to use the new API.
You can find some instructions in out [transition guide](https://nvidia.github.io/apex/amp.html#for-users-of-the-old-fp16-optimizer).

Let me know, if that solves the issue.
