### ISSUE TITLE
Bilinear RunTimeError : Expected object of scalar type Half but got scalar type Float for argument #2 'mat2'

### ISSUE THREAD

**Issue by buptorange** [NVIDIA/apex#302]
Thanks for your great work! 
I just used the codes in example:
`model,optimizer = amp.initialize(model,optimizer,opt_level='O1')`
and it turns out that

> After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Training on  1  GPU(s)
lr =  1e-05
Epoch 8:   0%|                                         | 0/1000 [00:00<?, ?it/s]total_batch_count =  7000
Traceback (most recent call last):
  File "tapex.py", line 302, in <module>
    train(train_gen, v, m, p, t, val_gen, train_status)
  File "tapex.py", line 162, in train
    raise e
  File "tapex.py", line 155, in train
    show_cover_loss=params.show_cover_loss,tokenizer = tokenizer)
  File "tapex.py", line 33, in train_batch
    ext_vocab_size=ext_vocab_size, include_cover_loss=show_cover_loss, tokenizer = tokenizer)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/pg/model.py", line 381, in forward
    log_prob=log_prob)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/pg/model.py", line 141, in forward
    encoder_states)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 136, in forward
    return F.bilinear(input1, input2, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 1364, in bilinear
    return torch.bilinear(input1, input2, weight, bias)
RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'mat2'
>
Seems something incompatible the weight of bilinear layer?
Without apex, no errors have occured here before.

**Comment by mcarilli** [comment]
I think this is because bilinear needs to be on the list of functions that take multiple inputs (aka PromoteFunctions).

**Comment by mcarilli** [comment]
Please retry with the latest master
```
pip uninstall apex
cd apex_repo_dir
git pull
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```
and reopen if the error continues.

**Comment by adihaviv** [comment]
I am getting the same issue. can you help? 

i'm using the latest build from apex. 
Python 3.7.0 
torch 1.2.0
transformers 2.1.1

Here is the sample code:
model, optimizer = amp.initialize(model, optimizer, opt_level=O1, loss_scale=1)
model = torch.nn.DataParallel(model)

class BertApexBug(m.BertPreTrainedModel):
    def __init__(self, config):
        super(BertApexBug, self).__init__(config)
        self.bert = m.BertModel(config)
        self.bi = nn.Bilinear(config.hidden_size, config.hidden_size, 1)
        self.init_weights()

    def forward(self, input_ids, token_type_ids=None, attention_mask=None, labels=None, attention_oracle_mask=None):

        flat_input_ids = input_ids.view(-1, input_ids.size(-1))  
        flat_token_type_ids = token_type_ids.view(-1, token_type_ids.size(-1))
        flat_attention_mask = attention_mask.view(-1, attention_mask.size(-1))

        outputs = self.bert(flat_input_ids, flat_token_type_ids, flat_attention_mask)
        pooled_output = outputs[1]

        bi = self.bi(pooled_output,pooled_output)

        return bi

Original Traceback (most recent call last):
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/specific/netapp5_2/gamir/adi/git/common-sense-distillnet/openbook_bert_models.py", line 170, in forward
    bi = self.bi(pooled_output,pooled_output)
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 155, in forward
    return F.bilinear(input1, input2, self.weight, self.bias)
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/functional.py", line 1380, in bilinear
    return torch.bilinear(input1, input2, weight, bias)
**RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'mat2'**

Thanks!

**Comment by thienan092** [comment]
I got the same issue with _**torch.einsum**_. It solved by casting operands to float ( like this torch.einsum('a,b->ab', a.float(), b.float()) ).
