### ISSUE TITLE
AttributeError: 'Adagrad' object has no attribute '_amp_stash'

### ISSUE THREAD

**Issue by agemagician** [NVIDIA/apex#307]
Hello,
I am trying to convert the transformer xl code from using the old fp16 api to work with the new api. In order to use the conservative mixed precision.
https://github.com/kimiyoung/transformer-xl/tree/master/pytorch

However, I always get the following error:
```
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "train_apex.py", line 614, in <module>
[1,1]<stderr>:    train()
[1,1]<stderr>:  File "train_apex.py", line 513, in train
[1,1]<stderr>:    with amp.scale_loss(loss, optimizer) as scaled_loss:
[1,1]<stderr>:  File "/home/ubuntu/anaconda3/envs/pytorchp3/lib/python3.6/contextlib.py", line 81, in __enter__
[1,1]<stderr>:    return next(self.gen)
[1,1]<stderr>:  File "/home/ubuntu/anaconda3/envs/pytorchp3/lib/python3.6/site-packages/apex/amp/handle.py", line 112, in scale_loss
[1,1]<stderr>:    if not optimizer._amp_stash.params_have_scaled_gradients:
[1,1]<stderr>:AttributeError: 'Adagrad' object has no attribute '_amp_stash'
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_apex.py", line 614, in <module>
[1,0]<stderr>:    train()
[1,0]<stderr>:  File "train_apex.py", line 513, in train
[1,0]<stderr>:    with amp.scale_loss(loss, optimizer) as scaled_loss:
[1,0]<stderr>:  File "/home/ubuntu/anaconda3/envs/pytorchp3/lib/python3.6/contextlib.py", line 81, in __enter__
[1,0]<stderr>:    return next(self.gen)
[1,0]<stderr>:  File "/home/ubuntu/anaconda3/envs/pytorchp3/lib/python3.6/site-packages/apex/amp/handle.py", line 112, in scale_loss
[1,0]<stderr>:    if not optimizer._amp_stash.params_have_scaled_gradients:
[1,0]<stderr>:AttributeError: 'Adagrad' object has no attribute '_amp_stash'
```

Any suggestion how I can fix this issue ?

Command:
`python train_apex.py         --cuda         --data /home/ubuntu/Downloads/dataset/uniref50/transformerxl/         --dataset uniref50         --n_layer 24         --d_model 1024         --n_head 8         --d_head 128         --d_inner 3072         --dropout 0.15         --dropatt 0.15         --optim adam         --lr 0.00025         --warmup_step 10000         --max_step 1000000         --tgt_len 512         --mem_len 512         --eval_tgt_len 128         --batch_size 3 --opt-level O1`

New Code:
```
# coding: utf-8
import argparse
import time
import math
import os, sys
import itertools

import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim

from data_utils import get_lm_corpus
from mem_transformer_apex import MemTransformerLM
from utils.exp_utils import create_exp_dir
from utils.data_parallel import BalancedDataParallel

import horovod.torch as hvd

parser = argparse.ArgumentParser(description='PyTorch Transformer Language Model')
parser.add_argument('--data', type=str, default='../data/wikitext-103',
                    help='location of the data corpus')
parser.add_argument('--dataset', type=str, default='wt103',
                    choices=['wt103', 'lm1b', 'enwik8', 'text8', 'uniref50'],
                    help='dataset name')
parser.add_argument('--n_layer', type=int, default=12,
                    help='number of total layers')
parser.add_argument('--n_head', type=int, default=10,
                    help='number of heads')
parser.add_argument('--d_head', type=int, default=50,
                    help='head dimension')
parser.add_argument('--d_embed', type=int, default=-1,
                    help='embedding dimension')
parser.add_argument('--d_model', type=int, default=500,
                    help='model dimension')
parser.add_argument('--d_inner', type=int, default=1000,
                    help='inner dimension in FF')
parser.add_argument('--dropout', type=float, default=0.0,
                    help='global dropout rate')
parser.add_argument('--dropatt', type=float, default=0.0,
                    help='attention probability dropout rate')
parser.add_argument('--init', default='normal', type=str,
                    help='parameter initializer to use.')
parser.add_argument('--emb_init', default='normal', type=str,
                    help='parameter initializer to use.')
parser.add_argument('--init_range', type=float, default=0.1,
                    help='parameters initialized by U(-init_range, init_range)')
parser.add_argument('--emb_init_range', type=float, default=0.01,
                    help='parameters initialized by U(-init_range, init_range)')
parser.add_argument('--init_std', type=float, default=0.02,
                    help='parameters initialized by N(0, init_std)')
parser.add_argument('--proj_init_std', type=float, default=0.01,
                    help='parameters initialized by N(0, init_std)')
parser.add_argument('--optim', default='adam', type=str,
                    choices=['adam', 'sgd', 'adagrad'],
                    help='optimizer to use.')
parser.add_argument('--lr', type=float, default=0.00025,
                    help='initial learning rate (0.00025|5 for adam|sgd)')
parser.add_argument('--mom', type=float, default=0.0,
                    help='momentum for sgd')
parser.add_argument('--scheduler', default='cosine', type=str,
                    choices=['cosine', 'inv_sqrt', 'dev_perf', 'constant'],
                    help='lr scheduler to use.')
parser.add_argument('--warmup_step', type=int, default=0,
                    help='upper epoch limit')
parser.add_argument('--decay_rate', type=float, default=0.5,
                    help='decay factor when ReduceLROnPlateau is used')
parser.add_argument('--lr_min', type=float, default=0.0,
                    help='minimum learning rate during annealing')
parser.add_argument('--clip', type=float, default=0.25,
                    help='gradient clipping')
parser.add_argument('--clip_nonemb', action='store_true',
                    help='only clip the gradient of non-embedding params')
parser.add_argument('--max_step', type=int, default=100000,
                    help='upper epoch limit')
parser.add_argument('--batch_size', type=int, default=60,
                    help='batch size')
parser.add_argument('--batch_chunk', type=int, default=1,
                    help='split batch into chunks to save memory')
parser.add_argument('--tgt_len', type=int, default=70,
                    help='number of tokens to predict')
parser.add_argument('--eval_tgt_len', type=int, default=50,
                    help='number of tokens to predict for evaluation')
parser.add_argument('--ext_len', type=int, default=0,
                    help='length of the extended context')
parser.add_argument('--mem_len', type=int, default=0,
                    help='length of the retained previous heads')
parser.add_argument('--not_tied', action='store_true',
                    help='do not tie the word embedding and softmax weights')
parser.add_argument('--seed', type=int, default=1111,
                    help='random seed')
parser.add_argument('--cuda', action='store_true',
                    help='use CUDA')
parser.add_argument('--adaptive', action='store_true',
                    help='use adaptive softmax')
parser.add_argument('--div_val', type=int, default=1,
                    help='divident value for adapative input and softmax')
parser.add_argument('--pre_lnorm', action='store_true',
                    help='apply LayerNorm to the input instead of the output')
parser.add_argument('--varlen', action='store_true',
                    help='use variable length')
parser.add_argument('--multi_gpu', action='store_true',
                    help='use multiple GPU')
parser.add_argument('--log-interval', type=int, default=200,
                    help='report interval')
parser.add_argument('--eval-interval', type=int, default=4000,
                    help='evaluation interval')
parser.add_argument('--work_dir', default='LM-TFM', type=str,
                    help='experiment directory.')
parser.add_argument('--restart', action='store_true',
                    help='restart training from the saved checkpoint')
parser.add_argument('--restart_dir', type=str, default='',
                    help='restart dir')
parser.add_argument('--debug', action='store_true',
                    help='run in debug mode (do not create exp dir)')
parser.add_argument('--same_length', action='store_true',
                    help='use the same attn length for all tokens')
parser.add_argument('--attn_type', type=int, default=0,
                    help='attention type. 0 for ours, 1 for Shaw et al,'
                    '2 for Vaswani et al, 3 for Al Rfou et al.')
parser.add_argument('--clamp_len', type=int, default=-1,
                    help='use the same pos embeddings after clamp_len')
parser.add_argument('--eta_min', type=float, default=0.0,
                    help='min learning rate for cosine scheduler')
parser.add_argument('--gpu0_bsz', type=int, default=-1,
                    help='batch size on gpu 0')
parser.add_argument('--max_eval_steps', type=int, default=-1,
                    help='max eval steps')
parser.add_argument('--sample_softmax', type=int, default=-1,
                    help='number of samples in sampled softmax')
parser.add_argument('--patience', type=int, default=0,
                    help='patience')
parser.add_argument('--finetune_v2', action='store_true',
                    help='finetune v2')
parser.add_argument('--finetune_v3', action='store_true',
                    help='finetune v3')
parser.add_argument('--fp16', action='store_true',
                    help='Run in pseudo-fp16 mode (fp16 storage fp32 math).')
parser.add_argument('--static-loss-scale', type=float, default=1,
                    help='Static loss scale, positive power of 2 values can '
                    'improve fp16 convergence.')
parser.add_argument('--dynamic-loss-scale', action='store_true',
                    help='Use dynamic loss scaling.  If supplied, this argument'
                    ' supersedes --static-loss-scale.')
#apex aurgment
parser.add_argument('--opt-level', type=str)
parser.add_argument('--keep-batchnorm-fp32', type=str, default=None)
parser.add_argument('--loss-scale', type=str, default=None)

args = parser.parse_args()
args.tied = not args.not_tied

if args.d_embed < 0:
    args.d_embed = args.d_model

assert args.ext_len >= 0, 'extended context length must be non-negative'
assert args.batch_size % args.batch_chunk == 0

#apex : check if it is installed
try:
    from apex.parallel import DistributedDataParallel as DDP
    from apex.fp16_utils import *
    from apex import amp, optimizers
    from apex.multi_tensor_apply import multi_tensor_applier
except ImportError:
    raise ImportError("Please install apex from https://www.github.com/nvidia/apex to run this example.")
assert torch.backends.cudnn.enabled, "Amp requires cudnn backend to be enabled."

args.work_dir = '{}-{}'.format(args.work_dir, args.dataset)
args.work_dir = os.path.join(args.work_dir, time.strftime('%Y%m%d-%H%M%S'))
logging = create_exp_dir(args.work_dir,
    scripts_to_save=['train.py', 'mem_transformer.py'], debug=args.debug)

# Set the random seed manually for reproducibility.
np.random.seed(args.seed)
torch.manual_seed(args.seed)
if torch.cuda.is_available():
    if not args.cuda:
        print('WARNING: You have a CUDA device, so you should probably run with --cuda')
    else:
        torch.cuda.manual_seed_all(args.seed)

# Validate `--fp16` option
if args.fp16:
    if not args.cuda:
        print('WARNING: --fp16 requires --cuda, ignoring --fp16 option')
        args.fp16 = False
    else:
        try:
            from apex.fp16_utils import FP16_Optimizer
        except:
            print('WARNING: apex not installed, ignoring --fp16 option')
            args.fp16 = False

device = torch.device('cuda' if args.cuda else 'cpu')

# Initialize Horovod
hvd.init()

# Pin GPU to be used to process local rank (one GPU per process)
torch.cuda.set_device(hvd.local_rank())

# Horovod: Adjust the max steps and warm up steps to match number of nodes
args.max_step = args.max_step // hvd.size()
args.warmup_step = args.warmup_step // hvd.size()

###############################################################################
# Load data
###############################################################################
corpus = get_lm_corpus(args.data, args.dataset)
ntokens = len(corpus.vocab)
args.n_token = ntokens

eval_batch_size = 10
tr_iter = corpus.get_iterator('train', args.batch_size, args.tgt_len,
    device=device, ext_len=args.ext_len)
va_iter = corpus.get_iterator('valid', eval_batch_size, args.eval_tgt_len,
    device=device, ext_len=args.ext_len)
te_iter = corpus.get_iterator('test', eval_batch_size, args.eval_tgt_len,
    device=device, ext_len=args.ext_len)

# adaptive softmax / embedding
cutoffs, tie_projs = [], [False]
if args.adaptive:
    assert args.dataset in ['wt103', 'lm1b']
    if args.dataset == 'wt103':
        cutoffs = [20000, 40000, 200000]
        tie_projs += [True] * len(cutoffs)
    elif args.dataset == 'lm1b':
        cutoffs = [60000, 100000, 640000]
        tie_projs += [False] * len(cutoffs)

###############################################################################
# Build the model
###############################################################################
def init_weight(weight):
    if args.init == 'uniform':
        nn.init.uniform_(weight, -args.init_range, args.init_range)
    elif args.init == 'normal':
        nn.init.normal_(weight, 0.0, args.init_std)

def init_bias(bias):
    nn.init.constant_(bias, 0.0)

def weights_init(m):
    classname = m.__class__.__name__
    if classname.find('Linear') != -1:
        if hasattr(m, 'weight') and m.weight is not None:
            init_weight(m.weight)
        if hasattr(m, 'bias') and m.bias is not None:
            init_bias(m.bias)
    elif classname.find('AdaptiveEmbedding') != -1:
        if hasattr(m, 'emb_projs'):
            for i in range(len(m.emb_projs)):
                if m.emb_projs[i] is not None:
                    nn.init.normal_(m.emb_projs[i], 0.0, args.proj_init_std)
    elif classname.find('Embedding') != -1:
        if hasattr(m, 'weight'):
            init_weight(m.weight)
    elif classname.find('ProjectedAdaptiveLogSoftmax') != -1:
        if hasattr(m, 'cluster_weight') and m.cluster_weight is not None:
            init_weight(m.cluster_weight)
        if hasattr(m, 'cluster_bias') and m.cluster_bias is not None:
            init_bias(m.cluster_bias)
        if hasattr(m, 'out_projs'):
            for i in range(len(m.out_projs)):
                if m.out_projs[i] is not None:
                    nn.init.normal_(m.out_projs[i], 0.0, args.proj_init_std)
    elif classname.find('LayerNorm') != -1:
        if hasattr(m, 'weight'):
            nn.init.normal_(m.weight, 1.0, args.init_std)
        if hasattr(m, 'bias') and m.bias is not None:
            init_bias(m.bias)
    elif classname.find('TransformerLM') != -1:
        if hasattr(m, 'r_emb'):
            init_weight(m.r_emb)
        if hasattr(m, 'r_w_bias'):
            init_weight(m.r_w_bias)
        if hasattr(m, 'r_r_bias'):
            init_weight(m.r_r_bias)
        if hasattr(m, 'r_bias'):
            init_bias(m.r_bias)

def update_dropout(m):
    classname = m.__class__.__name__
    if classname.find('Dropout') != -1:
        if hasattr(m, 'p'):
            m.p = args.dropout

def update_dropatt(m):
    if hasattr(m, 'dropatt'):
        m.dropatt.p = args.dropatt

if args.restart:
    with open(os.path.join(args.restart_dir, 'model.pt'), 'rb') as f:
        model = torch.load(f)
    if not args.fp16:
        model = model.float()
    model.apply(update_dropout)
    model.apply(update_dropatt)
else:
    model = MemTransformerLM(ntokens, args.n_layer, args.n_head, args.d_model,
        args.d_head, args.d_inner, args.dropout, args.dropatt,
        tie_weight=args.tied, d_embed=args.d_embed, div_val=args.div_val,
        tie_projs=tie_projs, pre_lnorm=args.pre_lnorm, tgt_len=args.tgt_len,
        ext_len=args.ext_len, mem_len=args.mem_len, cutoffs=cutoffs,
        same_length=args.same_length, attn_type=args.attn_type,
        clamp_len=args.clamp_len, sample_softmax=args.sample_softmax)
    model.apply(weights_init)
    model.word_emb.apply(weights_init) # ensure embedding init is not overridden by out_layer in case of weight sharing
args.n_all_param = sum([p.nelement() for p in model.parameters()])
args.n_nonemb_param = sum([p.nelement() for p in model.layers.parameters()])

#### optimizer
if args.optim.lower() == 'sgd':
    if args.sample_softmax > 0:
        dense_params, sparse_params = [], []
        for param in model.parameters():
            if param.size() == model.word_emb.weight.size():
                sparse_params.append(param)
            else:
                dense_params.append(param)
        # Horovod: scale learning rate by the number of GPUs.
        optimizer_sparse = optim.SGD(sparse_params, lr=args.lr * 2 * hvd.size())
        optimizer = optim.SGD(dense_params, lr=args.lr * hvd.size(), momentum=args.mom)
    else:
        # Horovod: scale learning rate by the number of GPUs.
        optimizer = optim.SGD(model.parameters(), lr=args.lr * hvd.size(),
            momentum=args.mom)
elif args.optim.lower() == 'adam':
    if args.sample_softmax > 0:
        dense_params, sparse_params = [], []
        for param in model.parameters():
            if param.size() == model.word_emb.weight.size():
                sparse_params.append(param)
            else:
                dense_params.append(param)
        # Horovod: scale learning rate by the number of GPUs.
        optimizer_sparse = optim.SparseAdam(sparse_params, lr=args.lr * hvd.size())
        optimizer = optim.Adam(dense_params, lr=args.lr * hvd.size())
    else:
        # Horovod: scale learning rate by the number of GPUs.
        optimizer = optim.Adam(model.parameters(), lr=args.lr * hvd.size())
elif args.optim.lower() == 'adagrad':
    # Horovod: scale learning rate by the number of GPUs.
    optimizer = optim.Adagrad(model.parameters(), lr=args.lr * hvd.size())


if args.fp16:
    model = model.half()

if args.multi_gpu:
    model = model.to(device)
    if args.gpu0_bsz >= 0:
        para_model = BalancedDataParallel(args.gpu0_bsz // args.batch_chunk,
                                          model, dim=1).to(device)
    else:
        para_model = nn.DataParallel(model, dim=1).to(device)
else:
    para_model = model.to(device)

# Initialize Amp.  Amp accepts either values or strings for the optional override arguments,
# for convenient interoperation with argparse.
para_model, optimizer = amp.initialize(para_model, optimizer,
                                      opt_level=args.opt_level,
                                      keep_batchnorm_fp32=args.keep_batchnorm_fp32,
                                      loss_scale=args.loss_scale
                                      )

# Add Horovod Distributed Optimizer
optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=para_model.named_parameters())

#### scheduler
if args.scheduler == 'cosine':
    # here we do not set eta_min to lr_min to be backward compatible
    # because in previous versions eta_min is default to 0
    # rather than the default value of lr_min 1e-6
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer,
        args.max_step, eta_min=args.eta_min) # should use eta_min arg
    if args.sample_softmax > 0:
        scheduler_sparse = optim.lr_scheduler.CosineAnnealingLR(optimizer_sparse,
            args.max_step, eta_min=args.eta_min) # should use eta_min arg
elif args.scheduler == 'inv_sqrt':
    # originally used for Transformer (in Attention is all you need)
    def lr_lambda(step):
        # return a multiplier instead of a learning rate
        if step == 0 and args.warmup_step == 0:
            return 1.
        else:
            return 1. / (step ** 0.5) if step > args.warmup_step \
                   else step / (args.warmup_step ** 1.5)
    scheduler = optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=lr_lambda)
elif args.scheduler == 'dev_perf':
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer,
        factor=args.decay_rate, patience=args.patience, min_lr=args.lr_min)
    if args.sample_softmax > 0:
        scheduler_sparse = optim.lr_scheduler.ReduceLROnPlateau(optimizer_sparse,
            factor=args.decay_rate, patience=args.patience, min_lr=args.lr_min)
elif args.scheduler == 'constant':
    pass

if args.cuda and args.fp16:
    # If args.dynamic_loss_scale is False, static_loss_scale will be used.
    # If args.dynamic_loss_scale is True, it will take precedence over static_loss_scale.
    optimizer = FP16_Optimizer(optimizer,
                               static_loss_scale = args.static_loss_scale,
                               dynamic_loss_scale = args.dynamic_loss_scale,
                               dynamic_loss_args = {'init_scale': 2 ** 16})

if args.restart:
    if os.path.exists(os.path.join(args.restart_dir, 'optimizer.pt')):
        with open(os.path.join(args.restart_dir, 'optimizer.pt'), 'rb') as f:
            opt_state_dict = torch.load(f)
            optimizer.load_state_dict(opt_state_dict)
    else:
        print('Optimizer was not saved. Start from scratch.')

# Horovod: Broadcast parameters from rank 0 to all other processes.
hvd.broadcast_parameters(model.state_dict(), root_rank=0)
hvd.broadcast_optimizer_state(optimizer, root_rank=0)

logging('=' * 100)
for k, v in args.__dict__.items():
    logging('    - {} : {}'.format(k, v))
logging('=' * 100)
logging('#params = {}'.format(args.n_all_param))
logging('#non emb params = {}'.format(args.n_nonemb_param))

###############################################################################
# Training code
###############################################################################

# Horovod: averge the values for test from different nodes
def metric_average(val, name):
    tensor = torch.tensor(val)
    avg_tensor = hvd.allreduce(tensor, name=name)
    return avg_tensor.item()

def evaluate(eval_iter):
    # Turn on evaluation mode which disables dropout.
    model.eval()

    # If the model does not use memory at all, make the ext_len longer.
    # Otherwise, make the mem_len longer and keep the ext_len the same.
    if args.mem_len == 0:
        model.reset_length(args.eval_tgt_len,
            args.ext_len+args.tgt_len-args.eval_tgt_len, args.mem_len)
    else:
        model.reset_length(args.eval_tgt_len,
            args.ext_len, args.mem_len+args.tgt_len-args.eval_tgt_len)

    # Evaluation
    total_len, total_loss = 0, 0.
    with torch.no_grad():
        mems = tuple()
        for i, (data, target, seq_len) in enumerate(eval_iter):
            data, target = data.to(device), target.to(device)
            if args.max_eval_steps > 0 and i >= args.max_eval_steps:
                break
            ret = model(data.to(device), target.to(device), *mems)
            loss, mems = ret[0], ret[1:]
            loss = loss.mean()
            total_loss += seq_len * loss.float().item()
            total_len += seq_len

    # Switch back to the training mode
    model.reset_length(args.tgt_len, args.ext_len, args.mem_len)
    model.train()

    return total_loss / total_len


def train():
    # Turn on training mode which enables dropout.
    global train_step, train_loss, best_val_loss, eval_start_time, log_start_time
    model.train()
    if args.batch_chunk > 1:
        mems = [tuple() for _ in range(args.batch_chunk)]
    else:
        mems = tuple()
    train_iter = tr_iter.get_varlen_iter() if args.varlen else tr_iter
    for batch, (data, target, seq_len) in enumerate(train_iter):
        model.zero_grad()
        data, target = data.to(device), target.to(device)
        if args.batch_chunk > 1:
            data_chunks = torch.chunk(data, args.batch_chunk, 1)
            target_chunks = torch.chunk(target, args.batch_chunk, 1)
            for i in range(args.batch_chunk):
                data_i = data_chunks[i].contiguous()
                target_i = target_chunks[i].contiguous()
                ret = para_model(data_i, target_i, *mems[i])
                loss, mems[i] = ret[0], ret[1:]
                loss = loss.float().mean().type_as(loss) / args.batch_chunk
                if args.fp16:
                    optimizer.backward(loss)
                else:
                    #loss.backward()
                    with amp.scale_loss(loss, optimizer) as scaled_loss:
                        scaled_loss.backward()
                train_loss += loss.float().item()
        else:
            #print('Check cuda')
            #print(data.is_cuda)
            #print(target.is_cuda)
            #print(mems.is_cuda)
            ret = para_model(data, target, *mems)
            loss, mems = ret[0], ret[1:]
            loss = loss.float().mean().type_as(loss)
            if args.fp16:
                optimizer.backward(loss)
            else:
                with amp.scale_loss(loss, optimizer) as scaled_loss:
                    scaled_loss.backward()
                #loss.backward()
            train_loss += loss.float().item()

        if args.fp16:
            optimizer.clip_master_grads(args.clip)
        else:
            torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)

        optimizer.step()
        if args.sample_softmax > 0:
            optimizer_sparse.step()

        # step-wise learning rate annealing
        train_step += 1
        if args.scheduler in ['cosine', 'constant', 'dev_perf']:
            # linear warmup stage
            if train_step < args.warmup_step:
                curr_lr = args.lr * train_step / args.warmup_step
                optimizer.param_groups[0]['lr'] = curr_lr
                if args.sample_softmax > 0:
                    optimizer_sparse.param_groups[0]['lr'] = curr_lr * 2
            else:
                if args.scheduler == 'cosine':
                    scheduler.step(train_step)
                    if args.sample_softmax > 0:
                        scheduler_sparse.step(train_step)
        elif args.scheduler == 'inv_sqrt':
            scheduler.step(train_step)

        if train_step % args.log_interval == 0:
            cur_loss = train_loss / args.log_interval
            elapsed = time.time() - log_start_time
            log_str = '| epoch {:3d} step {:>8d} | {:>6d} batches | lr {:.3g} ' \
                      '| ms/batch {:5.2f} | loss {:5.2f}'.format(
                epoch, train_step, batch+1, optimizer.param_groups[0]['lr'],
                elapsed * 1000 / args.log_interval, cur_loss)
            if args.dataset in ['enwik8', 'text8']:
                log_str += ' | bpc {:9.5f}'.format(cur_loss / math.log(2))
            elif args.dataset == 'uniref50':
                log_str += ' | ppl {:9.3f}'.format(math.exp(cur_loss)) + ' | bpc {:9.5f}'.format(cur_loss / math.log(2))
            else:
                log_str += ' | ppl {:9.3f}'.format(math.exp(cur_loss))
            logging(log_str)
            train_loss = 0
            log_start_time = time.time()

        if train_step % args.eval_interval == 0:
            val_loss = evaluate(va_iter)
            
            # Horovod: average metric values across workers.
            val_loss = metric_average(val_loss, 'avg_loss')
            
            # Horovod: Display the validation loss and save the model only in the main node
            if hvd.rank() == 0:
                logging('-' * 100)
                log_str = '| Eval {:3d} at step {:>8d} | time: {:5.2f}s ' \
                        '| valid loss {:5.2f}'.format(
                    train_step // args.eval_interval, train_step,
                    (time.time() - eval_start_time), val_loss)
                if args.dataset in ['enwik8', 'text8']:
                    log_str += ' | bpc {:9.5f}'.format(val_loss / math.log(2))
                elif args.dataset == 'uniref50':
                    log_str += ' | valid ppl {:9.3f}'.format(math.exp(val_loss)) + ' | bpc {:9.5f}'.format(val_loss / math.log(2))
                else:
                    log_str += ' | valid ppl {:9.3f}'.format(math.exp(val_loss))
                logging(log_str)
                logging('-' * 100)
            # Save the model if the validation loss is the best we've seen so far.
            if hv.localrank() == 0:
                if not best_val_loss or val_loss < best_val_loss:
                    if not args.debug:
                        with open(os.path.join(args.work_dir, 'model.pt'), 'wb') as f:
                            torch.save(model, f)
                        with open(os.path.join(args.work_dir, 'optimizer.pt'), 'wb') as f:
                            torch.save(optimizer.state_dict(), f)
                        best_val_loss = val_loss

            # dev-performance based learning rate annealing
            if args.scheduler == 'dev_perf':
                scheduler.step(val_loss)
                if args.sample_softmax > 0:
                    scheduler_sparse.step(val_loss)

            eval_start_time = time.time()

        if train_step == args.max_step:
            break

# Loop over epochs.
train_step = 0
train_loss = 0
best_val_loss = None

log_start_time = time.time()
eval_start_time = time.time()

# At any point you can hit Ctrl + C to break out of training early.
try:
    for epoch in itertools.count(start=1):
        train()
        if train_step == args.max_step:
            logging('-' * 100)
            logging('End of training')
            break
except KeyboardInterrupt:
    logging('-' * 100)
    logging('Exiting from training early')

# Load the best saved model.
with open(os.path.join(args.work_dir, 'model.pt'), 'rb') as f:
    model = torch.load(f)
para_model = model.to(device)

# Run on test data.
test_loss = evaluate(te_iter)
# Horovod: average metric values across workers.
test_loss = metric_average(test_loss, 'avg_loss')

# Horovod: Display the test loss only on the main node
if hvd.rank() == 0:
    logging('=' * 100)
    if args.dataset in ['enwik8', 'text8']:
        logging('| End of training | test loss {:5.2f} | test bpc {:9.5f}'.format(
            test_loss, test_loss / math.log(2)))
    elif args.dataset == 'uniref50':
        logging('| End of training | test loss {:5.2f} | test ppl {:9.3f} | test bpc {:9.5f}'.format(
            test_loss, math.exp(test_loss), test_loss / math.log(2)))
    else:
        logging('| End of training | test loss {:5.2f} | test ppl {:9.3f}'.format(
            test_loss, math.exp(test_loss)))
    logging('=' * 100)

```

I will appreciate your help @mcarilli @ptrblck @csarofeen @FDecaYed @syed-ahmed

**Comment by ptrblck** [comment]
Hi @agemagician,

the `_amp_stash` attribute should be created after `amp.initialize` was called on the `optimizer`.
Based on your code, it looks like you are calling this line afterwards:
```python
optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=para_model.named_parameters())
```
Could you check, if `_amp_stash` was is a registered attribute before and after this line is called?
This should work:
```python
model, optimizer = amp.initialize(...)
print(optimizer._amp_stash)
optimizer = hvd.DistributedOptimizer(optimizer, named_parameters=para_model.named_parameters())
print(optimizer._amp_stash)
```

I'm not familiar with `horovod`, but this information might be a good starter to debug this issue.

Best,
ptrblck

**Comment by agemagician** [comment]
Hi @ptrblck ,

Thanks a lot for your fast reply.

You are correct. After Horovod the problem occurred :

```
<apex.amp._process_optimizer.AmpOptimizerState object at 0x7efffd2fd320>
Traceback (most recent call last):
  File "train_apex.py", line 373, in <module>
    print(optimizer._amp_stash)
AttributeError: 'Adam' object has no attribute '_amp_stash'
```

But this is weird because the old api works fine.
Is there anyway to solve it from your side or it should be solved from Horovod side ?

In case not, Can I use the old api with "conservative mixed precision" mode ? and How ?

**Comment by ptrblck** [comment]
Thanks for this information!
I wouldn't recommend to use the deprecated API.

I'm not really familiar with horovod, but would it be possible to use `apex.parallel.DistributedDataParallel` as a workaround?

Let me know, if that's not possible for your use case.

**Comment by agemagician** [comment]
The data is textual data and if I used apex.parallel.DistributedDataParallel, I assume it is going to send  random batches or consequence batches into separate GPU.
This will not work because the model uses memory similar to LSTM, and If I didn't send batches in correct sequence, the model will not learn correctly.

With Horovod, I divided the dataset at the start into seperate parts where every part is not related to each other and sequence batches is processed by single GPU.

I am not sure if it is possible With  apex.parallel.DistributedDataParallel .

**Comment by agemagician** [comment]
Maybe one clarification that might help me.

Assuming I have batch size 128 and I used "apex.parallel.DistributedDataParallel" with 4 nodes, then it is going to divided the current 128 into 4 nodes where each node will get 32 batch, and during the next iteration the same order will be respected or not ?

If it will not change the way the batches is being processed and generate, then it will work out.

**Comment by mcarilli** [comment]
@ptrblck is right that you shouldn't use the old amp API.

`apex.parallel.DistributedDataParallel` and `torch.nn.parallel.DistributedDataParallel`, **when used with one GPU per process**, do not subdivide the input data batch that's seen by each process.  In other words, if you have batch size 128 **per process**, these DDP wrappers will not change the fact that each process accepts batch size 128 inputs, and if there are 4 processes, this will result in an effective global batch size of 128*4.  Basically, each process will simply handle whatever data batch it is given at each iteration.  As long as you set up the dataloading in each process to feed the right data to the forward pass each iteration, I think it will work properly.

`apex.parallel.DistributedDataParallel` uses one GPU per process by default.  To use `torch.nn.parallel.DistributedDataParallel` with one GPU per process, you must supply the additional constructor arguments `model = DDP(model, device_ids=[arg.local_rank], output_device=arg.local_rank)`.  In both cases, you must call `model = DDP(model)` after `amp.initialize`.  Beware:  If you do not supply the `device_ids` and `output_device` arguments, torch DDP **will** silently choose to use all visible devices, and it **will** silently subdivide the batch across those devices.

We don't officially support or test with Horovod.  However, it's possible that a simple fix will enable your existing Horovod code.  The reason your example is breaking is that `amp.scale_loss(loss, optimizer)` expects `_amp_stash` to be a top-level attributed of `optimizer`, assigned by `amp.initialize`.  With Horovod, you are wrapping the optimizer once more, which means that `_amp_stash` is no longer a top-level attribute.  To make the Horovod version work, the fix might be as simple as passing the underlying optimizer (that's now owned by the horovod-wrapped thing) to `amp.scale_loss`.  Presumably the underlying optimizer is still accessible as an attribute of the Horovod-wrapped optimizer, and `_amp_stash` is still an attribute of the underlying optimizer, so this would look like:
```
with amp.scale_loss(loss, optimizer.underlying_optimizer) as scaled_loss:
    scaled_loss.backward()
```

**Comment by agemagician** [comment]
Thanks a lot @mcarilli for the detailed explanation.

I have tried the second solution and unfortunately, it doesn't work.
Horovod optimizer doesn't have an underlying optimizer.
The propirites of Horovod are only:
```
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex_
_', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_allreduce_delay', '_allreduce_grad_async', '_compression', '_grad_accs', '_handles', '_make_hook', '_parameter_names', '_register_hooks', '_requires_update', 'ad
d_param_group', 'backward_passes_per_step', 'defaults', 'find_duplicates', 'load_state_dict', 'param_groups', 'set_backward_passes_per_step', 'state', 'state_dict', 'step', 'synchronize', 'zero_grad']
```

I will try your first recommendation and I will update you if it did work.

**Comment by agemagician** [comment]
Thanks a lot for your help.
The first method worked out perfectly.

**Comment by parulML** [comment]
@agemagician I am getting the same error while using Apex with Horovod. Could you please help me with how did you fix it.
