### ISSUE TITLE
RuntimeError: Expected object of type torch.cuda.HalfTensor but found type torch.cuda.FloatTensor for argument #3 'weight'

### ISSUE THREAD

**Issue by xternalz** [NVIDIA/apex#32]
Hi, I'm trying to train with FP16. Whenever I set BN layers to `float` type, it gives me

> RuntimeError: Expected object of type torch.cuda.HalfTensor but found type torch.cuda.FloatTensor for argument #3 'weight'

Does anyone have any ideas?

**Comment by mcarilli** [comment]
How are you setting the BN layers to float?  Are you using `network_to_half` as found in [the imagenet example](https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main.py#L122)?

Also, can you copy the full stack trace from your RuntimeError?

**Comment by mcarilli** [comment]
One thing I'm noticing (which may or may not be related) is that you need to convert your network to half before you construct the optimizer.  This is good practice for Pytorch optimizer use in general, because optimizers may choose to create some internal state buffers with the same type as the parameters you initially give them.  If you then change the type of the parameters later (via `model.half()` or `model = network_to_half(model)`) those parameters may become inconsistent with the buffers that the optimizer created for them.

Therefore, the first thing I would try is moving [model = network_to_half(model)](https://gist.github.com/Tensorfengsheng1926/cd7f4924329bddb27b4f8bda108284c2#file-trainfp16-py-L157) to line 114, so the code looks like this:
```
112    state_dict = torch.load(CONFIG.INIT_MODEL)
113    model.load_state_dict(state_dict, strict=False)  # Skip "aspp" layer 
114    model = network_to_half(model)
115    model = nn.DataParallel(model)
```

**Comment by Tensorfengsheng1926** [comment]
Thank you for your reply! I've tried your advice but the same error still occurs...

**Comment by mcarilli** [comment]
Can you post the updated version of your script?  The version I see here: https://gist.github.com/Tensorfengsheng1926/cd7f4924329bddb27b4f8bda108284c2 still has network_to_half on line 157.

**Comment by Tensorfengsheng1926** [comment]
I have updated the script and here is the revision.
https://gist.github.com/Tensorfengsheng1926/cd7f4924329bddb27b4f8bda108284c2/revisions
Thanks!

**Comment by mcarilli** [comment]
Hmm, based on the fact that this error message occurred within backward() itself, I suspect it's not a problem with FP16_Optimizer, but more likely (as @xternalz said) a problem with how `network_to_half` affects your model.

Can you try disabling FP16_Optimizer (just comment out [line 145](https://gist.github.com/Tensorfengsheng1926/cd7f4924329bddb27b4f8bda108284c2/20903982758451bb09156b7739c4a4630af878e4#file-trainfp16-py-L145) and see if the error still occurs?

**Comment by mcarilli** [comment]
Also, this is probably unrelated, but in general we recommend using DistributedDataParallel (with multiple processes) rather than single-process DataParallel for multi-GPU training.  In our experience multiprocess is usually faster.

Apex and Pytorch both have good implementations of DistributedDataParallel module wrappers.
[simple apex.parallel.DistributedDataParallel example](https://github.com/NVIDIA/apex/tree/master/examples/FP16_Optimizer_simple/distributed_apex)
[simple torch.nn.parallel.DistributedDataParallel example](https://github.com/NVIDIA/apex/tree/master/examples/FP16_Optimizer_simple/distributed_pytorch)

**Comment by Tensorfengsheng1926** [comment]
Hi, firstly I've just tried disabling `FP16_Optimizer` and it doesn't seem to support  `optimizer.backward(loss)`.

```
File "trainfp16.py", line 210, in main
    optimizer.backward(loss)
AttributeError: 'SGD' object has no attribute 'backward'
```

And then I used `loss.backward()` instead of `optimizer.backward(loss)`, the same error occured.

```
Traceback (most recent call last):
  File "trainfp16.py", line 262, in <module>
    main()
  File "F:\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "F:\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "F:\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "trainfp16.py", line 209, in main
    loss.backward()
  File "F:\Anaconda3\lib\site-packages\torch\tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "F:\Anaconda3\lib\site-packages\torch\autograd\__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Expected object of type torch.cuda.HalfTensor but found type torch.cuda.FloatTensor for argument #3 'weight'
```

However, when I simply used `model = model.half()` to replace `network_to_half` and enabled `FP16_Optimizer`, somehow it worked pretty well. Running on my RTX2080Ti, FP16 seems to be slower than FP32, but their performance are very close.
Many thanks for your assistance!
