### ISSUE TITLE
Install Error: support PyTorch 0.4.1?

### ISSUE THREAD

**Issue by 1duo** [NVIDIA/apex#34]
I've recently upgraded to `PyTorch 0.4.1`. When I try to install Apex, it gives following error:

```
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import torch
  File "/home/yuduo/anaconda3/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: /home/yuduo/anaconda3/lib/python3.6/site-packages/torch/lib/libshm.so: undefined symbol: _ZTI24THRefcountedMapAllocator
```

**Comment by 1duo** [comment]
Might be PyTorch installation error, tried with `python -c "import torch; print(torch.__version__)"` and does not work. So close this issue as not related to Apex.
