### ISSUE TITLE
[Windows] Install error

### ISSUE THREAD

**Issue by zongbingwang** [NVIDIA/apex#348]
Hi ,
I am trying to install apex on my windows 10.
I have installed currently cuda 10 (cuda toolkit) and pytorch. That works well.
But when I launch the command pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" . I get below error.

Could you have a look about this?

fused_adam_cuda_kernel.cu
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\ProgramData\Miniconda3\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib/x64" /LIBPATH:C:\ProgramData\Miniconda3\libs /LIBPATH:C:\ProgramData\Miniconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" cudart.lib c10.lib caffe2.lib torch.lib torch_python.lib caffe2_gpu.lib _C.lib /EXPORT:PyInit_fused_adam_cuda build\temp.win-amd64-3.7\Release\csrc/fused_adam_cuda.obj build\temp.win-amd64-3.7\Release\csrc/fused_adam_cuda_kernel.obj /OUT:build\lib.win-amd64-3.7\fused_adam_cuda.cp37-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.7\Release\csrc\fused_adam_cuda.cp37-win_amd64.lib
       Creating library build\temp.win-amd64-3.7\Release\csrc\fused_adam_cuda.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\csrc\fused_adam_cuda.cp37-win_amd64.exp
    fused_adam_cuda_kernel.obj : error LNK2001: unresolved external symbol "bool __cdecl at::cuda::detail::canUse32BitIndexMath(class at::Tensor const &,__int64)" (?canUse32BitIndexMath@detail@cuda@at@@YA_NAEBVTensor@3@_J@Z)
    build\lib.win-amd64-3.7\fused_adam_cuda.cp37-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120
error
Cleaning up...
  Removing source in C:\Users\zowan\AppData\Local\Temp\pip-req-build-hxqzj5b8
Removed build tracker 'C:\\Users\\zowan\\AppData\\Local\\Temp\\pip-req-tracker-tap9l_8z'
Command "C:\ProgramData\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\zowan\\AppData\\Local\\Temp\\pip-req-build-hxqzj5b8\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record C:\Users\zowan\AppData\Local\Temp\pip-record-3dv0gjl1\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\zowan\AppData\Local\Temp\pip-req-build-hxqzj5b8\
Exception information:
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\commands\install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "C:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\req\__init__.py", line 57, in install_given_reqs
    **kwargs
  File "C:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\req\req_install.py", line 945, in install
    spinner=spinner,
  File "C:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\utils\misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "C:\ProgramData\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\zowan\\AppData\\Local\\Temp\\pip-req-build-hxqzj5b8\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record C:\Users\zowan\AppData\Local\Temp\pip-record-3dv0gjl1\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\zowan\AppData\Local\Temp\pip-req-build-hxqzj5b8\
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect

**Comment by zongbingwang** [comment]
fixed by upgrade pytorch to 1.1.0
