### ISSUE TITLE
Inconsistency in patching optimizer step

### ISSUE THREAD

**Issue by jbaczek** [NVIDIA/apex#361]
While doing loss scaling AMP patches a step function in this way:
```python
def patch_step(opt, loss_scaler, loss_id):
    opt_step = opt.step
    def skip_step():
        maybe_print(("Gradient overflow.  Skipping step, loss scaler " +
                     "{} reducing loss scale to {}").format(loss_id,
                     loss_scaler.loss_scale()))
        if hasattr(opt._amp_stash, "all_fp32_from_fp16_params"):
            # Clear the master grads that wouldn't be zeroed by model.zero_grad()
            for param in opt._amp_stash.all_fp32_from_fp16_params:
                param.grad = None
        opt.step = opt_step
        opt._amp_stash.already_patched = False
    return skip_step
optimizer.step = patch_step(optimizer, loss_scaler, loss_id)
optimizer._amp_stash.already_patched = True
```
But PyTorch declaration of optimizer.step is this:
```python
def step(self, closure):
      r"""Performs a single optimization step (parameter update).

      Arguments:
          closure (callable): A closure that reevaluates the model and
              returns the loss. Optional for most optimizers.
      """
      raise NotImplementedError
```
This lead to TypeError in my case.
```
Traceback (most recent call last):
  File "/workspace/translation/train.py", line 563, in <module>
    distributed_main(args)
  File "/workspace/translation/distributed_train.py", line 57, in main
    single_process_main(args)
  File "/workspace/translation/train.py", line 136, in main
    train(args, trainer, task, epoch_itr, logger=watchdog)
  File "/workspace/translation/train.py", line 188, in train
    log_output = trainer.train_step(sample, update_params=True, last_step=(i == len(itr)-1))
  File "/workspace/translation/fairseq/trainer.py", line 188, in train_step
    self._opt()
  File "/workspace/translation/fairseq/trainer.py", line 315, in _opt
    self.optimizer.step()
  File "/workspace/translation/fairseq/optim/fairseq_optimizer.py", line 86, in step
    return self.optimizer.step(closure)
TypeError: skip_step() takes 0 positional arguments but 1 was given
```

**Comment by mcarilli** [comment]
Amp doesn't support closures, currently.  It needs visibility of the backward pass to implement loss scaling and gradient unscaling in the context manager.  Is there a reason you need to use a closure?

**Comment by jbaczek** [comment]
No, there isn't but I have optimizer wrapper in my project that I'm not allowed to change. It has default closure argument as None and it passes it explicitly to a torch optimizer and this causes an error. It would be great if AMP had the same API as torch.optim.optimizer not to fail in such cases. It can still print a warning or raise an error if closure is not None.

**Comment by mcarilli** [comment]
So you don't actually need to _use_ the closure, you just need a closure argument to be acceptable?

Allowing Amp to actually use a closure would be really tricky.  Allowing Amp to accept a None closure, but error out if the closure is not None, would be easy.

**Comment by jbaczek** [comment]
That's exactly what I need right now.

**Comment by mcarilli** [comment]
Hopefully fixed via https://github.com/NVIDIA/apex/commit/68c850d370fe18ad5aa4c4d1850692bccb9b26eb, reopen if you still have errors.
