### ISSUE TITLE
Issues with gcc when installing apex with CUDA support

### ISSUE THREAD

**Issue by fuzzyBatman** [NVIDIA/apex#372]
System config:
- OS: Fedora 30
- CUDA version: 10.2
- GPU: nVidia GTX1050(M)

Command:
```
python3 setup.py install --cuda_ext --cpp_ext --user
```

GCC compiler version > 7 is not supported, so I use gcc63 by creating symlinks as gcc63->gcc and g++63-> gcc. Result:

```
torch.__version__  =  1.2.0.dev20190622

Compiling cuda extensions with
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
from /usr/bin

running install
running bdist_egg
running egg_info
writing apex.egg-info/PKG-INFO
writing dependency_links to apex.egg-info/dependency_links.txt
writing top-level names to apex.egg-info/top_level.txt
reading manifest file 'apex.egg-info/SOURCES.txt'
writing manifest file 'apex.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
/home/fuzzybatman/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py:167: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using g++, and then you can also use
g++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
building 'amp_C' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/fuzzybatman/.local/lib/python3.7/site-packages/torch/include -I/home/fuzzybatman/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/fuzzybatman/.local/lib/python3.7/site-packages/torch/include/TH -I/home/fuzzybatman/.local/lib/python3.7/site-packages/torch/include/THC -I/usr/include/python3.7m -c csrc/amp_C_frontend.cpp -o build/temp.linux-x86_64-3.7/csrc/amp_C_frontend.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=amp_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
gcc: error: unrecognized command line option ‘-fstack-clash-protection’; did you mean ‘-fstack-protector’?
gcc: error: unrecognized command line option ‘-fcf-protection’; did you mean ‘-fstack-protector’?
error: command 'gcc' failed with exit status 1
```

How can I remove `-fstack-clash-protection` and `-fcf-protection`

**Comment by ptrblck** [comment]
Hi @fuzzyBatman,

I assume you are using CUDA10.0, since 10.1 is the latest version as far as I know.
Based on the [CUDA 10.0 installation guide](https://docs.nvidia.com/cuda/archive/10.0/cuda-installation-guide-linux/index.html) Fedora 27 should be supported with GCC 7.3.1.

Anyway, could you try to use the install command from our README:
```
$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```

**Comment by fuzzyBatman** [comment]
This is my result for `nvidia-smi`

```
Tue Jun 25 12:17:09 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.14       Driver Version: 430.14       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0    N/A /  N/A |      0MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Weird that it shows 10.2. However, in the package manager I see that it is 10.1

I ran 

```
pip3 install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" . --user
```

Result:

```
/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py:217: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Created temporary directory: /tmp/pip-ephem-wheel-cache-b5i3ithr
Created temporary directory: /tmp/pip-req-tracker-zu8dwqjd
Created requirements tracker '/tmp/pip-req-tracker-zu8dwqjd'
Created temporary directory: /tmp/pip-install-s85vb43e
Processing /home/satyajithj/Downloads/src/apex
  Created temporary directory: /tmp/pip-req-build-dhydatzr
  Added file:///home/satyajithj/Downloads/src/apex to build tracker '/tmp/pip-req-tracker-zu8dwqjd'
    Running setup.py (path:/tmp/pip-req-build-dhydatzr/setup.py) egg_info for package from file:///home/satyajithj/Downloads/src/apex
    Running command python setup.py egg_info
    torch.__version__  =  1.1.0
    running egg_info
    creating pip-egg-info/apex.egg-info
    writing pip-egg-info/apex.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/apex.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/apex.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-dhydatzr has version 0.1, which satisfies requirement apex==0.1 from file:///home/satyajithj/Downloads/src/apex
  Removed apex==0.1 from file:///home/satyajithj/Downloads/src/apex from build tracker '/tmp/pip-req-tracker-zu8dwqjd'
Installing collected packages: apex
  Created temporary directory: /tmp/pip-record-wv58cux6
  Running setup.py install for apex ...     Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-dhydatzr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-wv58cux6/install-record.txt --single-version-externally-managed --compile --user --prefix=
    torch.__version__  =  1.1.0

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2019 NVIDIA Corporation
    Built on Wed_Apr_24_19:10:27_PDT_2019
    Cuda compilation tools, release 10.1, V10.1.168
    from /usr/bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-dhydatzr/setup.py", line 64, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-dhydatzr/setup.py", line 54, in check_cuda_torch_binary_vs_bare_metal
        "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.0.130.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
error
Cleaning up...
  Removing source in /tmp/pip-req-build-dhydatzr
Removed build tracker '/tmp/pip-req-tracker-zu8dwqjd'
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-dhydatzr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-wv58cux6/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-req-build-dhydatzr/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 418, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/usr/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 949, in install
    spinner=spinner,
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 771, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-dhydatzr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-wv58cux6/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-req-build-dhydatzr/
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 11244
Analyzing links from page https://pypi.org/simple/pip/

```

**Comment by ptrblck** [comment]
Thanks for the information!
The CUDA 10.2 might be an issue with the new driver.
For the sake of debugging, could you remove the `(bare_metal_minor != torch_binary_minor)` check in [this line of code](https://github.com/NVIDIA/apex/blob/9ce80178cd5635d4e993023f1636c8178ebb8985/setup.py#L49) and try to install apex again?

**Comment by fuzzyBatman** [comment]
I am using gcc73 now and I get the same errors I reported initially.

```
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/satyajithj/.local/lib/python3.7/site-packages/torch/include -I/home/satyajithj/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/satyajithj/.local/lib/python3.7/site-packages/torch/include/TH -I/home/satyajithj/.local/lib/python3.7/site-packages/torch/include/THC -I/usr/include/python3.7m -c csrc/flatten_unflatten.cpp -o build/temp.linux-x86_64-3.7/csrc/flatten_unflatten.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=apex_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    gcc: error: unrecognized command line option ‘-fstack-clash-protection’; did you mean ‘-fstack-protector’?
    gcc: error: unrecognized command line option ‘-fcf-protection’; did you mean ‘-fstack-protector’?
    error: command 'gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-req-build-bh7p0o2q
Removed build tracker '/tmp/pip-req-tracker-f9o1pd6m'
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-bh7p0o2q/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-dn2vemlv/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-req-build-bh7p0o2q/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 418, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/usr/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 949, in install
    spinner=spinner,
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 771, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-bh7p0o2q/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-dn2vemlv/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-req-build-bh7p0o2q/
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 11244
Analyzing links from page https://pypi.org/simple/pip/
```

**Comment by fuzzyBatman** [comment]
I think these are issues with my GCC libs.

**Comment by cdes5804** [comment]
> Thanks for the information!
> The CUDA 10.2 might be an issue with the new driver.
> For the sake of debugging, could you remove the `(bare_metal_minor != torch_binary_minor)` check in [this line of code](https://github.com/NVIDIA/apex/blob/9ce80178cd5635d4e993023f1636c8178ebb8985/setup.py#L49) and try to install apex again?

Thanks! It totally helped!

**Comment by jveitchmichaelis** [comment]
I also had to use gcc-8 on the latest version of Ubuntu as CUDA 10.2 isn't compatible with 9. e.g. following:

https://askubuntu.com/questions/26498/how-to-choose-the-default-gcc-and-g-version
