### ISSUE TITLE
got error with install apex

### ISSUE THREAD

**Issue by stefensa** [NVIDIA/apex#386]
I installed Python-only build version of Apex before via
```bash
$ pip install -v --no-cache-dir ./
```
and I installed successfully.

Now I wanna install Apex with CUDA and C++ extensions via
```bash
$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

But I encounter an error after executing the above command,  can anybody give me some advice? Thanks a lot.

```
/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py:207: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Created temporary directory: /tmp/pip-ephem-wheel-cache-67yoi2kx
Created temporary directory: /tmp/pip-req-tracker-i9mxcckv
Created requirements tracker '/tmp/pip-req-tracker-i9mxcckv'
Created temporary directory: /tmp/pip-install-pj27q9jq
Looking in indexes: http://pypi.intra.yiducloud.cn/root/doubanio/+simple/
Processing /data/pengjie.ding/apex-master
  Created temporary directory: /tmp/pip-req-build-ypex69fn
  Added file:///data/pengjie.ding/apex-master to build tracker '/tmp/pip-req-tracker-i9mxcckv'
    Running setup.py (path:/tmp/pip-req-build-ypex69fn/setup.py) egg_info for package from file:///data/pengjie.ding/apex-master
    Running command python setup.py egg_info
    torch.__version__  =  1.1.0
    running egg_info
    creating pip-egg-info/apex.egg-info
    writing pip-egg-info/apex.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/apex.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/apex.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-ypex69fn has version 0.1, which satisfies requirement apex==0.1 from file:///data/pengjie.ding/apex-master
  Removed apex==0.1 from file:///data/pengjie.ding/apex-master from build tracker '/tmp/pip-req-tracker-i9mxcckv'
Installing collected packages: apex
  Created temporary directory: /tmp/pip-record-m_qcgysg
  Running setup.py install for apex ...     Running command /home/pengjie.ding/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ypex69fn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-m_qcgysg/install-record.txt --single-version-externally-managed --compile
    torch.__version__  =  1.1.0

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2018 NVIDIA Corporation
    Built on Sat_Aug_25_21:08:01_CDT_2018
    Cuda compilation tools, release 10.0, V10.0.130
    from /usr/local/cuda/bin

    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/apex
    copying apex/__init__.py -> build/lib.linux-x86_64-3.7/apex
    creating build/lib.linux-x86_64-3.7/apex/RNN
    copying apex/RNN/models.py -> build/lib.linux-x86_64-3.7/apex/RNN
    copying apex/RNN/RNNBackend.py -> build/lib.linux-x86_64-3.7/apex/RNN
    copying apex/RNN/cells.py -> build/lib.linux-x86_64-3.7/apex/RNN
    copying apex/RNN/__init__.py -> build/lib.linux-x86_64-3.7/apex/RNN
    creating build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/handle.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/scaler.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/frontend.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/amp.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/opt.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/_amp_state.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/__version__.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/_initialize.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/compat.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/_process_optimizer.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/utils.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/__init__.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/wrap.py -> build/lib.linux-x86_64-3.7/apex/amp
    copying apex/amp/rnn_compat.py -> build/lib.linux-x86_64-3.7/apex/amp
    creating build/lib.linux-x86_64-3.7/apex/normalization
    copying apex/normalization/fused_layer_norm.py -> build/lib.linux-x86_64-3.7/apex/normalization
    copying apex/normalization/__init__.py -> build/lib.linux-x86_64-3.7/apex/normalization
    creating build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/sync_batchnorm_kernel.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/optimized_sync_batchnorm.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/multiproc.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/sync_batchnorm.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/optimized_sync_batchnorm_kernel.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/distributed.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/LARC.py -> build/lib.linux-x86_64-3.7/apex/parallel
    copying apex/parallel/__init__.py -> build/lib.linux-x86_64-3.7/apex/parallel
    creating build/lib.linux-x86_64-3.7/apex/multi_tensor_apply
    copying apex/multi_tensor_apply/multi_tensor_apply.py -> build/lib.linux-x86_64-3.7/apex/multi_tensor_apply
    copying apex/multi_tensor_apply/__init__.py -> build/lib.linux-x86_64-3.7/apex/multi_tensor_apply
    creating build/lib.linux-x86_64-3.7/apex/fp16_utils
    copying apex/fp16_utils/fp16_optimizer.py -> build/lib.linux-x86_64-3.7/apex/fp16_utils
    copying apex/fp16_utils/fp16util.py -> build/lib.linux-x86_64-3.7/apex/fp16_utils
    copying apex/fp16_utils/loss_scaler.py -> build/lib.linux-x86_64-3.7/apex/fp16_utils
    copying apex/fp16_utils/__init__.py -> build/lib.linux-x86_64-3.7/apex/fp16_utils
    creating build/lib.linux-x86_64-3.7/apex/optimizers
    copying apex/optimizers/fp16_optimizer.py -> build/lib.linux-x86_64-3.7/apex/optimizers
    copying apex/optimizers/fused_adam.py -> build/lib.linux-x86_64-3.7/apex/optimizers
    copying apex/optimizers/__init__.py -> build/lib.linux-x86_64-3.7/apex/optimizers
    creating build/lib.linux-x86_64-3.7/apex/reparameterization
    copying apex/reparameterization/reparameterization.py -> build/lib.linux-x86_64-3.7/apex/reparameterization
    copying apex/reparameterization/weight_norm.py -> build/lib.linux-x86_64-3.7/apex/reparameterization
    copying apex/reparameterization/__init__.py -> build/lib.linux-x86_64-3.7/apex/reparameterization
    creating build/lib.linux-x86_64-3.7/apex/amp/lists
    copying apex/amp/lists/torch_overrides.py -> build/lib.linux-x86_64-3.7/apex/amp/lists
    copying apex/amp/lists/tensor_overrides.py -> build/lib.linux-x86_64-3.7/apex/amp/lists
    copying apex/amp/lists/functional_overrides.py -> build/lib.linux-x86_64-3.7/apex/amp/lists
    copying apex/amp/lists/__init__.py -> build/lib.linux-x86_64-3.7/apex/amp/lists
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ypex69fn/setup.py", line 119, in <module>
        cmdclass=cmdclass,
      File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 232, in build_extensions
        self._check_abi()
      File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 370, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 162, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 138, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/pengjie.ding/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/home/pengjie.ding/anaconda3/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
error
Cleaning up...
  Removing source in /tmp/pip-req-build-ypex69fn
Removed build tracker '/tmp/pip-req-tracker-i9mxcckv'
Command "/home/pengjie.ding/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ypex69fn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-m_qcgysg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-ypex69fn/
Exception information:
Traceback (most recent call last):
  File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 945, in install
    spinner=spinner,
  File "/home/pengjie.ding/anaconda3/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/pengjie.ding/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ypex69fn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-record-m_qcgysg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-ypex69fn/
```

**Comment by stefensa** [comment]
gcc version
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
```

pytorch:  1.1.0

```
CUDA Version 10.0.130
```

CUDNN
```
AJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 2
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
```

**Comment by ptrblck** [comment]
Hi @stefensa,

could you check the [CUDA installation guide for CUDA10.0](https://docs.nvidia.com/cuda/archive/10.0/cuda-installation-guide-linux/index.html#system-requirements) and check the required GCC version for your current OS?

**Comment by stefensa** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi ptrblck,    I’ve solved the problem by re-install my gcc, there’s something wrong with that. My classmates just made a incorrect operation to it, thanks for your kindly help and sorry for forgetting to close the question on GitHub.

        
    
     
    

    On 07/4/2019 20:29，ptrblck<notifications@github.com> wrote： 


Hi @stefensa,
could you check the CUDA installation guide for CUDA10.0 and check the required GCC version for your current OS?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


        font{
            line-height: 1.6;
        }
