### ISSUE TITLE
Torch.cat error

### ISSUE THREAD

**Issue by yimjinkyu1** [NVIDIA/apex#389]
I want to insert residual layer to neural net.
But I notice below bug in amp.

Out += torch.cat((shortcut, padding),1)

RuntimeError: Expected object of scalar type Half but got scalar type Float for sequence element 1 in sequence argument at position #1 ‘tensors’

**Comment by ptrblck** [comment]
Hi @yimjinkyu1,

could you post a small reproducible code snippet so that we can have a look?
This dummy example of a residual connection seems to work:
```python
import torch
import torch.nn as nn

from apex import amp

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv = nn.Conv2d(3, 3, 3, 1, 1)

    def forward(self, x):
        identity = x
        out = self.conv(x)
        out += identity

        return out

device = 'cuda'
model = MyModel().to(device)
x = torch.randn(1, 3, 24, 24, device=device)

model = amp.initialize(model, opt_level='O1')
output = model(x)
```

**Comment by mcarilli** [comment]
I think it's the cat call that's failing, not the residual connection.  Is that correct?
Cat is on the [sequence_casts list](https://github.com/NVIDIA/apex/blob/master/apex/amp/lists/torch_overrides.py#L110) so it should take all inputs and cast them to the widest type (in this case fp32).

**Comment by rafaelvalle** [comment]
Yes, for example:
```
Traceback (most recent call last):
  File "train.py", line 295, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 229, in train
    scaled_loss.backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/dcg-adlr-rafaelvalle-source.cosmos597/repos/tacotron2-gst/distributed.py", line 157, in allreduce_params
    coalesced = _flatten_dense_tensors(grads)
  File "/home/dcg-adlr-rafaelvalle-source.cosmos597/repos/tacotron2-gst/distributed.py", line 19, in _flatten_dense_tensors
    flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
RuntimeError: Expected object of scalar type Half but got scalar type Float for sequence element 3 in sequence argument at position #1 'tensors'
```
