### ISSUE TITLE
torch.save(model, 'best_model.pth') error with opt_level="O1"

### ISSUE THREAD

**Issue by ipScore** [NVIDIA/apex#415]
Traceback (most recent call last):
  File "/home/song/PycharmProjects/RSCDNet/train_amp.py", line 482, in <module>
    torch.save(model, '{}/best_model.pth'.format(model_save_dir))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 149, in _with_file_like
    return body(f)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 297, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <function interpolate at 0x7fcb09251f28>: it's not the same object as torch.nn.functional.interpolate

Process finished with exit code 1

**Comment by ipScore** [comment]
Hello, any kind advice for this issue?

**Comment by ptrblck** [comment]
Hi @ipScore,

could you post your model definition to reproduce this issue?

**Comment by ipScore** [comment]
> Hi @ipScore,
> 
> could you post your model definition to reproduce this issue?



I guess if I replace the **nn.functional.interpolate** with **nn.functional.interpolate()** , it will work well. Thank you for your reply.

```
class Interpolate(nn.Module):
    def __init__(self, size, mode):
        super(Interpolate, self).__init__()
        **self.interp = nn.functional.interpolate**
        self.size = size
        self.mode = mode

    def forward(self, x):
        x = self.interp(x, size=self.size, scale_factor=2, mode=self.mode, align_corners=None)
        return x
```

**Comment by seongwook-ham** [comment]
do not save model save model.state_dict()
