### ISSUE TITLE
NCCL error in: ../torch/lib/c10d/../c10d/NCCLUtils.hpp:29, unhandled cuda error

### ISSUE THREAD

**Issue by vsuhasm** [NVIDIA/apex#427]
My script works with --op-level O0 and O1, but not with the other options. The following is the error log.

```Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Learning rate: 0.1
THCudaCheck FAIL file=../aten/src/THC/THCCachingHostAllocator.cpp line=278 error=74 : misaligned address
Traceback (most recent call last):
  File "run_search.py", line 103, in <module>
    main(get_args())
  File "run_search.py", line 59, in main
    loss = searcher.train(epoch)
  File "/mnt/efs/PLNAS/trainer.py", line 220, in train
    output = self.model(input, gates)
  File "/home/ubuntu/anaconda3/envs/pytorchs_py363/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorchs_py363/lib/python3.6/site-packages/apex/parallel/distributed.py", line 476, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorchs_py363/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorchs_py363/lib/python3.6/site-packages/apex/amp/_initialize.py", line 204, in new_fwd
    **applier(kwargs, input_caster))
  File "/mnt/efs/PLNAS/proxyless_nas/nas_modules.py", line 207, in forward
    x = self.first_conv(x)
  File "/home/ubuntu/anaconda3/envs/pytorchs_py363/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/efs/PLNAS/proxyless_nas/layers.py", line 95, in forward
    x = self.weight_call(x)
  File "/mnt/efs/PLNAS/proxyless_nas/layers.py", line 184, in weight_call
    x = self.conv(x)
  File "/home/ubuntu/anaconda3/envs/pytorchs_py363/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorchs_py363/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/ubuntu/anaconda3/envs/pytorchs_py363/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: ../torch/lib/c10d/../c10d/NCCLUtils.hpp:29, unhandled cuda error```

The following is the output of pip freeze.
```
absl-py==0.7.1
apex==0.1
certifi==2019.6.16
cffi==1.12.3
future==0.17.1
grpcio==1.22.0
Markdown==3.1.1
mkl-fft==1.0.12
mkl-random==1.0.2
numpy==1.16.4
Pillow==6.1.0
protobuf==3.9.1
pycparser==2.19
PyYAML==5.1.1
six==1.12.0
tb-nightly==1.15.0a20190806
torch==1.3.0a0+5ec1c29
torchvision==0.5.0a0+8635be9
typing==3.6.4
Werkzeug==0.15.5
```

Any solutions foor this issue?

Thanks!

**Comment by ptrblck** [comment]
Hi @vsuhasm,

it seems the actual error might be:
```
THCudaCheck FAIL file=../aten/src/THC/THCCachingHostAllocator.cpp line=278 error=74 : misaligned address
```

Do you have a code snippet to reproduce this issue?

**Comment by vsuhasm** [comment]
Hi @ptrblck I'm reusing most of the code here: https://github.com/mit-han-lab/ProxylessNAS/tree/master/proxyless_nas and trying to reimplement using mixed precision training.

Another thing I noticed is that I get the same error when I do model.half() and cast inputs to half precision as well.

**Comment by ptrblck** [comment]
Thanks for the information about `model.half()`!
Which model should I use to get the same error?

**Comment by vsuhasm** [comment]
Hi @ptrblck I seem to have figured out the issue. I passed a `torch.float16` tensor to torch.multinomial which resulted in the misaligned address error. I casted the tensor explicitly using .float() and it got rid of the issue.

However, I ran into another issue where my code hangs when computing `optimizer.step()` after `scaled_loss.backward()`. This only happens when batchnorm weights are stored in fp32. Any thoughts? My code works fine for opt levels O0, O1 and O3 (with keep-batchnorm-fp32 = True).

**Comment by ptrblck** [comment]
Do you have a code to reproduce the issue regarding fp16 inputs to `torch.multinomial`?
This code seems to work:
```python
weights = torch.empty(10, device='cuda').uniform_()
torch.multinomial(weights, num_samples=5)
torch.multinomial(weights.half(), num_samples=5)
```

Do you see any activity on the GPU during this hang?
If not, could you try to isolate the issue and provide a code snippet to reproduce as we would like to debug it?

Best,
ptrblck
