### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by PharaunMizzrym** [NVIDIA/apex#467]
Hello
I'm having problems to import apex to my python project.
I have installed the module following the instructions.

`$ pip3 install -v --no-cache-dir ./ --user`

Then when I try to import amp from apex module it raises the next error:

`Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from apex import amp
  File "/home/pharaun/.local/lib/python3.6/site-packages/apex/__init__.py", line 6, in <module>
    from . import amp
  File "/home/pharaun/.local/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/home/pharaun/.local/lib/python3.6/site-packages/apex/amp/amp.py", line 5, in <module>
    from .frontend import *
  File "/home/pharaun/.local/lib/python3.6/site-packages/apex/amp/frontend.py", line 2, in <module>
    from ._initialize import _initialize
  File "/home/pharaun/.local/lib/python3.6/site-packages/apex/amp/_initialize.py", line 9, in <module>
    from ._process_optimizer import _process_optimizer
  File "/home/pharaun/.local/lib/python3.6/site-packages/apex/amp/_process_optimizer.py", line 6, in <module>
    from ..optimizers import FusedSGD
  File "/home/pharaun/.local/lib/python3.6/site-packages/apex/optimizers/__init__.py", line 2, in <module>
    from .fused_adam import FusedAdam
  File "/home/pharaun/.local/lib/python3.6/site-packages/apex/optimizers/fused_adam.py", line 3, in <module>
    from amp_C import multi_tensor_adam
ModuleNotFoundError: No module named 'amp_C'
`
Did some one have the same issue? I tried to search it but I didn't find anything.

Thanks!

**Comment by ptrblck** [comment]
Hi @PharaunMizzrym,

thanks for raising this issue.
It looks like this `import` was added in [this PR](https://github.com/NVIDIA/apex/commit/007c59472a94c69683b9315ee6844bcde1b15997).

CC @FDecaYed, @mcarilli

**Comment by quanpn90** [comment]
I manually commented the 'import' and it solved the problem for me. A hacky quick fix when you need to wait for the official update.

**Comment by PharaunMizzrym** [comment]
Hi @ptrblck @quanpn90 
I commented the import as @quanpn90 says and now is working for me.

Thanks for the help. I was driving me a little crazy since a month ago the code was working in my old computer and when I finish all the configuration in the new one I didn't work.

Regards and thanks for your quick answer.

**Comment by FDecaYed** [comment]
@ptrblck @mcarilli my bad. I cleaned up fused novograd/lamb before final push but forgot to do the same for adam. I'll push another change to fix
- import error when not building with extensions
- making separate list for fp16/32

**Comment by ptrblck** [comment]
Thanks @FDecaYed! :)

**Comment by FDecaYed** [comment]
> Thanks @FDecaYed! :)

https://github.com/NVIDIA/apex/pull/469
