### ISSUE TITLE
RuntimeError: reduce failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by wunei2016** [NVIDIA/apex#471]
It's the first time to try Apex in pytorch, several minor problems I've met were solved when I run my code. But when I think it was successful after running several minutes normally，the error below occurred.

> /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [8,0,0], thread: [94,0,0] Assertion `input >= 0. && input <= 1.` failed.
> /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [8,0,0], thread: [95,0,0] Assertion `input >= 0. && input <= 1.` failed.
> /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THCUNN/BCECriterion.cu:42: Acctype bce_functor<Dtype, Acctype>::operator()(Tuple) [with Tuple = thrust::detail::tuple_of_iterator_references<thrust::device_reference<float>, thrust::device_reference<float>, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>, Dtype = float, Acctype = float]: block: [8,0,0], thread: [96,0,0] Assertion `input >= 0. && input <= 1.` failed.

> Traceback (most recent call last):
> a = self.bce_loss(y_true, y_pred)
>   File "/home/sensetime/anaconda2/envs/pytorch1.1.0-py3-gdal/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/sensetime/anaconda2/envs/pytorch1.1.0-py3-gdal/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 512, in forward
>     return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
>   File "/home/sensetime/anaconda2/envs/pytorch1.1.0-py3-gdal/lib/python3.6/site-packages/apex/amp/wrap.py", line 129, in wrapper
>     return orig_fn(*args, **kwargs)
>   File "/home/sensetime/anaconda2/envs/pytorch1.1.0-py3-gdal/lib/python3.6/site-packages/torch/nn/functional.py", line 2113, in binary_cross_entropy
>     input, target, weight, reduction_enum)
> RuntimeError: reduce failed to synchronize: device-side assert triggered

How to solve them?

**Comment by ptrblck** [comment]
Hi @wunei2016, 

the actual error is the `Assertion input >= 0. && input <= 1. failed.` thrown in `nn.BCELoss`.
Make sure to pass a target with values in the range `[0, 1]`.

This code raises the same error:
```python
criterion = nn.BCELoss()

output = torch.tensor([[1.]], requires_grad=True)
target = torch.tensor([[1.]])
loss = criterion(output, target)  # works

output = output + 0.1
loss = criterion(output, target)  # fails
> RuntimeError: Assertion `x >= 0. && x <= 1.' failed. input value should be between 0~1, but got 1.100000 
```

**Comment by wunei2016** [comment]
Hi @ptrblck,

I used `sigmoid` before compute loss. so, the output should be` >= 0 and <= 1`. 
The error occurred after several epochs. it means that it ran well before error. so, the target is in the range `[0, 1]`. 

This code raises the same error too:

```
criterion = nn.BCELoss()

output = torch.tensor([float('nan')], requires_grad=True)
target = torch.tensor([0.5])
loss = criterion(output, target)
>RuntimeError: Assertion `x >= 0. && x <= 1.' failed. input value should be between 0~1, but got nan at c:\new-builder_2\win-wheel\pytorch\aten\src\thnn\generic/BCECriterion.c:62
```

so, I think the output become `nan` value in some layers. Is that possible to happen?

**Comment by ptrblck** [comment]
Thanks for the additional information!
That might be the case.
Could you run the code with
```python
torch.autograd.set_detect_anomaly(True)
```
at the beginning of the script?
This should yield a stack trace pointing to the operation which created the invalid value.

**Comment by cherepanovic** [comment]
very similar situation [here my bug post](https://github.com/pytorch/pytorch/issues/36647)

The sigmoid function will be applied on the values so that they are in the range between 0 and 1 and I get the same error.
