### ISSUE TITLE
Apex failing to import name rnn_compat

### ISSUE THREAD

**Issue by Tdogb** [NVIDIA/apex#496]
Please let me know if you need more details but I am on ubuntu 16.04 and I am getting this error.

`Python 2.7.12 (default, Aug 22 2019, 16:36:40) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import apex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "apex/__init__.py", line 6, in <module>
    from . import amp
  File "apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "apex/amp/amp.py", line 1, in <module>
    from . import compat, rnn_compat, utils, wrap
  File "apex/amp/rnn_compat.py", line 1, in <module>
    from . import utils, wrap
  File "apex/amp/wrap.py", line 4, in <module>
    from . import rnn_compat
ImportError: cannot import name rnn_compat`

**Comment by ptrblck** [comment]
Hi @Tdogb,

thanks for raising this issue.
Would [this suggestion](https://github.com/NVIDIA/apex/issues/299#issuecomment-531574028) work for you?
If so, we should fix it in the current master.
