### ISSUE TITLE
:If you _really_ know what you are doing, you can disable this warning by passing allow_banned=True to `amp.init()`.

### ISSUE THREAD

**Issue by molyswu** [NVIDIA/apex#504]
enabled                : True
[1,1]<stdout>:loss_scale             : dynamic
[1,1]<stdout>:master_weights         : None
[1,1]<stdout>:patch_torch_functions  : True
[1,1]<stdout>:opt_level              : O1
[1,1]<stdout>:keep_batchnorm_fp32    : None
[1,1]<stdout>:cast_model_type        : None
[1,1]<stdout>:Processing user overrides (additional kwargs that are not None)...
[1,1]<stdout>:After processing overrides, optimization options are:
[1,1]<stdout>:enabled                : True
[1,1]<stdout>:loss_scale             : dynamic
[1,1]<stdout>:master_weights         : None
[1,1]<stdout>:patch_torch_functions  : True
[1,1]<stdout>:opt_level              : O1
[1,1]<stdout>:keep_batchnorm_fp32    : None
[1,1]<stdout>:cast_model_type        : None
[1,0]<stdout>:
[1,0]<stdout>:
[1,0]<stdout>:epoch: 0,batch: 0[1,0]<stdout>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_1.py", line 187, in <module>
[1,0]<stderr>:    loss, outputs = model(imgs, targets)
[1,0]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
[1,0]<stderr>:    result = self.forward(*input, **kwargs)
[1,0]<stderr>:  File "/media/ai/sdc1/tools/horovod_study/yolov3-pytoch/PyTorch-YOLOv3/models.py", line 260, in forward
[1,0]<stderr>:    x, layer_loss = module[0](x, targets, img_dim)
[1,0]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
[1,0]<stderr>:    result = self.forward(*input, **kwargs)
[1,0]<stderr>:  File "/media/ai/sdc1/tools/horovod_study/yolov3-pytoch/PyTorch-YOLOv3/models.py", line 197, in forward
[1,0]<stderr>:    loss_conf_obj = self.bce_loss(pred_conf[obj_mask], tconf[obj_mask])
[1,0]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
[1,0]<stderr>:    result = self.forward(*input, **kwargs)
[1,0]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/loss.py", line 498, in forward
[1,0]<stderr>:    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
[1,0]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/apex/amp/wrap.py", line 124, in wrapper
[1,0]<stderr>:    raise NotImplementedError(custom_err_msg)
[1,0]<stderr>:NotImplementedError: 
[1,0]<stderr>:amp does not work out-of-the-box with `F.binary_cross_entropy` or `torch.nn.BCELoss.` It requires that the output of the previous function be already a FloatTensor. 
[1,0]<stderr>:
[1,0]<stderr>:Most models have a Sigmoid right before BCELoss. In that case, you can use
[1,0]<stderr>:    torch.nn.BCEWithLogitsLoss
[1,0]<stderr>:to combine Sigmoid+BCELoss into a single layer that is compatible with amp.
[1,0]<stderr>:Another option is to add
[1,0]<stderr>:    amp.register_float_function(torch, 'sigmoid')
[1,0]<stderr>:before calling `amp.init()`.
[1,0]<stderr>:If you _really_ know what you are doing, you can disable this warning by passing allow_banned=True to `amp.init()`.
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "train_1.py", line 187, in <module>
[1,1]<stderr>:    loss, outputs = model(imgs, targets)
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
[1,1]<stderr>:    result = self.forward(*input, **kwargs)
[1,1]<stderr>:  File "/media/ai/sdc1/tools/horovod_study/yolov3-pytoch/PyTorch-YOLOv3/models.py", line 260, in forward
[1,1]<stderr>:    x, layer_loss = module[0](x, targets, img_dim)
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
[1,1]<stderr>:    result = self.forward(*input, **kwargs)
[1,1]<stderr>:  File "/media/ai/sdc1/tools/horovod_study/yolov3-pytoch/PyTorch-YOLOv3/models.py", line 197, in forward
[1,1]<stderr>:    loss_conf_obj = self.bce_loss(pred_conf[obj_mask], tconf[obj_mask])
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 547, in __call__
[1,1]<stderr>:    result = self.forward(*input, **kwargs)
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/loss.py", line 498, in forward
[1,1]<stderr>:    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
[1,1]<stderr>:  File "/usr/local/lib/python3.5/dist-packages/apex/amp/wrap.py", line 124, in wrapper
[1,1]<stderr>:    raise NotImplementedError(custom_err_msg)
[1,1]<stderr>:NotImplementedError: 
[1,1]<stderr>:amp does not work out-of-the-box with `F.binary_cross_entropy` or `torch.nn.BCELoss.` It requires that the output of the previous function be already a FloatTensor. 
[1,1]<stderr>:
[1,1]<stderr>:Most models have a Sigmoid right before BCELoss. In that case, you can use
[1,1]<stderr>:    torch.nn.BCEWithLogitsLoss
[1,1]<stderr>:to combine Sigmoid+BCELoss into a single layer that is compatible with amp.
[1,1]<stderr>:Another option is to add
[1,1]<stderr>:    amp.register_float_function(torch, 'sigmoid')
[1,1]<stderr>:before calling `amp.init()`.
[1,1]<stderr>:If you _really_ know what you are doing, you can disable this warning by passing allow_banned=True to `amp.init()`.

**Comment by ptrblck** [comment]
Double post from [here](https://github.com/NVIDIA/apex/issues/506#issuecomment-535442857).
As the error message suggests, you could e.g. change the criterion to `nn.BCEWithLogitsLoss` and remove the `sigmoid`, register the `sigmoid` as a float function, or disable the warning.
