### ISSUE TITLE
'function' object has no attribute '__self__' in Pytorch 1.3

### ISSUE THREAD

**Issue by aronhoff** [NVIDIA/apex#552]
After upgrading to Pytorch 1.3.0, my training script crashes with `AttributeError`. Relevant lines from the stack:
```
Traceback (most recent call last):
...
  File "/usr/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 299, in __init__
    super(CosineAnnealingLR, self).__init__(optimizer, last_epoch)
  File "/usr/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 58, in __init__
    self.optimizer.step = with_counter(self.optimizer.step)
  File "/usr/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 40, in with_counter
    instance_ref = weakref.ref(method.__self__)
AttributeError: 'function' object has no attribute '__self__'
```

The `step` method of the Amp optimizer is simply patched with a function, but is not made a method again in https://github.com/NVIDIA/apex/blob/088985936518be7e25795a30d8ab33affa9db6ed/apex/amp/_initialize.py#L235-L245, therefore it does not have a `__self__`.

**Comment by mcarilli** [comment]
That makes sense.  I use MethodType elsewhere but forgot to do it here.

**Comment by vinhngx** [comment]
I encountered the same issue in NGC pytorch 19.10 when implementing APEX for pytorch vision
detection library. Should I try the latest apex from source?

**Comment by mcarilli** [comment]
Yes, the fix was merged.  If you use a version more recent than https://github.com/NVIDIA/apex/pull/553 please reopen.

**Comment by kivechang** [comment]
Pytorch 1.4.0  has the same problem 

  File "D:\soft\anaconda3\lib\site-packages\torch\optim\lr_scheduler.py", line 337, in __init__
    super(StepLR, self).__init__(optimizer, last_epoch)

  File "D:\soft\anaconda3\lib\site-packages\torch\optim\lr_scheduler.py", line 73, in __init__
    self.optimizer.step = with_counter(self.optimizer.step)

  File "D:\soft\anaconda3\lib\site-packages\torch\optim\lr_scheduler.py", line 55, in with_counter
    instance_ref = weakref.ref(method.__self__)
AttributeError: 'function' object has no attribute '__self__'
