### ISSUE TITLE
RuntimeError: "GeluCUDAKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by BramVanroy** [NVIDIA/apex#555]
PyTorch 1.2 introduced the `gelu` activation function. Unfortunately, this leads to terminal errors when using with AMP.

Trace (`self.activation` is `gelu`): 

```
Traceback (most recent call last):
  File "predict.py", line 282, in <module>
    predictor.predict()
  File "predict.py", line 74, in predict
    fig = trainer.train()
  File "/home/bram/Python/projects/transformer-classifiers/transformer_classifiers/TransformerTrainer.py", line 232, in train
    self._process('train', epoch)
  File "/home/bram/Python/projects/transformer-classifiers/transformer_classifiers/TransformerTrainer.py", line 124, in _process
    preds = self.model(input_ids, attention_mask=input_mask)
  File "/home/bram/.local/share/virtualenvs/transformer-classifiers-x27iJBv7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bram/.local/share/virtualenvs/transformer-classifiers-x27iJBv7/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/bram/.local/share/virtualenvs/transformer-classifiers-x27iJBv7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bram/Python/projects/transformer-classifiers/transformer_classifiers/models.py", line 140, in forward
    cls_output = self.activation(cls_output)
  File "/home/bram/.local/share/virtualenvs/transformer-classifiers-x27iJBv7/lib/python3.7/site-packages/torch/nn/functional.py", line 1126, in gelu
    return torch._C._nn.gelu(input)
RuntimeError: "GeluCUDAKernelImpl" not implemented for 'Half'
```

**Comment by mcarilli** [comment]
Try adding `'gelu',` to the fp32 list [here](https://github.com/NVIDIA/apex/blob/master/apex/amp/lists/functional_overrides.py#L40) and
```
$ pip uninstall apex # repeat if necessary
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
If that works I will commit.

**Comment by BramVanroy** [comment]
It works indeed, thanks.

Is that the place for user functions as well? I have a few of my own activation functions that may benefit from this. Or is there a way to add custom functions on runtime?

**Comment by mcarilli** [comment]
That's still described in the README here https://github.com/NVIDIA/apex/blob/master/apex/amp/README.md#annotating-user-functions
Probably no easier than just calling .float() on inputs in your custom function's definition though.

**Comment by BramVanroy** [comment]
I just tested this on a Linux machine and it did not work (unexpected), so I'll need to check my Windows machine tonight to see if I the change is unsuccessful after all.

**Comment by yuchenlin** [comment]
> That's still described in the README here https://github.com/NVIDIA/apex/blob/master/apex/amp/README.md#annotating-user-functions
> Probably no easier than just calling .float() on inputs in your custom function's definition though.

Hi I tried reinstall but still has this issue in pytorch 1.0.0~1.4.0

**Comment by h-peng17** [comment]
> > That's still described in the README here https://github.com/NVIDIA/apex/blob/master/apex/amp/README.md#annotating-user-functions
> > Probably no easier than just calling .float() on inputs in your custom function's definition though.
> 
> Hi I tried reinstall but still has this issue in pytorch 1.0.0~1.4.0

I met this issue too in pytorch 1.0.0~1.4.0

**Comment by yuchenlin** [comment]
@h-peng17  i finally fixed this by installing the pytroch nightly (1.5.0+)
