### ISSUE TITLE
loss.backward() in apex.amp ?

### ISSUE THREAD

**Issue by LightToYang** [NVIDIA/apex#56]
As the example for handling multiple backward passes :

```
amp_handle = amp.init()
optimizer = amp_handle.wrap_optimizer(optimizer, num_loss=2)
# ...
optimizer.zero_grad()
loss1 = ComputeLoss1(model)
with optimizer.scale_loss(loss1) as scaled_loss:
    scaled_loss.backward()
# ...
loss2 = ComputeLoss2(model)
with optimizer.scale_loss(loss2) as scaled_loss:
    scaled_loss.backward()
# ...
optimizer.step()
```

Can we first add losses together and then do the wrapper?

```
loss = loss1 + loss2
with optimizer.scale_loss(loss) as scaled_loss:
    scaled_loss.backward()
```

**Comment by mcarilli** [comment]
I believe that would be mathematically equivalent, as long as amp uses the same loss scale for both.
@carlc-nv, is this ok?

**Comment by wassryan** [comment]
hi, guys, I am trying using two loss to handle only one model with one optimizer, and the second loss shares sub-graph in first loss, so I use retain_graph=True, but that didn't work, can you help me figure out what's wrong with my code?
@mcarilli 
`optimizer = torch.optim.SGD(...)
optimizer = LARC(optimizer=optimizer, trust_coefficient=0.001, clip=False)
model, optimizer = amp.initialize(model, optimizer, num_losses=2, opt_level='O1')
model = apex.parallel.DistributedDataParallel(model)

optimizer.zero_grad()
with amp.scale_loss(loss1, optimizer, loss_id=0) as scaled_loss:
        scaled_loss.backward(retain_graph=True)
with amp.scale_loss(loss2, optimizer, loss_id=1) as scaled_loss:
        scaled_loss.backward() <------ line 396
optimizer.step()
`

and the error log
`
Traceback (most recent call last):
  File "/home/xx/venv/py35torch1.4apex/lib/python3.5/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/xx/proto/train_pplv4.py", line 297, in main_worker
    train(train_loader, model, optimizer, epoch, args, criterion_list)
  File "/home/xx/proto/train_pplv4.py", line 396, in train
    scaled_loss.backward()
  File "/home/xx/venv/py35torch1.4apex/lib/python3.5/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/xx/venv/py35torch1.4apex/lib/python3.5/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/xx/venv/py35torch1.4apex/lib/python3.5/site-packages/apex/parallel/distributed.py", line 400, in allreduce_hook
    self.comm_ready_buckets(param)
  File "/home/xx/venv/py35torch1.4apex/lib/python3.5/site-packages/apex/parallel/distributed.py", line 519, in comm_ready_buckets
    bucket_idx, bucket_loc = self.param_id_to_bucket[id(param)]
KeyError: 140642903453560
`

**Comment by rgsousa88** [comment]
Hi, @wassryan have you found a solution for this error? I'm facing it now but I can't find a solution... Thanks in advance.
