### ISSUE TITLE
_register_state_dict_hook is not supported on ScriptModules Pytorch 1.3

### ISSUE THREAD

**Issue by kefirski** [NVIDIA/apex#561]
I had used apex library with PyTorch `1.2` and everything was fine.

Here is information of my build

```
PyTorch version: 1.2.0a0+8554416
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

CUDA runtime version: 10.0.130
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2

[pip3] torch==1.2.0a0+8554416
[conda] magma-cuda100             2.5.0                         1    soumith
```

But I get the error on more recent build with PyTorch `1.3`

```
Traceback (most recent call last):
  File "train.py", line 85, in <module>
    model, optimizer = amp.initialize(model, optimizer, opt_level=args.opt_level)
  File "/opt/conda/lib/python3.7/site-packages/apex/amp/frontend.py", line 358, in initialize
    return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
  File "/opt/conda/lib/python3.7/site-packages/apex/amp/_initialize.py", line 209, in _initialize
    module._register_state_dict_hook(O2StateDictHook(functools.partial(to_type, torch.float32)))
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1689, in fail
    raise RuntimeError(name + " is not supported on ScriptModules")
RuntimeError: _register_state_dict_hook is not supported on ScriptModules
```

System info:
```
PyTorch version: 1.3.0a0+de394b6
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

CUDA runtime version: 10.1.243

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4

Versions of relevant libraries:
[pip3] torch==1.3.0a0+de394b6
[conda] magma-cuda101             2.5.1                         1    pytorch
```

**Comment by mcarilli** [comment]
Apex does not support scripted modules.  My primary task right now is integrating mixed precision into upstream.  I'm working on the eager mode integration and @jjsjann123 is working on JIT support.
Plan for gradient scaling and autocasting:  https://github.com/pytorch/pytorch/issues/25081
PR for gradient scaling component:  https://github.com/pytorch/pytorch/pull/26512 (fairly well reviewed now, should be merged soon)
Plan for jit support:  https://github.com/pytorch/pytorch/issues/25387 (@jjsjann123 )
