### ISSUE TITLE
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'

### ISSUE THREAD

**Issue by bruce1408** [NVIDIA/apex#578]
when i install apex, error as follows https://github.com/NVIDIA/apex/issues/570, and i install apex
```
pip install -V --no-cache-dir ./
``` 
and there was an error **ModuleNotFoundError: No module named 'fused_layer_norm_cuda'**

env:
ubuntu 16.04
apex==0.1
torch==1.3.1
GPU Nvidia 2080 Ti

nvcc -V 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
gcc -V
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.11' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 
```

```
Traceback (most recent call last):
  File "/home/bruce/PycharmProjects/CAIL2019/train_bert.py", line 91, in <module>
    model = BertForTripletNet.from_pretrained(BERT_MODEL_PATH)
  File "/home/bruce/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 536, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/bruce/PycharmProjects/CAIL2019/models/net2.py", line 10, in __init__
    self.bert = BertModel(config)
  File "/home/bruce/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_transformers/modeling_bert.py", line 651, in __init__
    self.embeddings = BertEmbeddings(config)
  File "/home/bruce/anaconda3/envs/pytorch/lib/python3.6/site-packages/pytorch_transformers/modeling_bert.py", line 240, in __init__
    self.LayerNorm = BertLayerNorm(config.hidden_size, eps=config.layer_norm_eps)
  File "/home/bruce/anaconda3/envs/pytorch/lib/python3.6/site-packages/apex/normalization/fused_layer_norm.py", line 133, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/home/bruce/anaconda3/envs/pytorch/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
```

**Comment by stellaywu** [comment]
got the same error, tried the solution here https://github.com/NVIDIA/apex/issues/156#issuecomment-465301976
But while install got another error 
```ERROR: Command "/anaconda3/envs/venv/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2x/0hqrql092vgdwyflw74v45100000gn/T/pip-req-build-g7xbiggp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /private/var/folders/2x/0hqrql092vgdwyflw74v45100000gn/T/pip-record-vhe2uw4_/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/2x/0hqrql092vgdwyflw74v45100000gn/T/pip-req-build-g7xbiggp/
```

I have only CPU, could that be the reason?

**Comment by ptrblck** [comment]
@bruce1408 `fused_layer_norm_cuda` uses CUDA extensions, so you should build `apex` with these extensions as described [here](https://github.com/NVIDIA/apex#linux).

@stellaywu `apex` needs a GPU to run, as a lot of FP16 operations are not implemented on CPU (and IIRC do not yield any speedup).
