### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by taylor4712** [NVIDIA/apex#582]
`$ git clone apex

$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext"`

Hello! Follow the above installation process, I can't install successfully. what should I do？Thank you for your help.

`Processing /home/taylor
/apex
  Running setup.py (path:/tmp/pip-k39v50vg-build/setup.py) egg_info for package from file:///home/taylor/apex
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-k39v50vg-build/setup.py", line 5, in <module>
        from pip._internal import main as pipmain
    ModuleNotFoundError: No module named 'pip._internal'
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-k39v50vg-build/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-k39v50vg-build/`

I already set python 3.6 as default.

**Comment by cliffwoolley** [comment]
> import torch ImportError: No module named torch

It looks like you don't have PyTorch installed?

**Comment by taylor4712** [comment]
I have installed pytorch
