### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by akshayc11** [NVIDIA/apex#583]
Hi, I tried installing apex using the commands specified in the README.md, but I am getting the following error:
```bash
Skipping wheel build for apex, due to binaries being disabled for it.
Installing collected packages: apex
  Created temporary directory: /tmp/pip-record-21lduwph
    Running command /home/akshay/dev/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-gee_f6bx/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-gee_f6bx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-21lduwph/install-record.txt --single-version-externally-managed --compile --install-headers /home/akshay/dev/include/site/python3.6/apex
    torch.__version__  =  1.2.0
    /tmp/pip-req-build-gee_f6bx/setup.py:43: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2019 NVIDIA Corporation
    Built on Sun_Jul_28_19:07:16_PDT_2019
    Cuda compilation tools, release 10.1, V10.1.243
    from /usr/local/cuda/bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-gee_f6bx/setup.py", line 100, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-gee_f6bx/setup.py", line 77, in check_cuda_torch_binary_vs_bare_metal
        "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.0.130.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
    Running setup.py install for apex ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-gee_f6bx
Removed build tracker '/tmp/pip-req-tracker-b0v03mjk'
ERROR: Command errored out with exit status 1: /home/akshay/dev/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-gee_f6bx/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-gee_f6bx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-21lduwph/install-record.txt --single-version-externally-managed --compile --install-headers /home/akshay/dev/include/site/python3.6/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/akshay/dev/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/home/akshay/dev/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/home/akshay/dev/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/home/akshay/dev/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 888, in install
    cwd=self.unpacked_source_directory,
  File "/home/akshay/dev/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 275, in runner
    spinner=spinner,
  File "/home/akshay/dev/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/akshay/dev/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-gee_f6bx/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-gee_f6bx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-21lduwph/install-record.txt --single-version-externally-managed --compile --install-headers /home/akshay/dev/include/site/python3.6/apex Check the logs for full command output.
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Found index url https://pypi.org/simple
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 200 12329
Analyzing links from page https://pypi.org/simple/pip/
...
```
OS: Ubuntu 18.04
Python 3.6.8
CUDA 10.1

I am doing the installation in a virtual environment, which has torch, torchvision, tensorflow-gpu all installed within. Is there anything I am missing? Thanks

**Comment by akshayc11** [comment]
Sorry, On paying more attention to the error, it looks like I had the wrong version of torch (compiled with cuda10.0 reinstalling that solved the issue)
