### ISSUE TITLE
BUG: Opt-level 01 not working

### ISSUE THREAD

**Issue by mayoore** [NVIDIA/apex#586]
I have PyTorch v1.2 and Apex installed. I was able to get opt_level 00 and 03 working. But, opt_level 01 option isn't working. From the debugging I've done, looks like it's crashing at `    prefetcher = data_prefetcher(train_loader)`. However, there aren't any error messages to help with debugging. 

OUTPUT:

$ python main_amp.py -a resnet50 --b 224 --workers 4 --opt-level O1 data 
opt_level = O1
keep_batchnorm_fp32 = None <class 'NoneType'>
loss_scale = None <class 'NoneType'>

CUDNN VERSION: 7602

=> creating model 'resnet50'
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic

**Comment by mcarilli** [comment]
Does it work if you don't use the prefetcher (ie pass the DataLoader directly to the per-epoch training loop)?

**Comment by mayoore** [comment]
I get this runtime error when I use DataLoader. Would it work in FP16 opt_level O1 mode if I change `image = image.float()`?

Traceback (most recent call last):
  File "main_amp.py", line 552, in <module>
    main()
  File "main_amp.py", line 243, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main_amp.py", line 352, in train
    output = model(input)
  File "/mnt/nfs/nfsshare/user_homes/mayoore/anaconda3/envs/apex/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/nfs/nfsshare/user_homes/mayoore/anaconda3/envs/apex/lib/python3.6/site-packages/torchvision/models/resnet.py", line 196, in forward
    x = self.conv1(x)
  File "/mnt/nfs/nfsshare/user_homes/mayoore/anaconda3/envs/apex/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/nfs/nfsshare/user_homes/mayoore/anaconda3/envs/apex/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/mnt/nfs/nfsshare/user_homes/mayoore/anaconda3/envs/apex/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
  File "/mnt/nfs/nfsshare/user_homes/mayoore/anaconda3/envs/apex/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: _thnn_conv2d_forward not supported on CPUType for Byte

**Comment by mcarilli** [comment]
You're running on the CPU.  You would need to call .cuda() on inputs and targets.
