### ISSUE TITLE
Bilinear RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'mat2'

### ISSUE THREAD

**Issue by adihaviv** [NVIDIA/apex#596]
I am getting the same issue as #302 . can you help? 

i'm using the latest build from apex. 
Python 3.7.0 
torch 1.2.0
transformers 2.1.1

Here is the sample code:
model, optimizer = amp.initialize(model, optimizer, opt_level=O1, loss_scale=1)
model = torch.nn.DataParallel(model)

class BertApexBug(m.BertPreTrainedModel):
    def __init__(self, config):
        super(BertApexBug, self).__init__(config)
        self.bert = m.BertModel(config)
        self.bi = nn.Bilinear(config.hidden_size, config.hidden_size, 1)
        self.init_weights()

    def forward(self, input_ids, token_type_ids=None, attention_mask=None, labels=None, attention_oracle_mask=None):

        flat_input_ids = input_ids.view(-1, input_ids.size(-1))  
        flat_token_type_ids = token_type_ids.view(-1, token_type_ids.size(-1))
        flat_attention_mask = attention_mask.view(-1, attention_mask.size(-1))

        outputs = self.bert(flat_input_ids, flat_token_type_ids, flat_attention_mask)
        pooled_output = outputs[1]

        bi = self.bi(pooled_output,pooled_output)

        return bi

Original Traceback (most recent call last):
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/specific/netapp5_2/gamir/adi/git/common-sense-distillnet/openbook_bert_models.py", line 170, in forward
    bi = self.bi(pooled_output,pooled_output)
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 155, in forward
    return F.bilinear(input1, input2, self.weight, self.bias)
  File "/specific/netapp5_2/gamir/adi/miniconda3/envs/tr_py37/lib/python3.7/site-packages/torch/nn/functional.py", line 1380, in bilinear
    return torch.bilinear(input1, input2, weight, bias)
**RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'mat2'**

Thanks!

**Comment by ptrblck** [comment]
Hi @adihaviv!

I cannot reproduce this issue using just the `nn.Bilinear` layer:
```python
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.bi = nn.Bilinear(20, 30, 1)

    def forward(self, x1, x2):
        output = self.bi(x1, x2)
        return output

model = MyModel().cuda()
x1 = torch.randn(10, 20).cuda()
x2 = torch.randn(10, 30).cuda()

model = amp.initialize(model, opt_level='O1')
output = model(x1, x2)
```

Could you post a link to the Bert model?

**Comment by adihaviv** [comment]
you can take the BertModel from https://github.com/huggingface/pytorch-transformers

After some additional investigation you can reproduce it without BERT. 
You will get this exception if the input is not float.

for example: 
```
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.bi = nn.Bilinear(80, 80, 1)

    def forward(self, x1, x2):
        output = self.bi(x1, x2)
        return output

model = MyModel().cuda()
x1 = torch.randn(10, 80).cuda().long()
x2 = torch.randn(10, 80).cuda().long()

model = amp.initialize(model, opt_level='O1')
output = model(x1, x2)
```

The output type from Bert is 'torch.cuda.HalfTensor' . so if I change it from Half to .float() there is no exception.

**Comment by adihaviv** [comment]
any update?

**Comment by adihaviv** [comment]
@ptrblck, can you help?
