### ISSUE TITLE
CUDNN_STATUS_INTERNAL_ERROR on sagemaker notebook

### ISSUE THREAD

**Issue by hadaev8** [NVIDIA/apex#610]
Any advice?
It work fine on my local pc.
```
Traceback (most recent call last):
  File "train.py", line 368, in <module>
    args.n_gpus, args.rank, args.group_name, hparams, args.checkpoint_path_vanilla)
  File "train.py", line 291, in train
    scaled_loss.backward()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
```

**Comment by ptrblck** [comment]
Hi @hadaev8 ,
which script are you running? Could you post a (minimal) code snippet to reproduce this error?

**Comment by hadaev8** [comment]
It is about cuda version in system and pytorch cuda.

**Comment by MittalShruti** [comment]
hi @hadaev8 

which version pytorch cuda are you using? I am getting same erro

CUDA Version 10.0.130
Pytorch 1.3.1+cu100
CUDNN 7.6.5
