### ISSUE TITLE
bad support for pytorch sync-bn

### ISSUE THREAD

**Issue by CoinCheung** [NVIDIA/apex#611]
My pytorch version is 1.2, and my apex is built from the head on github. My gpu is 2080ti and my system is ubuntu16.04. The cuda version is 10.0.130, and cudnn version is 7.

My test code is like this: 
```python
import argparse

import torch
import torch.nn as nn
import torch.distributed as dist

from apex import amp

def parse_args():
    parse = argparse.ArgumentParser()
    parse.add_argument(
            '--local_rank',
            dest = 'local_rank',
            type = int,
            default = -1,
            )
    return parse.parse_args()


class Model(nn.Module):

    def __init__(self):
        super(Model, self).__init__()
        self.conv = nn.Conv2d(3, 16, 3, 1, 1)
        self.bn = nn.SyncBatchNorm.convert_sync_batchnorm(
            nn.BatchNorm2d(16)
        )
        self.classifier = nn.Linear(16, 10)

    def forward(self, x):
        feat = self.conv(x)
        feat = self.bn(feat)
        feat = torch.mean(feat, dim=(2, 3))
        logits = self.classifier(feat)
        return logits


args = parse_args()
torch.cuda.set_device(args.local_rank)
dist.init_process_group(
            backend = 'nccl',
            init_method = 'tcp://127.0.0.1:33271',
            world_size = torch.cuda.device_count(),
            rank=args.local_rank
            )

net = Model()
net.cuda()
net.train()
criteria = nn.CrossEntropyLoss()
optim = torch.optim.SGD(net.parameters(), lr=1e-3)
net, optim = amp.initialize(net, optim, opt_level='O1')
net = nn.parallel.DistributedDataParallel(
    net,
    device_ids = [args.local_rank, ],
    output_device = args.local_rank
)

inten = torch.randn(4, 3, 128, 128).cuda()
lbs = torch.randint(0, 10, (4, )).cuda()

logits = net(inten)
loss = criteria(logits, lbs)
with amp.scale_loss(loss, optim) as scaled_loss:
    scaled_loss.backward()
optim.step()
print(loss.item())
```
Run this `CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 debug.py`, and I got the error of: 

Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Traceback (most recent call last):
  File "debug.py", line 74, in <module>
    logits = net(inten)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
Traceback (most recent call last):
  File "debug.py", line 74, in <module>
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    logits = net(inten)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "debug.py", line 44, in forward
    feat = self.bn(feat)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 458, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    self.eps, exponential_average_factor, process_group, world_size)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/_functions.py", line 42, in forward
    result = self.forward(*input, **kwargs)
  File "debug.py", line 44, in forward
    count_all.view(-1).long().tolist()
RuntimeError: expected scalar type Half but found Float
    feat = self.bn(feat)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 458, in forward
    self.eps, exponential_average_factor, process_group, world_size)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/_functions.py", line 42, in forward
    count_all.view(-1).long().tolist()
RuntimeError: expected scalar type Half but found Float
Traceback (most recent call last):
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/miniconda/envs/py36/bin/python', '-u', 'debug.py', '--local_rank=1']' returned non-zero exit status 1.

**Comment by shoutOutYangJie** [comment]
>  self.bn = nn.SyncBatchNorm.convert_sync_batchnorm(
            nn.BatchNorm2d(16)

I think "nn.SyncBatchNorm" should be "apex.parallel.convert_syncbn_model"

**Comment by CoinCheung** [comment]
Thanks, do I also need to use apex.parallel for multi-gpu training? I found that the code can work on pytorch1.3, but not on pytorch1.2. If I use pytorch1.3, will the pytorch sync-bn work as correctly as apex.parallel or will there be any unexpected behaviors?

**Comment by graycrown** [comment]
@shoutOutYangJie 
Hello, @as754770178 :
I try to use SyncBatchNorm in DDP mode, there are two kinds of choices for implementation, "torch.nn.SyncBatchNorm.convert_sync_batchnorm" and "apex.parallel.convert_syncbn_model". But only "torch.nn.SyncBatchNorm.convert_sync_batchnorm" works in my experiment. I found some researchers suggest that "torch.nn.SyncBatchNorm.convert_sync_batchnorm" is not suitable for apex. But "apex.parallel.convert_syncbn_model" seems not work in my model, and there will be an error when "BatchNorm" are executed。Logs are shown below:
`Traceback (most recent call last):
  File "train_depthnet_V16_01_DDP_aug_KITTI3.py", line 287, in <module>
    main()
  File "train_depthnet_V16_01_DDP_aug_KITTI3.py", line 241, in main
    losses = train(inputs)
  File "train_depthnet_V16_01_DDP_aug_KITTI3.py", line 148, in train
    out, d_out, c_out = model(inputs)
  File "/home/vision/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vision/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/vision/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../submodels/depthNet_v16_memonger.py", line 339, in forward
    out_conv1 = self.conv1(rgb)
  File "/home/vision/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../submodels/submodule_lib.py", line 91, in forward
    out = self.bn(out)
  File "/home/vision/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/vision/anaconda3/envs/python3.8/lib/python3.8/site-packages/apex/parallel/optimized_sync_batchnorm.py", line 85, in forward
    return SyncBatchnormFunction.apply(input, z, self.weight, self.bias, self.running_mean, self.running_var, self.eps, self.training or not self.track_running_stats, exponential_average_factor, self.process_group, channel_last, self.fuse_relu)
  File "/home/vision/anaconda3/envs/python3.8/lib/python3.8/site-packages/apex/parallel/optimized_sync_batchnorm_kernel.py", line 36, in forward
    torch.distributed.all_gather(mean_l, mean, process_group)
  File "/home/vision/anaconda3/envs/python3.8/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1187, in all_gather
    work = group.allgather([tensor_list], [tensor])
RuntimeError: All tensor operands to scatter/gather must have the same size
`
I had checked the  size of tensors before batchnorm operation, and they all have same shape 
`torch.Size([4, 32, 256, 1216])`

Do you have any suggestions for that ?
