### ISSUE TITLE
Install Failure on CUDA 10.2

### ISSUE THREAD

**Issue by kim-younghan** [NVIDIA/apex#693]
Hi, I am trying to install apex in the way in the quick start but it crashes.

```
pip3 install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

```
/usr/lib/python3/dist-packages/pip/commands/install.py:212: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Processing /home/kim-younghan/apex
  Running setup.py (path:/tmp/pip-txa77oi8-build/setup.py) egg_info for package from file:///home/kim-younghan/apex
    Running command python setup.py egg_info
    torch.__version__  =  1.4.0
    running egg_info
    creating pip-egg-info/apex.egg-info
    writing pip-egg-info/apex.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/apex.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/apex.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/apex.egg-info/SOURCES.txt'
    /tmp/pip-txa77oi8-build/setup.py:43: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
  Source in /tmp/pip-txa77oi8-build has version 0.1, which satisfies requirement apex==0.1 from file:///home/kim-younghan/apex
Installing collected packages: apex
  Running setup.py install for apex ...     Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-txa77oi8-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-at8pivae-record/install-record.txt --single-version-externally-managed --compile --user --prefix=
    torch.__version__  =  1.4.0
    /tmp/pip-txa77oi8-build/setup.py:43: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2018 NVIDIA Corporation
    Built on Sat_Aug_25_21:08:01_CDT_2018
    Cuda compilation tools, release 10.0, V10.0.130
    from /usr/local/cuda-10.0/bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-txa77oi8-build/setup.py", line 100, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-txa77oi8-build/setup.py", line 77, in check_cuda_torch_binary_vs_bare_metal
        "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.1.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
error
Cleaning up...
  Removing source in /tmp/pip-txa77oi8-build
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-txa77oi8-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-at8pivae-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-txa77oi8-build/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-txa77oi8-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --cpp_ext --cuda_ext install --record /tmp/pip-at8pivae-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-txa77oi8-build/
```

Is there anything I can do?

**Comment by tanyapohn** [comment]
Hello, @kim-younghan 

I had the same problem, and I think there might be an incompatibility with `pytoch` and `cuda` version when you first installed. 

Please check this [link](https://github.com/NVIDIA/apex/issues/621#issuecomment-579669456)

Hope it helps!

**Comment by kim-younghan** [comment]
Thanks, @tanyapohn !!

I think it crashed because PyTorch version didn't match. 

Thanks for giving me advice!
