### ISSUE TITLE
Running setup.py install for apex ... error

### ISSUE THREAD

**Issue by keloemma** [NVIDIA/apex#723]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-lisrmeqq/setup.py", line 103, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-lisrmeqq/setup.py", line 80, in check_cuda_torch_binary_vs_bare_metal
        "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.1.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
    Running setup.py install for apex ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-lisrmeqq
Removed build tracker: '/tmp/pip-req-tracker-jffj36az'
ERROR: Command errored out with exit status 1: /home/getalp/keloe/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-lisrmeqq/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-lisrmeqq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --pyprof --cpp_ext --cuda_ext install --record /tmp/pip-record-g7zy9ukr/install-record.txt --single-version-externally-managed --compile --install-headers /home/getalp/keloe/anaconda3/include/python3.7m/apex Check the logs for full command output.
Exception information:

I am getting this error in my stacktrace when trying for (many times to install apex) Does this mean that I have to change CUDA version ? I f yes how ? 

Should I use pip to reinstall cuda ??

**Comment by tanyapohn** [comment]
Hi @keloemma ,

According to your error, it says:

> RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries. Pytorch binaries were compiled with Cuda 10.1.

I suggest you:
1. Check the version of `pytorch` with `cuda` compatibility
    - To check your cuda version: `nvcc --version` or in `usr/local/cuda-[version]`
    - If your CUDA is 10.0, please re-check your pytorch with cuda [here](https://pytorch.org/get-started/previous-versions/)
   - Then, install/re-install with `pip install torch==1.4+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html`

2. You can now install apex with [this](https://github.com/NVIDIA/apex/issues/86#issuecomment-455620478) as @seedlit has mentioned.

I hope this would help

**Comment by keloemma** [comment]
> Hi @keloemma ,
> 
> According to your error, it says:
> 
> > RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries. Pytorch binaries were compiled with Cuda 10.1.
> 
> There is no need to change your `cuda` version, all you need is to install `pytorch` with the compatible `cuda` version.
> 
> I suggest you:
> 
>     1. Check the version of `pytorch` with `cuda` compatibility
>        
>        * To check your cuda version: `nvcc --version` or in `usr/local/cuda-[version]`
>        * If your CUDA version is 10.0, please re-check your pytorch with cuda [here](https://pytorch.org/get-started/previous-versions/)
>        * Then, install/re-install with `pip install torch==1.4+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html`
> 
>     2. You can now install apex with [this](https://github.com/NVIDIA/apex/issues/86#issuecomment-455620478) as @seedlit has mentioned.
> 
> 
> I hope this would help

Hello when running my code I get this error : FAISS library was not found.
FAISS not available. Switching to standard nearest neighbors search implementation.
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    from xlm.trainer import SingleTrainer, EncDecTrainer
  File "/home/getalp/kelodjoe/eXP/Flaubert/xlm/trainer.py", line 21, in <module>
    import apex
  File "/home/getalp/kelodjoe/anaconda3/lib/python3.7/site-packages/apex/__init__.py", line 6, in <module>
    from . import parallel
ImportError: cannot import name 'parallel' from 'apex' (/home/getalp/kelodjoe/anaconda3/lib/python3.7/site-packages/apex/__init__.py)

How can I solve IT ?

**Comment by Lornatang** [comment]
@keloemma 
As far as I know, installing `apex` under conda can cause a lot of problems, and I recommend that you use native python as your python environment, which may slove your problems.

**Comment by ptrblck** [comment]
@keloemma 
Is your working directory currently inside of the apex folder? If so, could you change it and try to import apex again, please?

**Comment by keloemma** [comment]
> @keloemma
> Is your working directory currently inside of the apex folder? If so, could you change it and try to import apex again, please?


Actually apex directory is inside my working directory . I run my script in the directory where apex is located

**Comment by keloemma** [comment]
> Hi @keloemma ,
> 
> According to your error, it says:
> 
> > RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries. Pytorch binaries were compiled with Cuda 10.1.
> 
> There is no need to change your `cuda` version, all you need is to install `pytorch` with the compatible `cuda` version.
> 
> I suggest you:
> 
>     1. Check the version of `pytorch` with `cuda` compatibility
>        
>        * To check your cuda version: `nvcc --version` or in `usr/local/cuda-[version]`
>        * If your CUDA version is 10.0, please re-check your pytorch with cuda [here](https://pytorch.org/get-started/previous-versions/)
>        * Then, install/re-install with `pip install torch==1.4+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html`
> 
>     2. You can now install apex with [this](https://github.com/NVIDIA/apex/issues/86#issuecomment-455620478) as @seedlit has mentioned.
> 
> 
> I hope this would help

I try your solution but I still have this error  :

Traceback (most recent call last):
  File "setup.py", line 103, in <module>
    check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
  File "setup.py", line 80, in check_cuda_torch_binary_vs_bare_metal
    "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.0.
In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).

**Comment by tanyapohn** [comment]
Hi @keloemma ,

Apex requires `CUDA 9 or newer` as it has been stated on [this](https://github.com/NVIDIA/apex#requirements). 

I would suggest you update your `CUDA`.

Cheers!

**Comment by keloemma** [comment]
> Hi @keloemma ,
> 
> Apex requires `CUDA 9 or newer` as it has been stated on [this](https://github.com/NVIDIA/apex#requirements).
> 
> I would suggest you update your `CUDA`.
> 
> Cheers!

I updated my cuda even to 10.0 but is ti si not working whn ruuning my script which uses apex it says : 

FAISS library was not found.
FAISS not available. Switching to standard nearest neighbors search implementation.
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    from xlm.trainer import SingleTrainer, EncDecTrainer
  File "/home/getalp/kelodjoe/eXP/Flaubert/xlm/trainer.py", line 21, in <module>
    import apex
  File "/home/getalp/kelodjoe/anaconda3/lib/python3.7/site-packages/apex/__init__.py", line 6, in <module>
    from . import parallel
ImportError: cannot import name 'parallel' from 'apex' (/home/getalp/kelodjoe/anaconda3/lib/python3.7/site-packages/apex/__init__.py)

I do really know what to do it been 2 weeks I ma trying to resolve this problem

**Comment by Lornatang** [comment]
Upgrade to CUDA10 and CUDNN7. Then delete the folder and reclone, and run the command.

**Comment by keloemma** [comment]
> Upgrade to CUDA10 and CUDNN7. Then delete the folder and reclone, and run the command.

My cuda is already 10 but how can I upgrade it to CUDA10 again ? and for CUDNN7 if you have a link to the type of command I should use  could you share me ?

**Comment by Lornatang** [comment]
@keloemma 
Please upgrade your CUDA to 10.1 and install cudnn version correctly, and clone again.

**Comment by zhw2020913** [comment]
Did you reslved this problem? I have the same problem.
