### ISSUE TITLE
ImportError: cannot import name 'parallel' from 'apex' 

### ISSUE THREAD

**Issue by keloemma** [NVIDIA/apex#724]
I am getting this error after trying reinstalling apex and running my code :

FAISS library was not found.
FAISS not available. Switching to standard nearest neighbors search implementation.
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    from xlm.trainer import SingleTrainer, EncDecTrainer
  File "/data1/home/gealp/kedjoe/eXP/Flaubert/xlm/trainer.py", line 21, in <module>
    import apex
  File "/home/gealp/keljoe/anaconda3/lib/python3.7/site-packages/apex/__init__.py", line 6, in <module>
    from . import parallel
ImportError: cannot import name 'parallel' from 'apex' (/home/gealp/keldjoe/anaconda3/lib/python3.7/site-packages/apex/__init__.py)

**Comment by Lornatang** [comment]
see #723
