### ISSUE TITLE
Build error with Pytorch 1.5 & CUDA 10.1

### ISSUE THREAD

**Issue by abhinavs95** [NVIDIA/apex#805]
I'm trying to build Apex on top of Pytorch 1.5 with CUDA 10.1.

OS: Ubuntu 16.04
gcc version: 5.4.0
nvcc version: 10.1

Error log:

```
:OrderedDict<std::__cxx11::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, s[403/1867]
_ptr<torch::nn::Module> >&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module> 
torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::ConvTranspose2dImpl]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:44:65: error: invalid static_cast from type ‘const torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:56:59: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:68:61: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, std::shared
_ptr<torch::nn::Module> >&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module> 
torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::ConvTranspose1dImpl]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:44:65: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:56:59: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:68:61: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, std::shared
_ptr<torch::nn::Module> >&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module> 
torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::Conv3dImpl]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:44:65: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:56:59: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:68:61: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, std::shared
_ptr<torch::nn::Module> >&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module> 
torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::Conv2dImpl]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:44:65: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:56:59: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:68:61: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, std::shared
_ptr<torch::nn::Module> >&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module>
torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::Conv1dImpl]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:44:65: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:56:59: error: invalid static_cast from type ‘const torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:68:61: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, std::shared
_ptr<torch::nn::Module> >&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module> 
torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::AdaptiveLogSoftmaxWithLossImpl]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:44:65: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:56:59: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:68:61: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, std::shared
_ptr<torch::nn::Module> >&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module> 
torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::BilinearImpl]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:44:65: error: invalid static_cast from type ‘const torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:56:59: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:68:61: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, std::shared
_ptr<torch::nn::Module> >&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h: In instantiation of ‘std::shared_ptr<torch::nn::Module> 
torch::nn::Cloneable<Derived>::clone(const c10::optional<c10::Device>&) const [with Derived = torch::nn::LinearImpl]’:
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/optim/sgd.h:48:48:   required from here
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:44:65: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:56:59: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, at::Tensor>&’
    /opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:68:61: error: invalid static_cast from type ‘const torch:
:OrderedDict<std::__cxx11::basic_string<char>, std::shared_ptr<torch::nn::Module> >’ to type ‘torch::OrderedDict<std::__cxx11::basic_string<char>, std::shared
_ptr<torch::nn::Module> >&’
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    Running setup.py install for apex ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-3zcupvqx
Removed build tracker: '/tmp/pip-req-tracker-4v84mp31'
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3zcupvqx/s
etup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3zcupvqx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"'
, '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-01gkiepj/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.6m/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 404, in run
    use_user_site=options.use_user_site,
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 829, in install
    scheme=scheme,
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/operations/install/legacy.py", line 72, in install
    cwd=install_req.unpacked_source_directory,
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 275, in runner
    spinner=spinner,
  File "/opt/conda/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-3zcupvqx/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-3zcupvqx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__)
;code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-r
ecord-01gkiepj/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.6m/apex Check the logs for full c
ommand output.
```

I have noticed upgrading to gcc 7 fixes the problem. Does this mean Apex is not compatible with gcc 5 anymore? I need it to work with gcc 5 because other packages in my system might break on upgrading gcc.

**Comment by minaltolpadi** [comment]
Had the same error. For temporary workaround I checked out an earlier version of apex as mentioned here - https://github.com/NVIDIA/apex/issues/802
git checkout f3a960f80244cf9e80558ab30f7f7e8cbf03c0a0

**Comment by abhinavs95** [comment]
Thanks @minaltolpadi , I'm able to install it successfully from that commit

**Comment by aabzaliev** [comment]
@minaltolpadi thank you very much for the solution, worked for me as well

**Comment by fantasysee** [comment]
@minaltolpadi thank you very much for the solution!!!
