### ISSUE TITLE
RuntimeError in Variable._execution_engine.run_backward

### ISSUE THREAD

**Issue by SergeyMilyaev** [NVIDIA/apex#858]
Hi everyone, I've installed PyTorch 1.5 with CUDA 1.2 and apex with CUDA and C++ extensions and observe runtime error on backward pass. To reproduce the error I use [modified Apex ImageNet example with synthetic input](https://gist.github.com/SergeyMilyaev/156135e0949a5e648e01686b4cc85538):

`CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 main_amp.py  --a  resnet50 --b 32 --workers 16 --opt-level O0 dummy`

and I see the following output (runtime error displays without any description)

```
Traceback (most recent call last):
  File "/media2/milyaev/Code/Benchmarks/main1_amp.py", line 522, in <module>
    main()
  File "/media2/milyaev/Code/Benchmarks/main1_amp.py", line 254, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "/media2/milyaev/Code/Benchmarks/main1_amp.py", line 342, in train
    scaled_loss.backward()
  File "/media3/milyaev/anaconda3/envs/PyTorch1.5_gpu12/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/media3/milyaev/anaconda3/envs/PyTorch1.5_gpu12/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
    Variable._execution_engine.run_backward(
RuntimeError
```

[Modified PyTorch ImageNet example with synthetic input](https://gist.github.com/SergeyMilyaev/b535d2f5bf57dda7cdbc2941b2540dc6) runs without any problems:
`
CUDA_VISIBLE_DEVICES=0,1 python main.py -a resnet50 --b 32 --workers 16 --dist-url 'tcp://127.0.0.1:2504' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0  dummy`

The machine configuration is the following:
GPU: 8 * GTX 1080ti  
CPU: Intel(R) Xeon(R) CPU E5-2650 v4
OS: CentOS Linux release 8.1.1911
GCC version:  8.3.1
CUDA and NVCC version: 10.2
GPU driver version: 440.64.00 

When I try to install and run apex on the another machine with the same software configuration but RTX 2080ti cards I don't observe such an error with a backward pass.

**Comment by SergeyMilyaev** [comment]
I also just checked that docker container with the same Apex synthetic example runs without any problems, Dockerfile available [here](https://gist.github.com/SergeyMilyaev/76cfe84f9cfab2ab9bb3a08e60c7a625).
