### ISSUE TITLE
distributed lamb breaks python-only amp

### ISSUE THREAD

**Issue by lisadunlap** [NVIDIA/apex#865]
I have been using apex for the last few weeks now but today I am unable to import it and get this error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/apex/amp/amp.py", line 5, in <module>
    from .frontend import *
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/apex/amp/frontend.py", line 2, in <module>
    from ._initialize import _initialize
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/apex/amp/_initialize.py", line 14, in <module>
    from ..contrib.optimizers import FP16_Optimizer as FP16_Optimizer_for_fused
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/apex/contrib/optimizers/__init__.py", line 4, in <module>
    from .distributed_fused_lamb import DistributedFusedLAMB
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/apex/contrib/optimizers/distributed_fused_lamb.py", line 4, in <module>
    import amp_C
ModuleNotFoundError: No module named 'amp_C'


I tried removing it and re-installing it and got the same issue.

**Comment by ptrblck** [comment]
Thanks for raising this issue, Lisa!
We'll look into it.

CC @thorjohnsen

**Comment by PareshKamble** [comment]
@ptrblck Same error...
But with **segmentation fault**.
```
Traceback (most recent call last):
  File "performance_benchmark.py", line 11, in <module>
    import maskrcnn
  File "/home/ozsports/Documents/OZ_ARena/Background_Subtraction_Segmentation/ARTHus/maskrcnn.py", line 6, in <module>
    from maskrcnn_benchmark.modeling.detector import build_detection_model
  File "/home/ozsports/Documents/OZ_ARena/Background_Subtraction_Segmentation/ARTHus/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/ozsports/Documents/OZ_ARena/Background_Subtraction_Segmentation/ARTHus/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/detectors.py", line 2, in <module>
    from .generalized_rcnn import GeneralizedRCNN
  File "/home/ozsports/Documents/OZ_ARena/Background_Subtraction_Segmentation/ARTHus/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 11, in <module>
    from ..backbone import build_backbone
  File "/home/ozsports/Documents/OZ_ARena/Background_Subtraction_Segmentation/ARTHus/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/__init__.py", line 2, in <module>
    from .backbone import build_backbone
  File "/home/ozsports/Documents/OZ_ARena/Background_Subtraction_Segmentation/ARTHus/maskrcnn-benchmark/maskrcnn_benchmark/modeling/backbone/backbone.py", line 7, in <module>
    from maskrcnn_benchmark.modeling.make_layers import conv_with_kaiming_uniform
  File "/home/ozsports/Documents/OZ_ARena/Background_Subtraction_Segmentation/ARTHus/maskrcnn-benchmark/maskrcnn_benchmark/modeling/make_layers.py", line 10, in <module>
    from maskrcnn_benchmark.layers import Conv2d
  File "/home/ozsports/Documents/OZ_ARena/Background_Subtraction_Segmentation/ARTHus/maskrcnn-benchmark/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/home/ozsports/Documents/OZ_ARena/Background_Subtraction_Segmentation/ARTHus/maskrcnn-benchmark/maskrcnn_benchmark/layers/nms.py", line 5, in <module>
    from apex import amp
  File "/home/ozsports/anaconda3/envs/DeepImageBlend/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/home/ozsports/anaconda3/envs/DeepImageBlend/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/home/ozsports/anaconda3/envs/DeepImageBlend/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/amp/amp.py", line 5, in <module>
    from .frontend import *
  File "/home/ozsports/anaconda3/envs/DeepImageBlend/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/amp/frontend.py", line 2, in <module>
    from ._initialize import _initialize
  File "/home/ozsports/anaconda3/envs/DeepImageBlend/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/amp/_initialize.py", line 14, in <module>
    from ..contrib.optimizers import FP16_Optimizer as FP16_Optimizer_for_fused
  File "/home/ozsports/anaconda3/envs/DeepImageBlend/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/contrib/optimizers/__init__.py", line 4, in <module>
    from .distributed_fused_lamb import DistributedFusedLAMB
  File "/home/ozsports/anaconda3/envs/DeepImageBlend/lib/python3.6/site-packages/apex-0.1-py3.6.egg/apex/contrib/optimizers/distributed_fused_lamb.py", line 4, in <module>
    import amp_C
ModuleNotFoundError: No module named 'amp_C'
Segmentation fault (core dumped)
```
Kindly help resolve this.

**Comment by thorjohnsen** [comment]
I have fixed this issue. Sorry for breaking it.

**Comment by pogevip** [comment]
How to solve this bug?

**Comment by thorjohnsen** [comment]
@pogevip This was resolved back in June. The problem occurred when AMP was compiled without --cpp_ext. The solution was to remove the line 

from .distributed_fused_lamb import DistributedFusedLAMB

from apex/contrib/optimizers/__init__.py. Are you saying this issue is back? If you see a similar problem, please post more details so we can resolve it.

**Comment by fourat-bs** [comment]
Traceback (most recent call last):
  File "models/bert-nvidia/bert_finetuning_SA_DC.py", line 34, in <module>
    from nemo.collections.nlp.models.text_classification import TextClassificationModel
  File "/usr/local/lib/python3.7/site-packages/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/usr/local/lib/python3.7/site-packages/nemo/collections/nlp/models/__init__.py", line 15, in <module>
    from nemo.collections.nlp.models.dialogue_state_tracking.sgdqa_model import SGDQAModel
  File "/usr/local/lib/python3.7/site-packages/nemo/collections/nlp/models/dialogue_state_tracking/__init__.py", line 15, in <module>
    from nemo.collections.nlp.models.dialogue_state_tracking.sgdqa_model import SGDQAModel
  File "/usr/local/lib/python3.7/site-packages/nemo/collections/nlp/models/dialogue_state_tracking/sgdqa_model.py", line 33, in <module>
    from nemo.collections.nlp.models.nlp_model import NLPModel
  File "/usr/local/lib/python3.7/site-packages/nemo/collections/nlp/models/nlp_model.py", line 26, in <module>
    from megatron.checkpointing import get_checkpoint_version, set_checkpoint_version
  File "/usr/local/lib/python3.7/site-packages/megatron/checkpointing.py", line 25, in <module>
    from megatron import (get_args,
  File "/usr/local/lib/python3.7/site-packages/megatron/utils.py", line 24, in <module>
    import amp_C
ModuleNotFoundError: No module named 'amp_C'

still getting the error

**Comment by ptrblck** [comment]
@fourat-bs I don't think you are hitting the same issue, as the stacktrace doesn't point to `distributed_fused_lamb` but to `megatron`, which might need an apex installation with the cpp/cuda extension.

**Comment by skye95git** [comment]
> @fourat-bs I don't think you are hitting the same issue, as the stacktrace doesn't point to `distributed_fused_lamb` but to `megatron`, which might need an apex installation with the cpp/cuda extension.

Hi, I meet the similar issue:
Traceback (most recent call last):
  File "tools/generate_samples_gpt.py", line 27, in <module>
    from megatron.checkpointing import load_checkpoint
  File "/home/linjiayi/Megatron-LM/megatron/checkpointing.py", line 25, in <module>
    from megatron import (get_args,
  File "/home/linjiayi/Megatron-LM/megatron/utils.py", line 24, in <module>
    import amp_C
ModuleNotFoundError: No module named 'amp_C'

Do you know how to solve it?

**Comment by dayL-W** [comment]
same error

**Comment by KwangryeolPark** [comment]
same error.
