### ISSUE TITLE
ModuleNotFoundError: No module named 'amp_C'

### ISSUE THREAD

**Issue by nv-quan** [NVIDIA/apex#866]
I have pulled the latest code and installed as instructed, however when I imported apex, this error happened. I used apex before with no problem, is this related to the latest commit?
```
>>> import apex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/apex/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/home/ubuntu/apex/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/home/ubuntu/apex/apex/amp/amp.py", line 5, in <module>
    from .frontend import *
  File "/home/ubuntu/apex/apex/amp/frontend.py", line 2, in <module>
    from ._initialize import _initialize
  File "/home/ubuntu/apex/apex/amp/_initialize.py", line 14, in <module>
    from ..contrib.optimizers import FP16_Optimizer as FP16_Optimizer_for_fused
  File "/home/ubuntu/apex/apex/contrib/optimizers/__init__.py", line 4, in <module>
    from .distributed_fused_lamb import DistributedFusedLAMB
  File "/home/ubuntu/apex/apex/contrib/optimizers/distributed_fused_lamb.py", line 4, in <module>
    import amp_C
ModuleNotFoundError: No module named 'amp_C'
```

**Comment by nv-quan** [comment]
Duplicate: #865
