### ISSUE TITLE
Got AttributeError: 'DistributedDataParallel' object has no attribute 'needs_refresh' when doing scaled_loss.backward

### ISSUE THREAD

**Issue by lognat0704** [NVIDIA/apex#877]
My environment nvcc and pytorch.version.cuda are cuda-10.1.2 and installed apex and C++ extensions, GPUs are Titan_rtx *2.  I did run the test script - [distributed_data_parallel.py](https://github.com/NVIDIA/apex/blob/master/examples/simple/distributed/distributed_data_parallel.py) without any problem. But when I use Apex on training efficientdet-pytorch model,  Got AttributeError: 'DistributedDataParallel' object has no attribute 'needs_refresh' when doing scaled_loss.backward

```
Traceback (most recent call last):00000, time: 1.25592
  File "training-efficientdet-v4-apex.py", line 574, in <module>
    run_training()
  File "training-efficientdet-v4-apex.py", line 549, in run_training
    fitter.fit(train_loader, val_loader)
  File "training-efficientdet-v4-apex.py", line 369, in fit
    summary_loss = self.train_one_epoch(train_loader)
  File "training-efficientdet-v4-apex.py", line 438, in train_one_epoch
    scaled_loss.backward()
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/apex/parallel/distributed.py", line 363, in allreduce_hook
    if self.delay_allreduce or self.needs_refresh:
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute 'needs_refresh'
Traceback (most recent call last):
  File "training-efficientdet-v4-apex.py", line 574, in <module>
    run_training()
  File "training-efficientdet-v4-apex.py", line 549, in run_training
    fitter.fit(train_loader, val_loader)
  File "training-efficientdet-v4-apex.py", line 369, in fit
    summary_loss = self.train_one_epoch(train_loader)
  File "training-efficientdet-v4-apex.py", line 438, in train_one_epoch
    scaled_loss.backward()
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/apex/parallel/distributed.py", line 363, in allreduce_hook
    if self.delay_allreduce or self.needs_refresh:
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'DistributedDataParallel' object has no attribute 'needs_refresh'
Traceback (most recent call last):
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/hy/anaconda3/envs/badeda/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hy/anaconda3/envs/badeda/bin/python', '-u', 'training-efficientdet-v4-apex.py', '--local_rank=1']' returned non-zero exit status 1.
```
I also tried to switch from apex's DistributedDataParallel(model) to  torch.nn.parallel.DistributedDataParallel,but only works if I set up batch size =8 (which only use one GPU), but report error using batch size over 8 (use two GPUs)

Any advice and suggestions will be greatly appreciated

**Comment by voodoopotato** [comment]
can you provide your train script?

**Comment by zhiqihuang** [comment]
Same here. did you solve it? Thanks

**Comment by lognat0704** [comment]
Hi,

Sorry for reply.
I just use docker to solve the problem.

Nelson Hong Ming Tseng

*Deep Learning Engineer with design mind*

*+86 15618236628 *

**Comment by LiuXinqi12** [comment]
I encountered the same problem when I called "scaled_loss.backward()".

**Comment by ptrblck** [comment]
`apex`' DDP is deprecated and we recommend using the upstream DDP wrapper.
