### ISSUE TITLE
SycnBN in AMP?

### ISSUE THREAD

**Issue by LightToYang** [NVIDIA/apex#88]
How can I implement SycnBN with AMP? Should usign the following code in main_fp16_optimizer.py?

```
import apex
model = apex.parallel.convert_syncbn_model(model)

from apex.parallel import DistributedDataParallel as DDP
model = DDP(model, delay_allreduce=True)
```

If so, can the DDP be repalced with original DataParallel if I train net with only one computer?

**Comment by mcarilli** [comment]
None of that code uses Amp, but if your question is whether SyncBN and DDP are interoperable, the answer is yes, they should be.

Just make sure that all modifications to your model (including `model = apex.parallel.convert_syncbn_model(model)`) are done before `model = DDP(model, delay_allreduce=True)`, because DDP needs to see the finalized model parameters.  The way you've written it above should be ok.

**Comment by LightToYang** [comment]
Because apex.amp is a tool designed for ease of use and maximum safety in FP16 training. So how can I train model with SycnBN like that in main_fp16_optimizer.py? And DPP is designed for distributed training, can I replace DPP with torch.nn.DataParallel for single device ?

**Comment by mcarilli** [comment]
You should be able to call `model = apex.parallel.convert_syncbn_model(model)`, use it with either Amp or FP16_Optimizer, and it will work out of the box.

In general, though, it's good practice to make sure that all modifications to your `model` (e.g. `convert_syncbn_model`, `.half()` or `network_to_half`, and DDP) are done before you construct any optimizers, because the optimizers need to receive references to the finalized model parameters.

**Comment by LightToYang** [comment]
@mcarilli When using `sycn_bn` the following error occures:
```
Traceback (most recent call last):
  File "main_fp16_optimizer.py", line 485, in <module>
    main()
  File "main_fp16_optimizer.py", line 231, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main_fp16_optimizer.py", line 310, in train
    output = model(input)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/distributed.py", line 445, in forward
    result = self.module(*inputs, **kwargs)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/resnet.py", line 140, in forward
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/optimized_sync_batchnorm.py", line 63, in forward
    return SyncBatchnormFunction.apply(input, self.weight, self.bias, self.running_mean, self.running_var, self.eps, self.track_running_stats, self.momentum, self.process_group)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/parallel/optimized_sync_batchnorm_kernel.py", line 21, in forward
    process_group = torch.distributed.get_default_group()
AttributeError: module 'torch.distributed' has no attribute 'get_default_group'
```

**Comment by sahewat** [comment]
This is an incompatibility with the latest version of Pytorch. See https://github.com/pytorch/pytorch/pull/14767

For the interim, a hacky solution is to monkey patch the library as follows: 
```
from torch.distributed.distributed_c10d import _get_default_group
torch.distributed.get_default_group = _get_default_group
````
This is obviously not a good idea long term.

**Comment by wangxiaodong1021** [comment]
> Yes, any of those use cases should work. I don't know why you'd want to use syncBN without DDP though.

Thank you for your reply. Not using DDP is because the syncBN error caused the training to get stuck. Now everything is OK.
