### ISSUE TITLE
Cannot build apex with cuda 10.1 for Windows 10

### ISSUE THREAD

**Issue by MichaelJanz** [NVIDIA/apex#905]
Hi, I am having issues with building apex as mentioned above. 

My goal is to use the finetune a bert model. When doing this, I receive this error message:

_multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")
_

I am using this command for installing and builing apex:
 `python setup.py install --cuda_ext --cpp_ext >out.txt" .`

I tried the official docs also ofc, but it didnt work. I am running that command by using x64 Native Tools Command Prompt for VS 2019.

See the output here:
`setup.py:51: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
  warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0x81 in position 62: invalid start byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Traceback (most recent call last):
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\torch\utils\cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 390, in <module>
    extras_require=extras,
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\setuptools\__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\torch\utils\cpp_extension.py", line 585, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\torch\utils\cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Science\anaconda3\envs\bert_abssum4\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
    return stream.closed
ValueError: underlying buffer has been detached`

And the compiler log attached.
It looks to me like there are alot of compiling errors. However I am a newbie, so I am thankful for any hints.

Thank you.
[out.txt](https://github.com/NVIDIA/apex/files/4869320/out.txt)

**Comment by afogarty85** [comment]
I have the same problem with:
torch: 1.5.1
torch.version.cuda: 10.1

my install process:

git clone https://github.com/NVIDIA/apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./apex
