### ISSUE TITLE
UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by tehreemnaqvi** [NVIDIA/apex#938]
Hi,

I got this error, spent a lot of time to resolve this but couldn't find any solution.

How can I solve this issue? 
Please help.

Below is the error:

running install
running bdist_egg
running egg_info
writing slayerCuda.egg-info\PKG-INFO
writing dependency_links to slayerCuda.egg-info\dependency_links.txt
writing top-level names to slayerCuda.egg-info\top_level.txt
reading manifest file 'slayerCuda.egg-info\SOURCES.txt'
writing manifest file 'slayerCuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'slayerCuda' extension
creating C:\Users\Tehreem\Desktop\slayerPytorch-master\build\temp.win-amd64-3.6
creating C:\Users\Tehreem\Desktop\slayerPytorch-master\build\temp.win-amd64-3.6\Release
creating C:\Users\Tehreem\Desktop\slayerPytorch-master\build\temp.win-amd64-3.6\Release\src
creating C:\Users\Tehreem\Desktop\slayerPytorch-master\build\temp.win-amd64-3.6\Release\src\cuda
Emitting ninja build file C:\Users\Tehreem\Desktop\slayerPytorch-master\build\temp.win-amd64-3.6\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\include -IC:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\include\TH -IC:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\Tehreem\.conda\envs\py36\include -IC:\Users\Tehreem\.conda\envs\py36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c C:\Users\Tehreem\Desktop\slayerPytorch-master\src\cuda\slayerKernels.cu -o C:\Users\Tehreem\Desktop\slayerPytorch-master\build\temp.win-amd64-3.6\Release\src/cuda/slayerKernels.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -arch=sm_60 -O2 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=slayerCuda -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: C:/Users/Tehreem/Desktop/slayerPytorch-master/build/temp.win-amd64-3.6/Release/src/cuda/slayerKernels.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -IC:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\include -IC:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\include\TH -IC:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\Users\Tehreem\.conda\envs\py36\include -IC:\Users\Tehreem\.conda\envs\py36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -c C:\Users\Tehreem\Desktop\slayerPytorch-master\src\cuda\slayerKernels.cu -o C:\Users\Tehreem\Desktop\slayerPytorch-master\build\temp.win-amd64-3.6\Release\src/cuda/slayerKernels.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -arch=sm_60 -O2 -use_fast_math -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=slayerCuda -D_GLIBCXX_USE_CXX11_ABI=0
C:/Users/Tehreem/.conda/envs/py36/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

C:/Users/Tehreem/.conda/envs/py36/lib/site-packages/torch/include\ATen/record_function.h(18): warning: modifier is ignored on an enum specifier

C:/Users/Tehreem/.conda/envs/py36/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(483): error: a member with an in-class initializer must be const

C:/Users/Tehreem/.conda/envs/py36/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(496): error: a member with an in-class initializer must be const

C:/Users/Tehreem/.conda/envs/py36/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(510): error: a member with an in-class initializer must be const

C:/Users/Tehreem/.conda/envs/py36/lib/site-packages/torch/include\torch/csrc/jit/api/module.h(523): error: a member with an in-class initializer must be const

C:/Users/Tehreem/.conda/envs/py36/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(97): warning: modifier is ignored on an enum specifier

C:/Users/Tehreem/.conda/envs/py36/lib/site-packages/torch/include\torch/csrc/autograd/profiler.h(126): warning: modifier is ignored on an enum specifier

4 errors detected in the compilation of "C:/Users/Tehreem/AppData/Local/Temp/tmpxft_00004c9c_00000000-10_slayerKernels.cpp1.ii".
slayerKernels.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 631, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\Tehreem\.conda\envs\py36\lib\site-packages\torch\utils\cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

Your help will be highly appreciated!!

Thanks

**Comment by ZM-J** [comment]
I think it is because one should install Visual Studio at first.

> Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

Have you tried this?
