### ISSUE TITLE
Merged PR #937 breaks tox installs

### ISSUE THREAD

**Issue by minggnim** [NVIDIA/apex#940]
The same error as in #931 still persists after the merge #937. The environment I attempted to install apex was in tox for CD, where Cuda toolkit isn't available, and caused the error below

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-md7yngpi/setup.py", line 35, in <module>
        _, bare_metal_major, _ = get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-md7yngpi/setup.py", line 14, in get_cuda_bare_metal_version
        raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by HolographicWings** [comment]
same

**Comment by Kepler-Br** [comment]
same

**Comment by xden2331** [comment]
Same

**Comment by lqniunjunlper** [comment]
same

**Comment by lqniunjunlper** [comment]
same

**Comment by lqniunjunlper** [comment]
export TORCH_CUDA_ARCH_LIST="compute capability" before run install
