### ISSUE TITLE
No module named 'fast_self_multihead_attn'

### ISSUE THREAD

**Issue by Hecmay** [NVIDIA/apex#958]
Hi,
Iwas trying run the fast-MHA example here: 
https://github.com/NVIDIA/apex/tree/master/apex/contrib/multihead_attn

I got the following errors when running the performance:
```
Traceback (most recent call last):
  File "perf_test_multihead_attn.py", line 5, in <module>
    from apex.contrib.multihead_attn import SelfMultiheadAttn
  File "/home/apex/apex/contrib/multihead_attn/__init__.py", line 1, in <module>
    from .self_multihead_attn import SelfMultiheadAttn
  File "/home/apex/apex/contrib/multihead_attn/self_multihead_attn.py", line 9, in <module>
    from .fast_self_multihead_attn_func          import fast_self_attn_func
  File "/home/apex/apex/contrib/multihead_attn/fast_self_multihead_attn_func.py", line 2, in <module>
    import fast_self_multihead_attn
ModuleNotFoundError: No module named 'fast_self_multihead_attn'
```

The Apex packaged is installed with CPP and CUDA extension turned on. And I was not able to find the definition of this missing function anywhere.

**Comment by jehoon1ee** [comment]
Hi,I'm facing the same issue.
Have you found the solution?

**Comment by lendrick** [comment]
Removing pyprof from my code fixed this for me.

**Comment by sanjaychari** [comment]
I am facing the same issue. I am not using pyprof in my code.

**Comment by robin5540** [comment]
Looks like apex doesn't build this extension by default.

https://github.com/NVIDIA/apex/blob/6b7e77b0c34ca2be4243d495423e17d49090b49e/setup.py#L371

https://github.com/NVIDIA/apex/blob/6b7e77b0c34ca2be4243d495423e17d49090b49e/setup.py#L301

adding `--global-option="--fast_multihead_attn"` fixed the problem for me. (I'm running pyprof, and I get this exception during `pyprof.init()`)

**Comment by li-yi-dong** [comment]
> Looks like apex doesn't build this extension by default.
> 
> https://github.com/NVIDIA/apex/blob/6b7e77b0c34ca2be4243d495423e17d49090b49e/setup.py#L371
> 
> https://github.com/NVIDIA/apex/blob/6b7e77b0c34ca2be4243d495423e17d49090b49e/setup.py#L301
> 
> adding `--global-option="--fast_multihead_attn"` when installing apex fixed the problem for me. (I'm running pyprof, and I get this exception during `pyprof.init()`)

After I adding `--global-option="--fast_multihead_attn"`, I get a compilation error:
/usr/local/cuda/bin/nvcc -I/apex-master/apex/contrib/csrc/multihead_attn/cutlass -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/envs/python3.6.13/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/envs/python3.6.13/include/python3.6m -c apex/contrib/csrc/multihead_attn/encdec_multihead_attn_cuda.cu -o build/temp.linux-x86_64-3.6/apex/contrib/csrc/multihead_attn/encdec_multihead_attn_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -gencode arch=compute_70,code=sm_70 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=fast_multihead_attn -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
#7 1138.1     In file included from apex/contrib/csrc/multihead_attn/encdec_multihead_attn_cuda.cu:16:0:
#7 1138.1     apex/contrib/csrc/multihead_attn/strided_batched_gemm.cuh:14:10: fatal error: cutlass/cutlass.h: No such file or directory
#7 1138.1      #include "cutlass/cutlass.h"
#7 1138.1               ^~~~~~~~~~~~~~~~~~~
#7 1138.1     compilation terminated.
#7 1138.1     error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
#7 1138.2     Running setup.py install for apex: finished with status 'error'
