### ISSUE TITLE
Error occurs when building 'apex_C' extension: no such file -> 'flatten_unflatten.o'

### ISSUE THREAD

**Issue by selous123** [NVIDIA/apex#961]
**Environment:** 
```
ubuntu 16.04
torch1.5
cuda 10.1
cudnn 7.6.5
```

**pip command:**
```
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Trace:**

```
 building 'apex_C' extension
    creating /tmp/pip-req-build-f9vrrykr/build/temp.linux-x86_64-3.7
    creating /tmp/pip-req-build-f9vrrykr/build/temp.linux-x86_64-3.7/csrc
    Emitting ninja build file /tmp/pip-req-build-f9vrrykr/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    1.9.0
    g++ -pthread -shared -B /home/ibrain/anaconda3/envs/torch15/compiler_compat -L/home/ibrain/anaconda3/envs/torch15/lib -Wl,-rpath=/home/ibrain/anaconda3/envs/torch15/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-req-build-f9vrrykr/build/temp.linux-x86_64-3.7/csrc/flatten_unflatten.o -L/home/ibrain/anaconda3/envs/torch15/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.7/apex_C.cpython-37m-x86_64-linux-gnu.so
    g++: error: /tmp/pip-req-build-f9vrrykr/build/temp.linux-x86_64-3.7/csrc/flatten_unflatten.o: No such file or directory
    error: command 'g++' failed with exit status 1
    Running setup.py install for apex ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-f9vrrykr
Removed build tracker: '/tmp/pip-req-tracker-iw0x478z'
ERROR: Command errored out with exit status 1: /home/ibrain/anaconda3/envs/torch15/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-f9vrrykr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-f9vrrykr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-ybwk6u82/install-record.txt --single-version-externally-managed --compile --install-headers /home/ibrain/anaconda3/envs/torch15/include/python3.7m/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/ibrain/anaconda3/envs/torch15/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/ibrain/anaconda3/envs/torch15/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 404, in run
    use_user_site=options.use_user_site,
  File "/home/ibrain/anaconda3/envs/torch15/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/home/ibrain/anaconda3/envs/torch15/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 829, in install
    scheme=scheme,
  File "/home/ibrain/anaconda3/envs/torch15/lib/python3.7/site-packages/pip/_internal/operations/install/legacy.py", line 72, in install
    cwd=install_req.unpacked_source_directory,
  File "/home/ibrain/anaconda3/envs/torch15/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 275, in runner
    spinner=spinner,
  File "/home/ibrain/anaconda3/envs/torch15/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/ibrain/anaconda3/envs/torch15/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-f9vrrykr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-f9vrrykr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-ybwk6u82/install-record.txt --single-version-externally-managed --compile --install-headers /home/ibrain/anaconda3/envs/torch15/include/python3.7m/apex Check the logs for full command output.

```

**Comment by selous123** [comment]
Everything goes will we i downgrade cuda to 10.0 and pytorch to 1.4.0

I think there may be same conflits between cuda10.1 and apex

**Comment by ilyak93** [comment]
Did you tried it on cuda 10.2 maybe ?

**Comment by liubaihua-bb** [comment]
I got the same problem, any other solutions?/(ㄒoㄒ)/~~
