### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by KrisWongz** [NVIDIA/apex#990]
Warning: Torch did not find available GPUs on this system.
 If your intention is to cross-compile, this is not an error.
By default, Apex will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
Volta (compute capability 7.0), Turing (compute capability 7.5),
and, if the CUDA version is >= 11.0, Ampere (compute capability 8.0).
If you wish to cross-compile for a single specific architecture,
export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    _, bare_metal_major, _ = get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
  File "setup.py", line 14, in get_cuda_bare_metal_version
    raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by 6cigarette** [comment]
I have the same questions.Now do you find the solution?

**Comment by Symbolk** [comment]
This occurs when you try to install apex on a non-GPU machine.

Run the following command would work:

```
cd apex
export TORCH_CUDA_ARCH_LIST="compute capability" 
python3 setup.py install
```

**Comment by BUAADreamer** [comment]
Hello, did you solve this problem? I tried `export TORCH_CUDA_ARCH_LIST="compute capability" ` but it can't work either.

**Comment by tzcskys** [comment]
> Hello, did you solve this problem? I tried `export TORCH_CUDA_ARCH_LIST="compute capability" ` but it can't work either.

Hi, I also met the problem, did you find the solution? thanks

**Comment by tzcskys** [comment]
> > Hello, did you solve this problem? I tried `export TORCH_CUDA_ARCH_LIST="compute capability" ` but it can't work either.
> 
> Hi, I also met the problem, did you find the solution? thanks

Hi, I found out the problem with my environment is that the cuda installed with conda is not the full version, which means the nvcc is not installed. So use "conda install -c nvidia cuda-nvcc" first and try again, works for me. Put my solution here in case someone meet the same problem.

**Comment by BUAADreamer** [comment]
> > > Hello, did you solve this problem? I tried `export TORCH_CUDA_ARCH_LIST="compute capability" ` but it can't work either.
> > 
> > 
> > Hi, I also met the problem, did you find the solution? thanks
> 
> Hi, I found out the problem with my environment is that the cuda installed with conda is not the full version, which means the nvcc is not installed. So use "conda install -c nvidia cuda-nvcc" first and try again, works for me. Put my solution here in case someone meet the same problem.

Yeah, I find the reason is I didn't install the whole package, I finally use conda env and pip3 install from source

**Comment by xywhat** [comment]
> > > > Hello, did you solve this problem? I tried `export TORCH_CUDA_ARCH_LIST="compute capability" ` but it can't work either.
> > > 
> > > 
> > > Hi, I also met the problem, did you find the solution? thanks
> > 
> > 
> > Hi, I found out the problem with my environment is that the cuda installed with conda is not the full version, which means the nvcc is not installed. So use "conda install -c nvidia cuda-nvcc" first and try again, works for me. Put my solution here in case someone meet the same problem.
> 
> Yeah, I find the reason is I didn't install the whole package, I finally use conda env and pip3 install from source



> > > Hello, did you solve this problem? I tried `export TORCH_CUDA_ARCH_LIST="compute capability" ` but it can't work either.
> > 
> > 
> > Hi, I also met the problem, did you find the solution? thanks
> 
> Hi, I found out the problem with my environment is that the cuda installed with conda is not the full version, which means the nvcc is not installed. So use "conda install -c nvidia cuda-nvcc" first and try again, works for me. Put my solution here in case someone meet the same problem.

you saved me!

**Comment by Fanstering** [comment]
> > > > Hello, did you solve this problem? I tried `export TORCH_CUDA_ARCH_LIST="compute capability" ` but it can't work either.
> > > 
> > > 
> > > Hi, I also met the problem, did you find the solution? thanks
> > 
> > 
> > Hi, I found out the problem with my environment is that the cuda installed with conda is not the full version, which means the nvcc is not installed. So use "conda install -c nvidia cuda-nvcc" first and try again, works for me. Put my solution here in case someone meet the same problem.


Thanks, I encountered the same problem, and successfully solved it with your method

**Comment by olayinkaajayi** [comment]
> > > Hello, did you solve this problem? I tried `export TORCH_CUDA_ARCH_LIST="compute capability" ` but it can't work either.
> > 
> > 
> > Hi, I also met the problem, did you find the solution? thanks
> 
> Hi, I found out the problem with my environment is that the cuda installed with conda is not the full version, which means the nvcc is not installed. So use "conda install -c nvidia cuda-nvcc" first and try again, works for me. Put my solution here in case someone meet the same problem.

Thank you so much! This appears to work for me.

**Comment by WilliamTambellini** [comment]
python could nt find nvcc. Could need:
```
PATH=/usr/local/cuda/bin/:$PATH pip ...
```

**Comment by MSaqibShah** [comment]
Got it sorted after trying out different things and digging into the web for answers. Ended up fixing it by installing the whole CUDA toolkit manually from [this link](https://developer.nvidia.com/cuda-downloads). Figured I'd drop it here in case anyone else is pulling their hair out over the same issue. Cheers!

**Comment by gndps** [comment]
It was happening because CUDA_HOME was not found in setup.py
i.e `from torch.utils.cpp_extension import CUDA_HOME` was None
To solve it, I installed CUDA from here https://developer.nvidia.com/cuda-downloads
Then tried the apex installation command in a new shell

**Comment by PussyCat0700** [comment]
> > > Hello, did you solve this problem? I tried `export TORCH_CUDA_ARCH_LIST="compute capability" ` but it can't work either.
> > 
> > 
> > Hi, I also met the problem, did you find the solution? thanks
> 
> Hi, I found out the problem with my environment is that the cuda installed with conda is not the full version, which means the nvcc is not installed. So use "conda install -c nvidia cuda-nvcc" first and try again, works for me. Put my solution here in case someone meet the same problem.

Hi, How can I specify version of nvcc installed with this command?

**Comment by SuperIRabbit** [comment]
In my case running `module load cuda/{YOUR_CUDA_VERSION}` solves the problem (inspired by the answers above about nvcc)
